### ISSUE TITLE
runtimeError

### ISSUE THREAD

**Issue by 13yong** [deepmodeling/dpgen#1007]
The following error was encountered while using dpgen：
### RuntimeError: Get error code 127 in calling cd /home/m-dpmd1/work/dpgen/a28ac5213a807204ab5f8e76b1ee3223bae1a059 && qsub 2abc6109033ff0a12ef8ac3459c36425d4447754.sub through ssh with job: a28ac5213a807204ab5f8e76b1ee3223bae1a059 . message: bash: qsub: command not found
But when I ssh the root, the "qsub *.sub" can be used normally. And also when I use the same machine.json with different accounts, it can also work.
So I need some suggests. Thank you!

**Comment by 13yong** [comment]
By the way, how to specify the maximum running time of the PBS task in the machine?

**Comment by njzjz** [comment]
Please see [documentation](https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/context.html#ssh)

> Note that SSH context is [non-login](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html), so bash_profile files will not be executed.

**Comment by 13yong** [comment]
> Please see [documentation](https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/context.html#ssh)
> 
> > Note that SSH context is [non-login](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html), so bash_profile files will not be executed.

Sorry I can not get your means.
My machine.json file is set as follows:
> > context_type": "SSH",
      "batch_type": "torque",
      "local_root": "./",
      "remote_root": "/home/m-dpmd1/work/dpgen",
      "remote_profile": {
       "hostname": "202.xxx.xxx.xxx",
       "username": "m-dpmd1",
       "password": "",
       "port": 22" "

It doesn`t work!
But the machine.json file is set as follows :

> > "context_type": "SSH",
      "batch_type": "torque",
      "local_root": "./",
      "remote_root": "/home/m-dpmd1/work/dpgen",
      "remote_profile": {
       "hostname": "202.xxx.xxx.xxx",
       "username": "m-zc3",
       "password": "",
       "port": 22

It will work normally !
And there is one *.sub in my remote_path, in theory there will be more.

**Comment by njzjz** [comment]
If different users have different behavior, the most possible reason is that their `.bashrc` have different contents.
