### ISSUE TITLE
Problems with dpgen simplify

### ISSUE THREAD

**Issue by Dankomaister** [deepmodeling/dpgen#1029]
Hi I have some issues with using `dpgen simplify` to reduce my large dataset of labeled images.

I’m using `dpgen` version [v0.10.6](https://github.com/deepmodeling/dpgen/releases/tag/v0.10.6) and what I want to accomplish is the following.
1. Randomly select a set of initial images from my dataset, let’s say 1000
2. Train an ensemble of models on this initial dataset (the selected images from step 1.), let’s say 4 models
3. Calculate the model deviation on the remaining data (the data that was not selected at step 1.)
4. Select 100 images based on the calculated model deviation in step 3. and the `model_devi_f_trust_lo` and `model_devi_f_trust_hi` parameters. Then add these 100 structures to the initial dataset
5. Train an ensemble of models on the updated dataset (initial dataset + added images from step 4.), let’s say 4 models

Repeat step 3 to 5 until there are no candidate structures left. I assume this is possible to do using `dpgen simplify` ?

I used the [qm7.json](https://github.com/deepmodeling/dpgen/blob/master/examples/simplify/qm7.json) example input as a starting point and apart from changing the obvious things like `type_map`, `pick_data` and `default_training_param`. I also set `"labeled": true` since my large dataset contains only labeled images and `"fp_style": "none"`, `"fp_task_min": 1`. However, I can’t seem to get things to work :(

In the first iteration `iter.000000` the initial dataset seems to be selected correctly however no training is performed. `dpgen` then crashes at the second iteration `iter.000001` when it tries to perform the model deviation since there are no models trained. If I manually copy some trained models into the `iter.000000/00.train/00*/` folders and restart `dpgen` then the model deviation in the second iteration passes and 100 new images seems to be selected. However no new training is done in the following iterations and `dpgen` just keeps running until the whole dataset is selected which is not as intended.

I’m not sure if the problem I’m facing is a bug or if I need to modify my input for this to work properly.
Please let me know,
Daniel
[simplify.zip](https://github.com/deepmodeling/dpgen/files/9986485/simplify.zip)

**Comment by njzjz** [comment]
`fp_task_min` may not work with `"labeled": true`. Before it's fixed, you need to set `fp_task_min` to 0.

**Comment by Dankomaister** [comment]
Okay I will try that, thanks!
I did try and not set `fp_task_min` in the simplify.json file but then it complained that it was missing.
Will this also fix the problem I have that no ensemble of models are trained on the initial dataset?

**Comment by Dankomaister** [comment]
Thanks @njzjz !

Setting `"fp_task_min": 0` worked however now when I try to run `dpgen simplify` on my real dataset I found another problem.
My data is organized in the same order as my type map, '"type_map": ["Fe", "C"]', i.e. the .raw files are in folders like Fe38C70.
This works fine for training and for the calculation of model deviation. But ones the new data is to be selected `iter.000001 task 05` then `dpgen` crashes with this error:
```
INFO:dpgen:-------------------------iter.000001 task 05--------------------------
Traceback (most recent call last):
  File "/home/daniel/.conda/envs/dpgen-0.10.6/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/home/daniel/.conda/envs/dpgen-0.10.6/lib/python3.8/site-packages/dpgen/main.py", line 185, in main
    args.func(args)
  File "/home/daniel/.conda/envs/dpgen-0.10.6/lib/python3.8/site-packages/dpgen/simplify/simplify.py", line 509, in gen_simplify
    run_iter(args.PARAM, args.MACHINE)
  File "/home/daniel/.conda/envs/dpgen-0.10.6/lib/python3.8/site-packages/dpgen/simplify/simplify.py", line 482, in run_iter
    post_model_devi(ii, jdata, mdata)
  File "/home/daniel/.conda/envs/dpgen-0.10.6/lib/python3.8/site-packages/dpgen/simplify/simplify.py", line 233, in post_model_devi
    subsys = sys_entire[name][idx]
  File "/home/daniel/.conda/envs/dpgen-0.10.6/lib/python3.8/site-packages/dpdata/system.py", line 1117, in __getitem__
    return self.systems[key]
KeyError: 'Fe48C32'
```
I figured out that this is because `dpdata` does not respect the type map but instead sorts the elements alphabetically.
However the results from the model deviation is read based on the filename of the data `# data.rest.old/Fe48C32` etc.
Not sure if this is a bug with `dpgen` or `dpdata`. The expected behavior, I guess, would be for `dpdata` to respect the type map if given and not sort elements alphabetically.

**Comment by njzjz** [comment]
I guess the type map is not be passed to the system object in this context...

**Comment by Dankomaister** [comment]
Seems like that, so we consider this a bug?
