### ISSUE TITLE
'find too many unsuccessfully terminated jobs'

### ISSUE THREAD

**Issue by SimonkingCat** [deepmodeling/dpgen#1043]
```find too many unsuccessfully terminated jobs. Too many FP tasks are not converged. Please check your input parameters (e.g.INCAR) or configuration (e.g. POSCAR) in directories 'iter.*.*/02.fp/task.*.*/.' ```

**Comment by HuangJiameng** [comment]
detailed description?

**Comment by HuangJiameng** [comment]
Hi, have you checked `your input parameters (e.g.INCAR) or configuration (e.g. POSCAR)` to found out  why `Too many FP tasks are not converged`?

**Comment by SimonkingCat** [comment]
> Hi, have you checked `your input parameters (e.g.INCAR) or configuration (e.g. POSCAR)` to found out why `Too many FP tasks are not converged`?

Yes, but I cant figure it out. Can I delete these frames to continue the calculation?

**Comment by njzjz** [comment]
Duplicate of #399
