### ISSUE TITLE
[BUG] The calypso interface is not available for the current devel branch

### ISSUE THREAD

**Issue by Chengqian-Zhang** [deepmodeling/dpgen#1065]
**Summary**

The calypso interface is not available for the current devel branch. “ArgumentValueError: [at root location] get invalid choice `calypso` for flag key `model_devi_engine`”

**DPGEN Version and Platform**

The newest devel branch.

**Expected Behavior**

Job successfully submitted.

**Actual Behavior**

![image](https://user-images.githubusercontent.com/100290172/205429308-034c1e26-f0de-4e20-8f4e-dd997921cf60.png)

**Steps to Reproduce**

![image](https://user-images.githubusercontent.com/100290172/205429326-7522601e-f15c-417b-a4c7-1bc6a4c6edd1.png)

**Comment by njzjz** [comment]
@y1xiaoc Is it expected when `strict=False`? I though loose checking will allow this situation but it looks not.

**Comment by y1xiaoc** [comment]
flag has to be in one if those choices. I don't think non strict mode would release this requirement, since it will not be able to do any checking in that case.

**Comment by njzjz** [comment]
Fixed in #1068.
