### ISSUE TITLE
get "undefined key "stop_batch" is not allowed in strict mode" error 

### ISSUE THREAD

**Issue by taipinghu** [deepmodeling/dpgen#1084]
### Summary

the above error occurs when init-model is used. 
after changing "numb_steps" to "stop_batch", it works normally. 

### DeePMD-kit Version

2.1.5

### TensorFlow Version

default version in deepmd kit 2.1.5

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

bohrium contain name: registry.dp.tech/dptech/deepmd-kit:2.1.5-cuda11.6

### Details

the above error occurs when init-model is used. 
after change the keyword numb_steps to stop_batch, it works normally.

**Comment by AnguseZhang** [comment]
This seems solved. I'll close this issue for now.
