### ISSUE TITLE
Submit script problem in slurm: "#SBATCH --gres=gpu"

### ISSUE THREAD

**Issue by caojiachun** [deepmodeling/dpgen#1093]
Unable to submit task properly due to keyword "#SBATCH --gres=gpu:0". Can I delete the key words in the script, or some other solution? 
![image](https://user-images.githubusercontent.com/71744229/209962929-35015f2f-a047-4658-8e8a-80cda3915ccf.png)

#!/bin/bash -l
#SBATCH --parsable
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 52
**#SBATCH --gres=gpu:0**
#SBATCH --partition cpu
ulimit -s unlimited

**Comment by AnguseZhang** [comment]
I think that you can delete the keyword related to `gpu` in `machine.json`and try again. (Notice that go backward before making the scripts by modiying `record.dpgen`).

**Comment by caojiachun** [comment]
> 
I have deleted the keyword `gpu_per_node`  in `machine.json`, but it doesn't seem to be working.
**machine.json**
      "resources": {
        "number_node": 1,
        "local_root":"./",
        "cpu_per_node": 52,
        "queue_name": "cpu",
        "group_size": 1,
        "custom_flags":["ulimit -s unlimited"]
**script.sub**
![image](https://user-images.githubusercontent.com/71744229/209966948-ccf72afe-13c9-4172-94b1-7f81f15610c2.png)

**Comment by njzjz** [comment]
You can use [`custom_gpu_line`](https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/resources.html#argument:resources[Slurm]/kwargs/custom_gpu_line) parameter.

**Comment by caojiachun** [comment]
> You can use [`custom_gpu_line`](https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/resources.html#argument:resources%5BSlurm%5D/kwargs/custom_gpu_line) parameter.

I removed the "#SBATCH --gres=gpu" content from "dpdispatcher/slurm.py" and it no longer appears in the my submit script.
