### ISSUE TITLE
init_bulk :   raise ValueError(f"Invalid format: `{str(fmt)}`")

### ISSUE THREAD

**Issue by ywu2019** [deepmodeling/dpgen#1108]
![1673005198691](https://user-images.githubusercontent.com/51308670/211006328-cf33a854-22cf-4f85-a70f-150897ad87dd.png)

**Comment by ywu2019** [comment]
Thank you for your help. When i run "dpgen run param.json machine.json", another error occur.
![1673061301047](https://user-images.githubusercontent.com/51308670/211128934-a6b54e65-001a-4d11-ae2d-f066f136cb4d.png)

**Comment by ZSHtju** [comment]
Still get this error with the latest devel branch.
![image](https://user-images.githubusercontent.com/23290538/214220807-cfca1beb-0b50-428d-8c06-6f55cbbf4c2f.png)
Please take a look, thanks.

**Comment by njzjz** [comment]
@ZSHtju fixed in #1126.

**Comment by ZSHtju** [comment]
> @ZSHtju fixed in #1126.

Thanks so much. Problem solved.

**Comment by DM0815** [comment]
> @ZSHtju fixed in #1126.
Excuse me .I met the same question. because the dp installed in an off-line server. Do I can solve the problem by installing the dp-v2.1.5(offline-packages) again?

**Comment by njzjz** [comment]
@DM0815 I am not sure what you mean. Here is dpgen but not deepmd-kit.

**Comment by DM0815** [comment]
> @DM0815 I am not sure what you mean. Here is dpgen but not deepmd-kit.

Sorry ，I didn't go into detail, I meant dpgen. I met the same question when  conducting dpgen init_bulk, and the reminding also same 'invalid foramt'....  the version of deepmdkit and dpgen is 2.1.5, and 0.11.0 ,resepcetively. I installed it last year. Becasue I've only recently used this function(dpgen init_bulk). Therefore, shoud I upgrade the dpgen version?

**Comment by DM0815** [comment]
@ZSHtju excuse me, I also met this question. Can I know your version of deepmdkit and dpgen at present. And do you met question now?

> > @ZSHtju fixed in #1126.
> 
> Thanks so much. Problem solved.

**Comment by ZSHtju** [comment]
> @ZSHtju excuse me, I also met this question. Can I know your version of deepmdkit and dpgen at present. And do you met question now?
> 

Hi, Currently I am using deepmd-kit 2.1.5 and the devel branch of dpgen. This problem has been solved in the devel branch of dpgen.

**Comment by DM0815** [comment]
> 

Thanks for your information. But when I uninstall dpgen installed, then git clone dpgen followed by installed  and git checkout -b devel origin/devel, and also show I'm on devel branch, but still reminds the same error(ValueError: Invalid format: `poscar.02x02x02/00.place_ele/poscar`). May be one of steps is wrong.Can you give me some advice? Thanks.

**Comment by DM0815** [comment]
> @ZSHtju by the way, I git clone repositories from gitee rather than github, I think their updates should be synchronized.

**Comment by DM0815** [comment]
> > @ZSHtju excuse me, I also met this question. Can I know your version of deepmdkit and dpgen at present. And do you met question now?
> 
> Hi, Currently I am using deepmd-kit 2.1.5 and the devel branch of dpgen. This problem has been solved in the devel branch of dpgen.

Tks, help me a lot, it's solved.
