### ISSUE TITLE
conducting dpgen init_bulk reminding list index out of range

### ISSUE THREAD

**Issue by DM0815** [deepmodeling/dpgen#1140]
The param.json as follows:
{
  "api_version": "1.0",
  "_deepmd_version": "2.1.0",
  "train" :[
    {
      "command": "dp",
      "machine": {
        "batch_type": "PBS",
        "context_type": "local",
        "local_root" : "./",
        "remote_root":"/public/home/dmeng/MD/0215dp/con"
      },
      "resources": {
        "number_node": 1,
        "cpu_per_node": 4,
        "gpu_per_node": 0,
        "queue_name":"batch",
        "group_size": 4
      }
    }
],
  "model_devi":
    [{
      "command": "lmp -i input.lammps -v restart 0",
      "machine": {
        "batch_type": "PBS",
        "context_type": "local",
        "local_root" : "./",
        "remote_root":"/public/home/dmeng/MD/0215dp/con"
      },
      "resources": {
        "number_node": 1,
        "cpu_per_node": 4,
        "gpu_per_node": 0,
        "queue_name":"batch",
        "group_size": 4
      }
    }
],
  "fp":
    [{
      "command": "ulimit -s unlimited && ulimit -l unlimited && ulimit -t unlimited  && export OMP_NUM_THREADS=1 &&  mpirun -n 4 /public/home/dmeng/vasp.5.4.4/bin/vasp_std",
      "machine": {
        "batch_type": "PBS",
        "context_type": "local",
        "local_root" : "./",
        "remote_root":"/public/home/dmeng/MD/0215dp/con"
      },
      "resources": {
        "number_node": 1,
        "cpu_per_node": 4,
        "gpu_per_node": 0,
        "queue_name":"batch",
        "group_size": 4,
        "custom_flages":[ "#PBS -l nodes=node6:ppn=52 ##+node2:ppn=52",
                          "#PBS -j oe",
                          "##PBS -q batch"],
        "source_list": ["/public/softwares/intel/oneapi/setvars.sh intel64"]
      }
    }
]  
}
what's more, in the fp.log reminds "/var/spool/torque/mom_priv/jobs/4285.mgr.SC: 第 24 行:ulimit: stack size: 无法修改 limit 值: 不允许的操作",but I have added the ulimit command .
Could you help me.?I can't find the question

**Comment by DM0815** [comment]
Traceback (most recent call last):
  File "/public/home/dmeng/dpgen/bin/dpgen", line 10, in <module>
    sys.exit(main())
  File "/public/home/dmeng/dpgen/lib/python3.8/site-packages/dpgen/main.py", line 185, in main
    args.func(args)
  File "/public/home/dmeng/dpgen/lib/python3.8/site-packages/dpgen/data/gen.py", line 1425, in gen_init_bulk
    run_vasp_relax(jdata, mdata)
  File "/public/home/dmeng/dpgen/lib/python3.8/site-packages/dpgen/data/gen.py", line 1056, in run_vasp_relax
    submission.run_submission()
  File "/public/home/dmeng/dpgen/lib/python3.8/site-packages/dpdispatcher/submission.py", line 180, in run_submission
    self.update_submission_state()
  File "/public/home/dmeng/dpgen/lib/python3.8/site-packages/dpdispatcher/submission.py", line 226, in update_submission_state
    job.get_job_state()
  File "/public/home/dmeng/dpgen/lib/python3.8/site-packages/dpdispatcher/submission.py", line 588, in get_job_state
    job_state = self.machine.check_status(self)
  File "/public/home/dmeng/dpgen/lib/python3.8/site-packages/dpdispatcher/pbs.py", line 65, in check_status
    status_word = status_line.split ()[-2]        
IndexError: list index out of range

**Comment by AnguseZhang** [comment]
> File "/public/home/dmeng/dpgen/lib/python3.8/site-packages/dpdispatcher/pbs.py", line 65, in check_status
> status_word = status_line.split ()[-2]

This's probably because your PBS version is not standard or too old.

**Comment by AnguseZhang** [comment]
> ulimit -s unlimited && ulimit -l unlimited && ulimit -t unlimited

It seems that you do not have the permission to run `ulimit -s unlimited && ulimit -l unlimited && ulimit -t unlimited ` in your cluster. You can contact your cluster administrator.

**Comment by DM0815** [comment]
Thanks for your information. I will try
