### ISSUE TITLE
Problem with the cutoff radius in the dataset

### ISSUE THREAD

**Issue by flagiu** [deepmodeling/dpgen#1148]
Summary: Problem with the cutoff radius in the dataset.

The Cu dataset used in your paper https://doi.org/10.1016/j.cpc.2020.107206 shows some samples with ~7A box side but the cutoff radius used in the training is fixed to 8A. I'm wondering how are you applying periodic boundary conditions (PBC) with a box side smaller than the cutoff. Or have you switched off PBC to compute the model descriptors during training?

Thanks for the help,

Flavio Giuliani

**Comment by wanghan-iapcm** [comment]
One includes not only the nearest periodic neighbors but also other periodic neighbors when the cutoff is larger than half of the simulation cell. 
We notice that some MD packages only searches nearest periodic neighbors, but deepmd-kit considers all possible neighbors if necessary.
