### ISSUE TITLE
When dpdata converted datasets from cp2k_aimd, some mistakes occurs, just like enclosed below. Thus, What can I solve this problems?

### ISSUE THREAD

**Issue by jiaweiGe472** [deepmodeling/dpgen#1152]
<img width="1258" alt="微信图片_20230314090222" src="https://user-images.githubusercontent.com/109841608/224865520-29e06a42-56b1-450d-ae40-7bdfcaf719f9.png">
[profiles.zip](https://github.com/deepmodeling/dpgen/files/10963153/profiles.zip)

**Comment by robinzyb** [comment]
Hello, I can't find forces in your output log or `-frc-1.xyz` file. If you have the `-frc-1.xyz` file, try install [cp2kdata](https://github.com/robinzyb/cp2kdata). And see [cp2kdata for dpdata](https://github.com/robinzyb/cp2kdata#plug-in-for-dpdata)

**Comment by robinzyb** [comment]
At this time, I believe it may be best to close this particular issue. However, this issue can be reopened if further information is provided.

**Comment by robinzyb** [comment]
@njzjz please help me to close this issue, thank you!
