### ISSUE TITLE
when install dpgen, succeeded, but the pymatgen path and version is unknown

### ISSUE THREAD

**Issue by JTaozhang** [deepmodeling/dpgen#1159]
(ZT-py39) [ZT@master ~]$ dpgen -h
DeepModeling
------------
Version: 0.11.0
Path:    /public/home/ZT/.conda/envs/ZT-py39/lib/python3.9/site-packages/dpgen

Dependency
------------
     numpy     1.23.5   /public/home/ZT/.conda/envs/ZT-py39/lib/python3.9/site-packages/numpy
    dpdata     0.2.13   /public/home/ZT/.conda/envs/ZT-py39/lib/python3.9/site-packages/dpdata
  pymatgen            unknown version or path
     monty   2022.9.9   /public/home/ZT/.conda/envs/ZT-py39/lib/python3.9/site-packages/monty
       ase     3.22.1   /public/home/ZT/.conda/envs/ZT-py39/lib/python3.9/site-packages/ase
  paramiko      3.0.0   /public/home/ZT/.conda/envs/ZT-py39/lib/python3.9/site-packages/paramiko
 custodian  2022.5.26   /public/home/ZT/.conda/envs/ZT-py39/lib/python3.9/site-packages/custodian

Moreover, when I run the small test of CH4 in the ini file, using command " dpgen init_bulk param.json", it report an
**error**
 (   File "/public/home/zhangtao/anaconda3/envs/ZT-py39/lib/python3.9/site-packages/pymatgen/core/structure.py", line 2518, in to
    raise ValueError(f"Invalid format: `{str(fmt)}`")
ValueError: Invalid format: `ch4.poscar.01x01x01/00.place_ele/poscar   ) 

, which has been discussed in this community before.  According to the answer, it is the incompatibility problem of pymatgen. the developer also said he has fixed it(This error has been fixed by https://github.com/deepmodeling/dpgen/pull/1085 and https://github.com/deepmodeling/dpgen/pull/1126. Please update the code.). So I use command "pip install dpgen" reinstalled dpgen, and  I still meet this problem and "pymatgen unknown version and path". 

So, Whether the version of dpgen 0.11.0 has fixed this problem or there are some other problem also could acount for this?

**Comment by DM0815** [comment]
gitclone -b devel  dpgen(url)

**Comment by liu-stewart** [comment]
I suspect it is due to a version incompatibility issue. I have provided a temporary solution. You can see the code in the error prompt：

    #minor bug for element symbol behind the coordinates
    from_struct=Structure.from_file(from_file)
    from_struct.make_supercell(super_cell)
    from_struct.to('poscar', to_file)

but this method <to> in pymatgen .core.structure line 2460, the parameters are :

    def to(self, filename: str = "", fmt: str = "", **kwargs) -> str | None:

you can clearly observe that the fmt should be the second parameter, so you should change the 
    from_struct.to('poscar', to_file)
to
    from_struct.to(to_file,'poscar')

**Comment by njzjz** [comment]
0.11.1 has been released, which includes #1085 and #1126.

**Comment by twoslucky** [comment]
I downgraded the pymatgen version to 2022.3.24 and still encountered errors. After that, I updated to the latest dpgen version, but the issue persisted. Currently, the pymatgen version is 2022.3.24, and the dpgen version is 0.11.1.
（nohup: ignoring input
Traceback (most recent call last) :
File " /opt/anaconda3/bin/dpgen"，line 5，in <m
odule>
from dpgen.main import main
File "/opt/anaconda3/lib/python3.8/site-packages/dpgen/main.py",line 11,in <module>
from dpgen.auto_test.run import gen_test
File "/opt/anaconda3/lib/python3.8/site-packages/dpgen/auto_test/run.py""，line 9, in <module>
from dpgen.auto_test.common_prop import make_property,post_property，run_property
File "/opt/anaconda3/lib/python3.8/site-packages/dpgen/auto_test/common_prop.py", line 14, in <module>
from dpgen.auto_test.Interstitial import Interstitial
File " /opt/anaconda3/lib/python3.8/site-packages/dpgen/auto_test/Interstitial.py", line 8, in <module>
from pymatgen. analysis.defects.generators import InterstitialGeneratorModuleNotFoundError: No module named 'pymatgen.analysis.defects.generators'）

**Comment by twoslucky** [comment]
When checking the version information of dpgen, pymatgen unknown version or path appears. How should this issue be resolved, along with the error File "/opt/anaconda3/lib/python3.8/site packages/dpgen/auto_test/Interstitial. py", line 8, in

From pymatgen Analysis. defects. generators import InterntialGeneratorModuleNotFoundError: No module named 'pymatgen. analysis. defects. generators', have you contacted me?
