### ISSUE TITLE
Running dpgen run with fp_style pwscf

### ISSUE THREAD

**Issue by ErinEEEEE** [deepmodeling/dpgen#1181]
**Summary**

Running dpgen run on a json file with:
`     "fp_style": "pwscf",`
returns the error:
`get invalid choice pwscf for flag key fp_style`
though this is listed as a possible choice in the documentation.

**DPGEN Version and Platform**

0.11.0 on arm64 MacOS 12 (installed via pip)

**Job submission and computing cluster configuration**

Not relevant

**Details**

I understand e.g. init_bulk is only available for vasp and abacus so in order to use dpgen run using Quantum Espresso, I need to set up the initial ab initio MD data manually. However, as written above, the program terminates during the dpgen run process when I specify this format (pwscf) in my input files. The documentation does not specify how to use dpgen with Quantum Espresso in detail. Are there any examples available online?

**Comment by njzjz** [comment]
See #1067. Please use the latest code.
