### ISSUE TITLE
[BUG] _CP2K input file keyword error when adding 'PRINT'_

### ISSUE THREAD

**Issue by h840473807** [deepmodeling/dpgen#1204]
**Summary**

When using CP2K for 02.fp generation in Dpgen, several keywords are automatically written to the input file, located under the FORCE_EVAL section. 

&FORCE_EVAL
……
&PRINT
&FORCES ON
&END FORCES
&STRESS_TENSOR ON
&END STRESS_TENSOR
&END PRINT
&END FORCE_EVAL

However, when I add the "print" keyword under the SCF section, the position of the automatically added keywords by Dpgen **becomes incorrect**, appearing under the SCF section instead of the FORCE_EVAL section (SCF is second-level subfield of FORCE_EVAL). 

&FORCE_EVAL
&DFT
……
&SCF
……
&PRINT
&RESTART
BACKUP_COPIES 0
&END RESTART
&FORCES ON
&END FORCES
&STRESS_TENSOR ON
&END STRESS_TENSOR
&END PRINT
&END SCF
&END DFT
&END FORCE_EVAL

**The correct keyword should be as follows:**

&FORCE_EVAL
&DFT
……
&SCF
……
&PRINT
&RESTART
BACKUP_COPIES 0
&END RESTART
&END PRINT
&END SCF
&END DFT
&PRINT
&FORCES ON
&END FORCES
&STRESS_TENSOR ON
&END STRESS_TENSOR
&END PRINT
&END FORCE_EVAL

I guess that Dpgen may automatically add these keywords under the first PRINT section in the CP2K input file, and this may cause an error when there are multiple PRINT sections in the file.

**0.10.6**

**Job submission and computing cluster configuration**

**Expected Behavior**

&FORCE_EVAL
&DFT
……
&SCF
……
&PRINT
&RESTART
BACKUP_COPIES 0
&END RESTART
&END PRINT
&END SCF
&END DFT
&PRINT
&FORCES ON
&END FORCES
&STRESS_TENSOR ON
&END STRESS_TENSOR
&END PRINT
&END FORCE_EVAL

**Actual Behavior**

&FORCE_EVAL
&DFT
……
&SCF
……
&PRINT
&RESTART
BACKUP_COPIES 0
&END RESTART
&FORCES ON
&END FORCES
&STRESS_TENSOR ON
&END STRESS_TENSOR
&END PRINT
&END SCF
&END DFT
&END FORCE_EVAL

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by robinzyb** [comment]
hello, could you provide the cp2k input template for dpgen that may cause errors?

**Comment by h840473807** [comment]
Thank you for your reply, I have uploaded the param.json and a geometry file 0.lammpstrj. The key areas are in these lines as follows. These lines of keywords are added to prevent. wfn from being generated in each SCF iteration and occupying too many disks.
                    "PRINT":{
                          "RESTART": {
                                "BACKUP_COPIES": 0   
                             }
                       }

[param.json.txt](https://github.com/deepmodeling/dpgen/files/11468763/param.json.txt)
[0.lammpstrj.txt](https://github.com/deepmodeling/dpgen/files/11468764/0.lammpstrj.txt)

**Comment by robinzyb** [comment]
Hello, 
    I no longer maintain the dictionary way to setup the cp2k because it causes many problem. In your case, it is some wrong with the dictionary update in the dpgen.
   In general, I recommend just using the external cp2k template as your input, see https://github.com/deepmodeling/dpgen/tree/devel/examples/run/dp1.x-lammps-cp2k/methane. 
  Note that in the input, you must present a KEYWORD `ABC` in the section `CELL` so that the DP-GEN can replace the cell on-the-fly. In addition, you need to add  these lines under `FORCE_EVAL` section to print forces and stresses.

```
  STRESS_TENSOR ANALYTICAL
  &PRINT
    &FORCES ON
    &END FORCES
    &STRESS_TENSOR ON
    &END STRESS_TENSOR
  &END PRINT
``` 

The rest of lines in cp2k input may be customized as you like.

**Comment by phyoung123** [comment]
Hi, I just happened to be involved in this incident, did you fix it?

**Comment by phyoung123** [comment]
@h840473807

**Comment by h840473807** [comment]
Thank you for your reply. I have solved this problem according to your suggestion.

**Comment by phyoung123** [comment]
> Thank you for your reply. I have solved this problem according to your suggestion.
Add these lines?
`  STRESS_TENSOR ANALYTICAL
  &PRINT
    &FORCES ON
    &END FORCES
    &STRESS_TENSOR ON
    &END STRESS_TENSOR
  &END PRINT`

**Comment by phyoung123** [comment]
> 

Add these lines in `FORCE_EVAL`?

STRESS_TENSOR ANALYTICAL
  &PRINT
    &FORCES ON
    &END FORCES
    &STRESS_TENSOR ON
    &END STRESS_TENSOR
  &END PRINT

**Comment by robinzyb** [comment]
@h840473807 @phyoung123 happy to see this problem has been solved. If no further question, could you close this issue? Many thanks

**Comment by robinzyb** [comment]
For any question about how to prepare cp2k input for dpgen, I updated the doc https://docs.deepmodeling.com/projects/dpgen/en/devel/run/param.html#argument:run_jdata[fp_style=cp2k]/external_input_path
