### ISSUE TITLE
[Feature Request] _dpgen simplify with ABACUS_

### ISSUE THREAD

**Issue by AroundPeking** [deepmodeling/dpgen#1222]
**Summary**

"dpgen simplify"  do not support ABACUS fp calculation.

**Detailed Description**

When I wanna utilize concurrent algorithm to simplify an existing dataset, it is found that "dpgen simplify" only supports VASP/gaussian fp software. I wonder that you could develop interface with ABACUS, while "dpgen run" have already supported ABACUS.

In ....../dpgen/dpgen/simplify/simplify.py:
![b2b6cdd7fbe6080e17ab1d2c69462d0](https://github.com/deepmodeling/dpgen/assets/108850865/94bf16ae-4ac7-49bd-a7ce-6e99058de27c)

**Comment by njzjz** [comment]
Resolved in #1235.
