### ISSUE TITLE
[BUG] _lammps input error_

### ISSUE THREAD

**Issue by AroundPeking** [deepmodeling/dpgen#1265]
**Summary**

I'd like to utilize "dpgen simplify" to select a few structures from much larger dataset, almost 10 thousand (already having DFT results), to do DFT calculations at higher level.

However, after finishing the iter.000000, I found iter.000001 ended with "ERROR: Invalid command-line argument (src/lammps.cpp:297)". 

Actually, it was command in the script generated by DPGEN that lead to this failure. 
```(lmp -i input.lammps -v restart 0 model-devi -m ./graph.000.pb ./graph.001.pb ./graph.002.pb ./graph.003.pb -s data.rest.old -o details ) 1>>model_devi.log 2>>model_devi.log```
And in my working directory, there was no file *"input.lammps"*. It was likely that some errors appeared in my *para.json*. 

Besides, I wonder whether I need to add *"sys_configs"* in the *para.json*, including all the structures for simplifying. 
![1688533231505](https://github.com/deepmodeling/dpgen/assets/108850865/55d8e6d6-3848-4403-9da4-81c4097db032)
I noticed that in *dpgen/examples/simplify-MAPbI3-scan-lebesgue/simplify_example* it gives [null].

**DPGEN Version and Platform**

DPGEN 0.11.1.dev63+gbd9a72e

**Further Information, Files, and Links**
Here are script generated by DPGEN in my working directory and my *para.json* . 
[simplify.zip](https://github.com/deepmodeling/dpgen/files/11953996/simplify.zip)

**Comment by njzjz** [comment]
`dpgen simplify` uses DeePMD-kit to perform the model deviation calculation. You gave the path to LAMMPS instead.

**Comment by AroundPeking** [comment]
Thanks, so which keyword I can set in *para.json* to use DeePMD to perform model_devi instead of LAMMPS?

**Comment by njzjz** [comment]
> which keyword

https://docs.deepmodeling.com/projects/dpgen/en/latest/simplify/simplify-mdata.html#argument:simplify_mdata/model_devi/command

**Comment by njzjz** [comment]
> When iteration begins, it will add the picked data to the training dataset for 4 models.

Did you see this behavior? The data in `pick_data` is only added after calculating model deviation. Not all data will be used.

**Comment by njzjz** [comment]
I got your point. You added the same data into `init_data` and `pick_data`, which is not the correct usage for `dpgen simplify`.

`init_data` will be 100% added to the training data. In `pick_data`, only data points with large model deviation will be added to the training data during active learning cycles. They should not override.

**Comment by AroundPeking** [comment]
Yep, only data points with large model deviation will be added. But they also came from `init_data` to be the same structure, instead of lammps MD?

**Comment by njzjz** [comment]
`dpgen simplify` never runs LAMMPS MD.
