### ISSUE TITLE
[Parameters] Different INCAR can be selected based on "sys_configs" during fp phase.

### ISSUE THREAD

**Issue by Ternity** [deepmodeling/dpgen#1266]
**Summary**
When using VASP for fp, I hope to use different INCAR for different sys_configs, because I need to set corresponding initial magnetic moments in INCAR for different sys_configs, otherwise SCF is not easy to converge.

**Detailed Description**
Specifically,
for sys_ configs 1, the system has 10 Fe and 20 O, MAGOM should be set to 10 * 2.0 20 * 2.0 in INCAR; 
for sys_ configs 2, the system has 10 Fe and 21 O, MAGOM should be set to 10 * 2.0 21 * 2.0 in INCAR.

Although there have been some discussions indicating that this may seem a dangerous approach([issue726](https://github.com/deepmodeling/dpgen/issues/726)), I still hope to implement the new feature mentioned above in DPGEN. Or it can be implemented in DPGEN2?

Thank you very mach!

**Comment by wanghan-iapcm** [comment]
You may need to hack the `make_vasp_incar` https://github.com/deepmodeling/dpgen/blob/4be4f6daea8373858a7da98a14f704e52e2ba4dc/dpgen/generator/run.py#L2759-L2773 to implement a configuration dependent INCAR preparation.  This function is called at the folder of the FP task, see https://github.com/deepmodeling/dpgen/blob/4be4f6daea8373858a7da98a14f704e52e2ba4dc/dpgen/generator/run.py#L2869-L2871
Therefore, you may load the POSCAR, check the configuration, and write the correct MAGOM to the INCAR.

**Comment by Ternity** [comment]
Thank you to @wanghan-iapcm for your answer，I will try it.
