### ISSUE TITLE
the parameters settings of machine.json 

### ISSUE THREAD

**Issue by Liang1Kai** [deepmodeling/dpgen#1295]
Hi developer,
     I use a personal computer to do my calculations. In the file 'machine.json', How should i set the parameters of for "Bath type:" and "context_type:".
     Thanks fo reply!

**Comment by njzjz** [comment]
Please refer to [dpdispatcher documentation](https://dpdispatcher.rtfd.io).

**Comment by njzjz** [comment]
Feel free to reopen if the problem still exists. Thank you.
