### ISSUE TITLE
Hello, I would like to ask some questions about dpgen and dpdata in converting VASP calculation results into DeepMD

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/dpgen#1299]
1. The NELM in INCAR is set to 80, and the OUTCAR on the right side of the screenshot shows that this is an unconverted task, but dpgen included it in the dataset production.
2.  Collect this round of fp tasks using a script (Figure 2), eliminate the bad point, but repeat the previous data point. Also: dpgen version: 0.10.6 dpdata version: 0.2.13
![3261690877580_ pic](https://github.com/deepmodeling/dpgen/assets/122335090/33a9ed0f-4ae4-4dac-9cda-93720af98796)
![3271690877580_ pic](https://github.com/deepmodeling/dpgen/assets/122335090/6398c35a-1f2c-4911-b084-ce565546b30a)

**Comment by njzjz** [comment]
Could you provide this OUTCAR file?

**Comment by XuFanffei** [comment]
Currently unable to provide reference files
