### ISSUE TITLE
The traj folder was not generated during DPGEN, but the subsequent labeling can continue

### ISSUE THREAD

**Issue by ccww468** [deepmodeling/dpgen#1300]
When I was running DP-GEN, I found that in the process of model_devi, each task should recycle a traj folder. This track folder should be used to select candidates to run single-point energy calculations, but I checked the results after the run There is no traj folder in the model_devi task, but the subsequent labeling can continue to run. Why?
![image](https://github.com/deepmodeling/dpgen/assets/140952848/30d09f04-f837-4d21-ab39-994288011da4)
![image](https://github.com/deepmodeling/dpgen/assets/140952848/13d88d2e-74f8-4a2a-94f6-09f5e8a4d2b4)

**Comment by njzjz** [comment]
The default behavior is to delete the trajectory after candidates are selected. The [`model_devi_clean_traj`](https://docs.deepmodeling.com/projects/dpgen/en/latest/run/param.html#argument:run_jdata[model_devi_engine=lammps]/model_devi_clean_traj) option can control this behavior.

**Comment by njzjz** [comment]
Feel free to reopen if the problem still exists. Thank you.
