### ISSUE TITLE
[BUG] _dpgen simplify with fparam

### ISSUE THREAD

**Issue by chtchelkatchev** [deepmodeling/dpgen#1303]
Dpgen_0.11.0 (conda version) in simplify mode does not peak up fparam.npy from the database as follows from 01.model_devi produced by dpgen simplify. Thus INCAR's in 02.fp are not modified with smearing related to electron temperature. Nesessary parameters for electron temperature treatment have been added in param.json
****
"use_ele_temp":	1,
****
"fitting_net":  {
              "neuron"   :      [240, 240, 240],
              "resnet_dt":      true,
              "trainable":      [true, true, true, true],
	      "seed"     :	0,
              "numb_fparam":	1
              }

**Comment by wanghan-iapcm** [comment]
fparam may be interpreted in different meanings. At the presence of `use_ele_temp=1`, it is the global electron temperature.  I would prefer (2) or (3), the new data type is defined if we find `use_ele_temp=1`. 

the fparam data is written in a job.json file in the fp folder (symlinked from model devi folder),
https://github.com/deepmodeling/dpgen/blob/4be4f6daea8373858a7da98a14f704e52e2ba4dc/dpgen/generator/run.py#L1484-L1487
 then information will be correct used to setup vasp jobs (only supported by vasp jobs) https://github.com/deepmodeling/dpgen/blob/4be4f6daea8373858a7da98a14f704e52e2ba4dc/dpgen/generator/run.py#L2869-L2878

**Comment by chtchelkatchev** [comment]
Thank You for answer! Hopefully the possibility will be available in a new version of dpgen. By the way, "dpgen collect" does not collect fparam-files in Dpgen_0.11.0. Also dpgen collect does not produce anything after dpgen simplify...

**Comment by njzjz** [comment]
@amcadmus We need a new version of dpdata for the support of https://github.com/deepmodeling/dpdata/pull/476.
