### ISSUE TITLE
vasp KILLED BY SIGNAL: 9 (Killed).

### ISSUE THREAD

**Issue by Liang1Kai** [deepmodeling/dpgen#1308]
Hello Developer,
When I run the init-bulk process, the vasp program is terminated when I reach the third step to run a short md,it shows :
    BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES,
   RANK 7 PID 3703 RUNNING AT lk-virtual-machine,
   KILLED BY SIGNAL: 9 (Killed).
Stage 1 and 2 work normally.When I run stage 3  with vasp, it also works fine. This is my INCAR_md file:
PREC=A
ENCUT=450
ISYM=0
ALGO=Fast

EDIFF=1.000000e-06
EDIFFG = -0.02
LREAL=.False.

ISPIN=2
ISIF=2
ISMEAR=0
SIGMA=0.10000
IBRION=0
POTIM=0.5
SMASS = 0
TEBEG = 300
TEEND = 300
#NBLOCK = 1
#KBLOCK = 100
NSW=20

LWAVE=F
LCHARG=F
PSTRESS=0
KSPACING=0.3000
KGAMMA=.FALSE.
NPAR=8
KPAR=4
#NCORE = 8
How could I solve this problem, Thanks so so somuch!

Have a nice day!

**Comment by njzjz** [comment]
I am going to close the issue as no one here is the developer of VASP and knows why it got killed. It should not be related to the dpgen package.
