### ISSUE TITLE
[Feature Request] _QE convergence check_

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/dpgen#1333]
**Summary**

For QE first principle calculations, if there exist some not convergent cases, dpdata will report error. 

**Detailed Description**

I hope DPGEN can solve those cases like what VASP could give. Maybe skip those cases. 

**Further Information, Files, and Links**
Please find attached the file of DPGEN 02.fp with qe, I just want to collect the data. 
[02.fp.zip](https://github.com/deepmodeling/dpgen/files/12607205/02.fp.zip)

**Comment by AnguseZhang** [comment]
I think we can first implement the function which checks the convergence in `dpdata`, then figure out whether DP-GEN needs fix.

See
https://github.com/deepmodeling/dpdata/blob/acdc06fbff16063bd9d7377cafa4f059182a31d5/dpdata/vasp/outcar.py#L141C9-L142C36
