### ISSUE TITLE
When I used doyen , an error message for 'RuntimeError: systems with inconsistent formula could not be append' appeared.

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/dpgen#1336]
[raise Runtimeerror ('systems with inconsistent formula could not be append: %s V.s. %s' : (self. unig_formula, system. unit formula)) RuntimeError: systems with inconsistent formula could not be append: Fe99 v.s. Fe98]

**Comment by njzjz** [comment]
#351 may help
