### ISSUE TITLE
error in init_reaction: Cannot read the bulid_resurceses parameter in machine.json

### ISSUE THREAD

**Issue by caojiachun** [deepmodeling/dpgen#1351]
**I configured the parameters of machine.json according to the instructions, but an error was reported when I ran the build module.**

![image](https://github.com/deepmodeling/dpgen/assets/71744229/ea5012d3-79ab-47f9-a315-40e87bb28e0a)

**DPGEN Version: 0.10.6**
my machine.json:
{
  "api_version": "1.0",
  "deepmd_version": "2.0.1",

"reaxff":
    [{
      "command": "source /nfs/home/2001_aozhimin/bin/pairlmp.sh && mpirun -np 96 lmp",
      "machine": {
        "batch_type": "Slurm",
        "context_type": "local",
        "local_root" : "./",
        "remote_root":"./work"
      },
      "resources": {
        "number_node": 1,
        "local_root":"./",
        "cpu_per_node": 96,
        "gpu_per_node": 0,
        "queue_name": "fatcpu",
        "group_size": 1,
        "source_list":[""],
        "custom_flags":["source /nfs/home/2001_aozhimin/intel/oneapi/setvars.sh","ulimit -s unlimited","conda activate /nfs/home/2001_aozhimin/apps/deepmd-kit-cpu"]
      }
    }],

"build":
    [{
      "command": "datasetbuilder",
      "machine": {
        "batch_type": "Slurm",
        "context_type": "local",
        "local_root" : "./",
        "remote_root":"./work"
      },
      "resources": {
        "number_node": 1,
        "local_root":"./",
        "cpu_per_node": 96,
        "gpu_per_node": 0,
        "queue_name": "fatcpu",
        "group_size": 1,
        "source_list":[""],
        "custom_flags":["conda activate /nfs/home/2001_aozhimin/apps/deepmd-kit-cpu"]
      }
    }],

"fp":
      [{
              "command": "g16 < input > output ||:",
                "machine": {
                                          "batch_type": "Slurm",
                                          "context_type": "local",
                                          "local_root" : "./",
                                          "remote_root":"./work"
                                  },
               "resources": {
                                          "number_node": 1,
                                          "local_root":"./",
                                          "cpu_per_node": 96,
                                           "_gpu_per_node": 0,
                                           "queue_name": "fatcpu",
                                          "group_size": 200,
                                         "module_list": [""],
                                        "custom_flags":["ulimit -s unlimited"],
                                        "source_list": [""]
                                                                }
                                                              }
                                                            ]

}

**Comment by caojiachun** [comment]
I add the 'task_per_cpu' in the 'resources' of 'fp' and 'build' .

**Comment by njzjz** [comment]
It seems to be a bug that needs to fix.
