### ISSUE TITLE
bug in build process of init_reaction :  mddatasetbuilder program is not running properly.

### ISSUE THREAD

**Issue by caojiachun** [deepmodeling/dpgen#1353]
**Version of 'mddatasetbuilder.dps' does not match when running mddatasetbuilder**

![image](https://github.com/deepmodeling/dpgen/assets/71744229/ca76a006-eee0-42dc-8365-f0b72eecf5db)

**Comment by njzjz** [comment]
A bug from Cython causes this. See https://github.com/cython/cython/pull/5691. The message can be safely ignored.

**Comment by caojiachun** [comment]
Thank you!
