### ISSUE TITLE
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'

### ISSUE THREAD

**Issue by Suyoung999999999** [deepmodeling/dpgen#1361]
[param.json](https://github.com/deepmodeling/dpgen2/files/13065492/param.json)
I encountered an error when doing dpgen calculation, would like to ask how to solve it? I have uploaded the param.json file and the error file
[Uploading Gradia-run.err…]()

**Comment by wanghan-iapcm** [comment]
I cannot open the error log, please check the link.

**Comment by njzjz** [comment]
`init_data_sys` should be `list[str]` instead of `list[list[str]]`
