### ISSUE TITLE
Dpgen-enhance

### ISSUE THREAD

**Issue by Suyoung999999999** [deepmodeling/dpgen#1384]
### Summary

I want to do dpgen calculations by using a custom input.lammps and using enhanced sampling. Now found a case (https://github.com/deepmodeling/dpgen/tree/master/examples/run/dp-lammps-enhance_sampling) but I want to learn the input. plumed file all configurable parameters of the template, would you like to ask whether it is provided?

### DP-GEN Version

2.2.2

### Details

I would like to get a detailed dpgen enhanced sampling tutorial

**Comment by robinzyb** [comment]
please checkout the official website of Plumed for the tutorial https://www.plumed.org/doc

**Comment by Suyoung999999999** [comment]
Thanks for the help


| |
su18812625523
|
|
***@***.***
|
On 11/2/2023 21:27，Yongbin ***@***.***> wrote：

please checkout the official website of Plumed for the tutorial https://www.plumed.org/doc
