### ISSUE TITLE
there is an issue with fp when running dpgen 

### ISSUE THREAD

**Issue by 12jscvb** [deepmodeling/dpgen#1428]
### Summary

![2023-12-17](https://github.com/deepmodeling/dpgen/assets/145745956/420c12ec-9cda-43a2-a240-933aaa774148)
here are  my param.json file settings
![2023-12-17 (1)](https://github.com/deepmodeling/dpgen/assets/145745956/e1f2433e-a636-4c06-aa8b-558d7f1df48b)
the error occurs when I run dpgen,but  the parameter of fp_style has been set to cp2k, how should l solve it ? Thank you for help

### DP-GEN Version

dpgen v 0.12.0 , deepmd v2.0.4 ,numpy==1.25.0

### Platform, Python Version, etc

python3.9.18, ubuntu22.04

### Details

the error occurs when I run dpgen,but  the parameter of fp_style has been set to cp2k. May it be due to version mismatch?

**Comment by njzjz** [comment]
The command should be `dpgen run PARAM MACHINE`. See https://docs.deepmodeling.com/projects/dpgen/en/latest/overview/cli.html#run
