### ISSUE TITLE
Question:ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Zzy0317** [deepmodeling/dpgen#1457]
### Summary

An error occurs at  iter.00004 task00: ConnectionRefusedError: [Errno 111] Connection refused。

### DP-GEN Version

0.11.1

### Platform, Python Version, etc

platfrm:武汉大学超算平台；python version：3.9

### Details

Without modifying and input, an error occurs at  iter.00004 task00: ConnectionRefusedError: [Errno 111] Connection refused。
![QQ图片20240119160650](https://github.com/deepmodeling/dpgen/assets/151719652/56687f02-122a-47bc-a589-60d2eaf049b0)
Attach my machine.json file
[machine.json](https://github.com/deepmodeling/dpgen/files/13986228/machine.json)

**Comment by njzjz** [comment]
`hostname` expects a hostname instead of a host.
See https://superuser.com/questions/503687/whats-the-difference-between-host-and-hostname-in-ssh-config
