### ISSUE TITLE
[Feature Request] Support different backends for DeePMD-kit

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/dpgen#1462]
### Summary

Support PyTorch backend for DeePMD-kit.

### Detailed Description

Although I have submitted https://github.com/deepmodeling/deepmd-kit/pull/3191 to make most of the things the same, the suffixes of the model and checkpoint files are different by design. These suffixes are hardcoded in the code.

https://github.com/deepmodeling/dpgen/blob/73926506688ac8f8939f065056e83ac51fb2601f/dpgen/generator/run.py#L804-L812
https://github.com/deepmodeling/dpgen/blob/73926506688ac8f8939f065056e83ac51fb2601f/dpgen/generator/run.py#L884-L889
https://github.com/deepmodeling/dpgen/blob/73926506688ac8f8939f065056e83ac51fb2601f/dpgen/generator/run.py#L1938
https://github.com/deepmodeling/dpgen/blob/73926506688ac8f8939f065056e83ac51fb2601f/dpgen/simplify/simplify.py#L188

Besides, glob doesn't work for `backward_files` - in dpdispatcher, some contexts like Bohrium don't support it.
So, may we consider adding a parameter to switch?

**Comment by njzjz** [comment]
This is blocked by deepmodeling/deepmd-kit#3475.

**Comment by thangckt** [comment]
hi @njzjz 

Did you solved this problem?
I made some changes to have option for choosing between backends TF and PT, in [this file](https://github.com/thangckt/dpgen/commit/28b8a49d2246070aedc563a1a3109ff42134a9b8)

If you find it helpful, I will make a PR. Otherwise, just omit
