### ISSUE TITLE
[BUG] 请问dogen 训练的时候，个traing process, 误将其中一个终止后，如何重新生成graph.002.pb？

### ISSUE THREAD

**Issue by 3218923350** [deepmodeling/dpgen#1473]
### Bug summary

现在01.model_devi文件夹下没有graph.002.pb。误删掉的那个训练任务ID是11362154，将record.dpgen文件改回前一个session也不可以。现在这个结果就是重新提交续算的，它的00.train文件夹下只训练了000，001，003，没有002。也就是graph.002.pb没有被训练，我觉得是因为之前误终止掉这个任务的关系，但是找了一些办法都不起作用

### DP-GEN Version

*

### Input Files, Running Commands, Error Log, etc.

您好，请问dogen 训练的时候，个traing process, 误将其中一个终止后，如何重新生成graph.002.pb？现在01.model_devi文件夹下没有graph.002.pb。误删掉的那个训练任务ID是11362154，将record.dpgen文件改回前一个session也不可以。现在这个结果就是重新提交续算的，它的00.train文件夹下只训练了000，001，003，没有002。也就是graph.002.pb没有被训练，我觉得是因为之前误终止掉这个任务的关系，但是找了一些办法都不起作用

### Steps to Reproduce

您好，请问dogen 训练的时候，个traing process, 误将其中一个终止后，如何重新生成graph.002.pb？现在01.model_devi文件夹下没有graph.002.pb。误删掉的那个训练任务ID是11362154，将record.dpgen文件改回前一个session也不可以。现在这个结果就是重新提交续算的，它的00.train文件夹下只训练了000，001，003，没有002。也就是graph.002.pb没有被训练，我觉得是因为之前误终止掉这个任务的关系，但是找了一些办法都不起作用

**Comment by njzjz** [comment]
We don't accept non-English issues. Please use English for discussion.
