### ISSUE TITLE
是否能加入任务节点监测

### ISSUE THREAD

**Issue by NKJunhongLi** [deepmodeling/dpgen#1496]
### Summary

希望能够在程序中加入对任务节点的监测，避免程序被提交到坏节点后空跑的问题。

### Detailed Description

昨日提交了一个dpgen程序到本地集群运算，但今天回来看发现有一个任务的运算时间一直是0，此时距离任务提交已经超过14小时。

更换节点，重新提交任务之后，程序顺利跑通。推测是因为昨天提交任务时分配的节点是坏的。

如果可以，希望dpgen加入监测节点或类似的功能：如果超过多少多少小时无反馈，就终结任务，并更换节点重新提交运行。这样可以避免任务被分配到坏节点后，长时间空跑不执行的情况。

**Comment by njzjz** [comment]
We don't accept non-English issues. Please use English for discussion.
