### ISSUE TITLE
hard-coded model name in gromacs model devi calculation

### ISSUE THREAD

**Issue by thangckt** [deepmodeling/dpgen#1542]
### Summary

I am working on an other PR, and found this line  in file `dpgen/generator/run.py` may be a problem (not related to my problem)
```py
2005:             command += f"&& dp model-devi -m ../graph.000.pb ../graph.001.pb ../graph.002.pb ../graph.003.pb -s traj_deepmd -o model_devi.out -f {trj_freq}"
```
It's seemly that only first four models are used regardless the setting "numb_models"
Please check it or just omit this if I wrong.

### DP-GEN Version

0.12.1

### Details

.

**Comment by wanghan-iapcm** [comment]
you are right, it is not correct to hard-code the model names.
