### ISSUE TITLE
想问一下有关dpgen simplify的问题

### ISSUE THREAD

**Issue by xwxwshi** [deepmodeling/dpgen#1551]
### Summary

有关dpgen simplify的问题，请问运行完了以后，他是会把重复的数据删除还是会输出一个新的数据库

### DP-GEN Version

0.12.0

### Platform, Python Version, etc

Bohrium

### Details

想问问运行以后，我简化的数据，是会删除重复数据还是给我重新分类了

**Comment by robinzyb** [comment]
we only accept english issues
