### ISSUE TITLE
Error message needed to be revised

### ISSUE THREAD

**Issue by thangckt** [deepmodeling/dpgen#1553]
### Summary

Dear Developers, 

I think this line in file `dpgen/data/gen.py` should be revised for better description
```
680:         raise RuntimeError( "not file %s, vasp relaxation should be run before scale poscar" )
```
There is no value for string format.

### DP-GEN Version

devel

### Details

.

**Comment by njzjz** [comment]
git blame: 8a78d09658243b8d01dab651651066427868d47b

FYI @wanghan-iapcm
