### ISSUE TITLE
How to use the DNN model obtained from DPGEN in LAMMPS?

### ISSUE THREAD

**Issue by Duanmu37** [deepmodeling/dpgen#1565]
### Summary

I encountered issues while using the DNN model for LAMMPS simulations. I would greatly appreciate your assistance in resolving them.

### DP-GEN Version

0.12.1

### Details

I trained four DNN models using DPGEN. According to the guidelines, the differences between them are only the random initialization seeds. Should I use all four models simultaneously when running LAMMPS simulations with the DNN model?
(i.e., 
**pair_style deepmd graph.000.pb graph.001.pb graph.002.pb graph.003.pb
pair_coeff * ***
)

I wrote my LAMMPS input file this way, but I encountered errors when executing the task. Here is the last part of the error message I extracted:

  _>>> Info of model(s):
  using   4 model(s): graph.000.pb graph.001.pb graph.002.pb graph.003.pb 
  rcut in model:      6
  ntypes in model:    2
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
......
......

libgomp: Thread creation failed: Resource temporarily unavailable

libgomp: Thread creation failed: Resource temporarily unavailable
......
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[19122,1],36]
  Exit code:    1
--------------------------------------------------------------------------_
I will also upload the complete out file. I would greatly appreciate your assistance. If you need any other information from me, please let me know. Thank you again.
[slurm-283404.txt](https://github.com/user-attachments/files/15534626/slurm-283404.txt)

**Comment by njzjz** [comment]
See https://github.com/deepmodeling/deepmd-kit/issues/1757

**Comment by Duanmu37** [comment]
Hello, first of all, thank you for your response. However, my main issue is not the thread creation failure, but rather the following: 

NVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
......
......
I am not sure if there is an issue with my trained model or with my settings. I copied the graph.00*.pb files from the iter0000*/00.train folder to the new working directory for LAMMPS simulations. Is this the correct procedure?
I hope to receive your response soon. Thank you again.

**Comment by chb-deep** [comment]
Pls have you fixed this issue, I have the same issue

**Comment by njzjz** [comment]
> INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph

This message is **expected**.

> Pls have you fixed this issue, I have the same issue

Could you explain what your issue is?

**Comment by chb-deep** [comment]
> > INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
> 
> This message is **expected**.
> 
> > Pls have you fixed this issue, I have the same issue
> 
> Could you explain what your issue is?
 surpport model ver.:1.1
  build variant:      cpu
  build with tf inc:  /public1/home/scfa8472/anaconda3/envs/deepmd/include;/public1/home/scfa8472/anaconda3/envs/deepmd/include
  build with tf lib:  /public1/home/scfa8472/anaconda3/envs/deepmd/lib/libtensorflow_cc.so
  set tf intra_op_parallelism_threads: 8
  set tf inter_op_parallelism_threads: 6
  >>> Info of lammps module:
  use deepmd-kit at:  /public1/home/scfa8472/anaconda3/envs/deepmdINVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch
_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
INVALID_ARGUMENT: Tensor spin_attr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the GraphINVALID_ARGUMENT: Tensor spin_a
ttr/ntypes_spin:0, specified in either feed_devices or fetch_devices was not found in the Graph
