### ISSUE TITLE
The single-point energy calculations failed during the iteration process.

### ISSUE THREAD

**Issue by duousername1** [deepmodeling/dpgen#1623]
### Summary

Hello, I have a question. During iteration for single-point energy calculations, some calculations are successful, while others fail. The reason for the failures is that the number of atom types in the INPUT does not match the number of atom types in the structure file. This might be because I set `ntype=6` in the `param.json` file, but in the dataset for single-point energy calculation, there is a structure like NH4ClO4 where `ntype=4`, so they don't match. How do people usually handle this kind of situation? The reason I set `ntype=6` is that some of my structures consist of 6 atom types.

### DP-GEN Version

0.12.0

### Platform, Python Version, etc

"api_version": "1.0",
  "deepmd_version": "2.2.8",
bohrium paltform

### Details

![WechatIMG96](https://github.com/user-attachments/assets/e98e1847-2ce1-4c50-844c-d271ef7cefb3)

**Comment by njzjz** [comment]
It seems that this error message has been removed in https://github.com/deepmodeling/abacus-develop/pull/4548. ping @pxlxingliang for confirmation.

**Comment by pxlxingliang** [comment]
hi @duousername1, `ntype` is unnecessary now, please remove this parameter in your setting.

**Comment by duousername1** [comment]
> It seems that this error message has been removed in [deepmodeling/abacus-develop#4548](https://github.com/deepmodeling/abacus-develop/pull/4548). ping @pxlxingliang for confirmation.
Thank you, I will try following the method you provided.

**Comment by duousername1** [comment]
> hi @duousername1, `ntype` is unnecessary now, please remove this parameter in your setting.
Thank you, I will try following the method you provided.

**Comment by duousername1** [comment]
> hi @duousername1, `ntype` is unnecessary now, please remove this parameter in your setting.

Here's the translation:

hi 
The suggestion provided above helps address the issue with the number of atomic species, but I have encountered another problem. While performing single-point energy calculations during the iterations, I received the following error: "NLOCAL < NBANDS. CHECK IN FILE: OUT.ABACUS/warning.log." Therefore, I would like to set different parameters (such as the value of `nbands`) separately for different structures. Could you please advise on how to configure this in the `param.json` file?  thanks

**Comment by pxlxingliang** [comment]
Hi @duousername1, Please do not set `nbands` in `param.json`, which is different for different systems. The error is because the parallel cores are larger than band number, you should use a small machine with less parallel cores.

**Comment by pxlxingliang** [comment]
> NLOCAL < NBANDS. CHECK IN FILE: OUT.ABACUS/warning.log.

Sorry, I have made a mistake, the NLOCAL is the basis number. Just removing the setting of `nbands` in `param.json` will be fine.

**Comment by duousername1** [comment]
> NLOCAL < NBANDS

Thank you again, it worked successfully! @pxlxingliang
