### ISSUE TITLE
file not found, model_devi.out [BUG]

### ISSUE THREAD

**Issue by qutersimu** [deepmodeling/dpgen#1699]
### Bug summary

![Image](https://github.com/user-attachments/assets/b94f57de-d3aa-4b3d-9670-b6be0ef68a8b)
![Image](https://github.com/user-attachments/assets/ee3cf84c-1916-4a0f-9d9e-3dd6aadb6375)
Hi, i use dpgen to make dp potential , while the foler in 01.model_devi folder won't have model_devi.out file , the issue like to the first fig, how can i fix this bug? can you give me some ideas, thanks

### DP-GEN Version

0.12.1

### Input Files, Running Commands, Error Log, etc.

[param1222.json](https://github.com/user-attachments/files/18246329/param1222.json)

### Steps to Reproduce

Hi, i use dpgen to make dp potential , while the foler in 01.model_devi folder won't have model_devi.out file , the issue like to the first fig, how can i fix this bug? can you give me some ideas, thanks

**Comment by bio-punk** [comment]
I have same problem
Version: 0.11.1

I run code `lmp_mpi -i input.lammps -v restart 0` ,  still not exist model_devi.out. 
Is this some problem in lammps or deepmd?

how to solve it ? 
coule you have any solution
