### ISSUE TITLE
【bug】解析INCAR时没有忽略注释

### ISSUE THREAD

**Issue by hlyang1992** [deepmodeling/dpgen#232]
如果在INCAR中存在下面内容

```
# NSW = 0

...

NSW = 10
```
下面的代码会错误的将`md_nstep`设置为0，导致后续计算出错。

https://github.com/deepmodeling/dpgen/blob/ca01bd859856a57e0915395635307383aad2164a/dpgen/data/gen.py#L654-L666

**Comment by haidi-ustc** [comment]
Thanks for reporting bug, we will fix it soon !!!

**Comment by amcadmus** [comment]
fixed please see #235
