### ISSUE TITLE
Setting up DPGEN to run in university cluster

### ISSUE THREAD

**Issue by siddarthachar** [deepmodeling/dpgen#284]
Hello,

After reading the recently published paper [https://doi.org/10.1103/PhysRevMaterials.3.023804](url) for developing more accurate potentials for surfaces and bulks, I thought of setting it up on the cluster of University of Pittsburgh. We used slurm for job submission.  However, since DPGEN seems to be built for a different cluster environment, I had to make changes to the source code to make it adjust to ours. 

Instead of submitting jobs from a personal system, I need to send it from the cluster's login node. In the initial stage of "Initial data preparation", jobs are getting submitted, however, it doesn't realize the job hasn't finished and terms it as "failed" and tried submitting it another three times. I then ended up printing few variables from the file `Dispatcher.py` to see if things are correct.

Few particularly concerning values did arrive: 
This is what I get
`{'task_chunks': [['sys-0016']], 'job_list': [{'context': <dpgen.dispatcher.LocalContext.LocalContext object at 0x7fe470804e80>, 'batch': <dpgen.dispatcher.Slurm.Slurm object at 0x7fe4807e60f0>}], 'job_record': <dpgen.dispatcher.Dispatcher.JobRecord object at 0x7fe470ba0860>, 'command': ['srun --mpi=pmi2 vasp_std'], 'resources': {'task_per_node': 28, 'numb_node': 2, 'numb_gpu': 0, 'exclude_list': [], 'with_mpi': False, 'qos': 'short', 'source_list': [], 'module_list': ['intel/2017.1.132', 'intel-mpi/2017.1.132', 'mkl', 'fftw', 'vasp/5.4.4'], 'time_limit': '1:0:0', 'partition': 'opa', 'cluster': 'mpi', '_comment': "that's All", 'cpus_per_task': -1, 'mem_limit': -1, 'account': '', 'constraint_list': [], 'license_list': [], 'module_unload_list': [], 'envs': None, 'cuda_multi_tasks': False, 'allow_failure': False, 'cvasp': False}, 'outlog': 'log', 'errlog': 'err', 'backward_task_files': ['OUTCAR', 'CONTCAR']}`

Most of it seems right, but `job_list` and `job_record` have methods to a class. Is this correct? If not, what is it supposed to look like? 

There are a few additional question:
1. Do you think it is worth spending time to try and get it running on our cluster?
2. If yes, could one of the developers help us in setting it up here?
3. If not, what would be a better option to get it working? I think submitting jobs manually seems to be a difficult task. Would AWS be a better alternative, since I am assuming that it is independent of where you work from?

It would be great to get some help with this. Really looking forward to build reliable potentials for the system that I am working on.

Best
Sid

**Comment by njzjz** [comment]
Can you upload related files, including `dpgen.log` and directory on your cluster? I am wondering if the command on your cluster did not succeed.

**Comment by siddarthachar** [comment]
I am attaching the output from my run as well: 
[output.zip](https://github.com/deepmodeling/dpgen/files/4762528/output.zip)

I hope this helps.

**Comment by njzjz** [comment]
OK, now I know where we need to check. DP-GEN uses `squeue -o "%.18i %.2t" -j 12345` to check the job status, where `12345` is the job id. The output will be something like
```
   JOBID ST
     12345  R
```
 Then, it gets the job status by
https://github.com/deepmodeling/dpgen/blob/ea1f9227120987a32793729537ca355740d91e3d/dpgen/dispatcher/Slurm.py#L176-L188
Can you tell me what your job status is when it is running? Is it `R`?

**Comment by njzjz** [comment]
It seems that your job is running but the slurm doesn't return the `R` status.

**Comment by siddarthachar** [comment]
#### Fixes made to execute `init_bulk` 

This is really helpful, JobStatus was was always 'terminated' and then didn't return the `R` status. So I had to make some changes in `Slurm.py` to fix it to my system: 
`ret, stdin, stdout, stderr
           = self.context.block_call ("squeue --job " + job_id)` 
to
`ret, stdin, stdout, stderr
           = self.context.block_call ("squeue --job -M all " + job_id)`

This is because our supercomputer has more than one clusters [mpi, smp, gpu and htc] and so `squeue --job <job ID>` didn't work. 

The other change that I previously made in `Slurm.py` was: 
`    
    ret += 'squeue -u %s ' % mdata1['username']
`

in the function `_make_squeue()` definition 
to: 
`       ret += 'squeue -M all -u ska31'
`
Where ska31 is my username for the cluster. 

After making these changes it seems like `init_bulk` works fine for all four stages `[1,2,3,4]`. I am attaching the new folder for reference. This includes the input and output files:

[smp-my-example.zip](https://github.com/deepmodeling/dpgen/files/4767404/smp-my-example.zip)

I am assuming that it ran correctly and the initial data has been prepared to continue for DPGEN to run!

#### To execute `dpgen run`

For the next step, I found it difficult to understand how the new `PARAM` file has to be created to execute `dpgen run PARAM MACHINE`. While referring to the  examples (and `Cu_public`) on your Github folder for dpgen, there are a few questions regarding writing the `PARAM` (`param.json` in `Cu_public`) file.

1. Do I need to manually enter the path for `init_data_sys`, `sys_configs` etc? Is there an automated way of doing things? 
2. I do not really understand what the function of `init_batch_size` and `sys_batch_size` is. How do you decide these numbers? Is it advisable to set everything to "auto"? 
3. How do you decide on the number of iterations `_idx` ? Are these chosen arbitrarily? If yes, would there be a way to restart from a particular checkpoint if the model performs poorly? 

Thanks a lot for the help so far. Looking forward to hear from you soon.
