### ISSUE TITLE
About Installation

### ISSUE THREAD

**Issue by MSJavaScript** [deepmodeling/dpgen#289]
I have installed deepmd-kit by "conda install", and I create a virtual environment, deepmd-kit is installed in it. How can I install deepgen in this conda virtual environment ?

**Comment by njzjz** [comment]
Execute
```
pip install dpgen
```
after you activate this environment.

**Comment by MSJavaScript** [comment]
> Execute
> 
> ```
> pip install dpgen
> ```
> 
> after you activate this environment.

Oh, thanks. I have installed in this way.
