### ISSUE TITLE
How to deal with this error? 

### ISSUE THREAD

**Issue by funan-jhc-lee** [deepmodeling/dpgen#306]
![1](https://user-images.githubusercontent.com/68222622/90082277-e7375f80-dd41-11ea-8ec7-f3f4745da9cd.png)
![2](https://user-images.githubusercontent.com/68222622/90082283-eacae680-dd41-11ea-8965-0195e604f086.png)
When the dpgen have finished step 7 of iter000000, and all fp missions have been finished successfully，there comes with an error like this. It seems sonthing wrong with dpdata?  Thanks a lot!

**Comment by njzjz** [comment]
Maybe related to deepmodeling/dpdata#109... (CC @amcadmus @zezhong-zhang @felix5572 )

**Comment by amcadmus** [comment]
@funan-jhc-lee please report the version of dpgen and dpdata

**Comment by funan-jhc-lee** [comment]
> @funan-jhc-lee please report the version of dpgen and dpdata

deepmd-kit           1.2.0             
dpdata               0.1.17             
dpgen                0.8.0

**Comment by funan-jhc-lee** [comment]
> @funan-jhc-lee please report the version of dpgen and dpdata

Sorry，I‘m quite not good with github. Should I edit the System.py like what it was changed in this pull request? I have edited System.py, but it seems not working. Thanks a lot ！

**Comment by funan-jhc-lee** [comment]
> Maybe related to [deepmodeling/dpdata#109](https://github.com/deepmodeling/dpdata/pull/109)... (CC @amcadmus @zezhong-zhang @felix5572 )

Sorry，I‘m quite not good with github. Should I edit the System.py like what it was changed in this pull request? I have edited System.py, but it seems not working. Thanks a lot !

**Comment by njzjz** [comment]
> > Maybe related to [deepmodeling/dpdata#109](https://github.com/deepmodeling/dpdata/pull/109)... (CC @amcadmus @zezhong-zhang @felix5572 )
> 
> Sorry，I‘m quite not good with github. Should I edit the System.py like what it was changed in this pull request? I have edited System.py, but it seems not working. Thanks a lot !

How do you edit it? If you edit on the source code, you need to use `pip install .` (`.` is the directory of `setup.py`) to install it.

**Comment by funan-jhc-lee** [comment]
> > > Maybe related to [deepmodeling/dpdata#109](https://github.com/deepmodeling/dpdata/pull/109)... (CC @amcadmus @zezhong-zhang @felix5572 )
> > 
> > 
> > Sorry，I‘m quite not good with github. Should I edit the System.py like what it was changed in this pull request? I have edited System.py, but it seems not working. Thanks a lot !
> 
> How do you edit it? If you edit on the source code, you need to use `pip install .` (`.` is the directory of `setup.py`) to install it.

I edited the file in the path appearing in the error message that I uploaded :/public/home/liyue/deepmd-kit/lib/python3.7/site-packages/dpdata/system.py. Should I install dpdata again? Thanks a lot for your reply！

**Comment by njzjz** [comment]
Please upgrade the dpdata to the newest version `pip install -U dpdata`. If the error still appears, please upload the OUTCAR here. Thanks!

**Comment by njzjz** [comment]
> > > > Maybe related to [deepmodeling/dpdata#109](https://github.com/deepmodeling/dpdata/pull/109)... (CC @amcadmus @zezhong-zhang @felix5572 )
> > > 
> > > 
> > > Sorry，I‘m quite not good with github. Should I edit the System.py like what it was changed in this pull request? I have edited System.py, but it seems not working. Thanks a lot !
> > 
> > 
> > How do you edit it? If you edit on the source code, you need to use `pip install .` (`.` is the directory of `setup.py`) to install it.
> 
> I edited the file in the path appearing in the error message that I uploaded :/public/home/liyue/deepmd-kit/lib/python3.7/site-packages/dpdata/system.py. Should I install dpdata again?
> I tried to use dpdata to read in results(OUTCAR) of all fp tasks, and found there is some system contaning no frame "MultiSystems (1 systems containing 0 frames)" . Is this where the error comes from? Thanks a lot for your reply！

Please upgrade the dpdata to the newest version `pip install -U dpdata`. If the error still appears, please upload the OUTCAR here. Thanks!

**Comment by funan-jhc-lee** [comment]
> > > > > Maybe related to [deepmodeling/dpdata#109](https://github.com/deepmodeling/dpdata/pull/109)... (CC @amcadmus @zezhong-zhang @felix5572 )
> > > > 
> > > > 
> > > > Sorry，I‘m quite not good with github. Should I edit the System.py like what it was changed in this pull request? I have edited System.py, but it seems not working. Thanks a lot !
> > > 
> > > 
> > > How do you edit it? If you edit on the source code, you need to use `pip install .` (`.` is the directory of `setup.py`) to install it.
> > 
> > 
> > I edited the file in the path appearing in the error message that I uploaded :/public/home/liyue/deepmd-kit/lib/python3.7/site-packages/dpdata/system.py. Should I install dpdata again?
> > I tried to use dpdata to read in results(OUTCAR) of all fp tasks, and found there is some system contaning no frame "MultiSystems (1 systems containing 0 frames)" . Is this where the error comes from? Thanks a lot for your reply！
> 
> Please upgrade the dpdata to the newest version `pip install -U dpdata`. If the error still appears, please upload the OUTCAR here. Thanks!
I upgraded the dpdata to 0.1.19 but there comes a new error, I am tring using
[task.000.000006.zip](https://github.com/deepmodeling/dpgen/files/5072071/task.000.000006.zip)
[task.000.000101.zip](https://github.com/deepmodeling/dpgen/files/5072074/task.000.000101.zip)

 dpgen to get a deep-potential for PtNi alloy system. Here are two examples of tasks in 02.fp. Thanks a lot!

**Comment by njzjz** [comment]
@funan-jhc-lee So, I found one is Pt4Ni12 and another one is Pt11Ni5... Is it expected as you set, or a bug of dpgen?

**Comment by funan-jhc-lee** [comment]
Thanks a lot! I contained diffrent systems into one element when setting "sys_configs" ,  and this caused this error.
