### ISSUE TITLE
Compatibility with Quantum Espresso

### ISSUE THREAD

**Issue by mkphuthi** [deepmodeling/dpgen#319]
Hi. Would compatibility with QE (or GPAW) be something you might look at or would you consider it difficult to include in the current implementation? After skimming the code it seems dpgen is very dependent on VASP.

**Comment by mkphuthi** [comment]
I just saw the examples. My mistake.

**Comment by thangckt** [comment]
Dear Developers, 

I wonder if you have plan to implement GPAW?

Thanks
