### ISSUE TITLE
Error when running model_devi_jobs

### ISSUE THREAD

**Issue by Xi-yuanWang** [deepmodeling/dpgen#322]
my param.json is 
```
"model_devi_dt": 0.002,
  "model_devi_skip": 0,
  "model_devi_f_trust_lo":  0.05,
  "model_devi_f_trust_hi":  0.15,
  "model_devi_clean_traj":  false,
  "model_devi_jobs": [
    {
      "sys_idx": [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360],
      "temps": [
        30
      ],
      "press": [
        1
      ],
      "trj_freq": 5,
      "nsteps":   500,
      "ensemble": "npt",
      "_idx":     "00"
    }
  ],
```
During Iter.0000, four jobs was submitted and only one job failed. And the track is.

ERROR: Attempting to rescale a 0.0 temperature (../velocity.cpp:735)
Last command: velocity        all create ${TEMP} 197386

**Comment by AnguseZhang** [comment]
Seems like LAMMPS's bug in its early version. See https://sourceforge.net/p/lammps/mailman/message/33848517/
This is probably solved in later versions. I will close this issue, and if there's still some problem you can reopen this issue or create a new issue. Thanks for your report.
