### ISSUE TITLE
 find too many unsuccessfully terminated jobs

### ISSUE THREAD

**Issue by mayankaditya** [deepmodeling/dpgen#324]
Hi, I am getting the following error in the second iteration:

 **find too many unsuccessfully terminated jobs**

How to go ahead?

Thanks,
Mayank

**Comment by njzjz** [comment]
set `ratio_failed` in your json file to 1, e.g. 
```json
"ratio_failed": 1,
```

**Comment by mayankaditya** [comment]
There are two json files, and each of them has many sections where should I put this line.

Thanks,
Mayank

**Comment by njzjz** [comment]
`PARAM` file.
