### ISSUE TITLE
Dpgen code is not compatible with new version pymatgen

### ISSUE THREAD

**Issue by Cirillasz** [deepmodeling/dpgen#357]
https://pymatgen.org/index.html#major-announcement-v2022-0
'A backwards incompatible change has been introduced in v2022.0.*.'
 'If your existing code uses from pymatgen import <something>, you will need to make modifications.'

I have met several problems when installing dpgen due to new version pymatgen.

**Comment by AnguseZhang** [comment]
Pymatgen just did an incompatible update. We must first make sure that this update is stable, and then support their update. Before that, I suggest that you use the old version of Pymatgen , such as 2020.

**Comment by amcadmus** [comment]
solved by #356 and #358
