### ISSUE TITLE
Ask for help: UserWarning: The batch sizes are not enough 

### ISSUE THREAD

**Issue by zcb-code** [deepmodeling/dpgen#365]
**Summary**
My question is how to use several files with different atoms as input files("init_data_sys"), to train the model? The second is, how to use different structures with different atoms as initial structures ("sys_configs")? The following are the details:

**Summary**

I use many structures. I use dpgen to run the iteration. If I use one prepared files, it went well with each structure. However, if added two structure files as   "Li14" ，"Li8"，(these files were created with dpdata from OUTCARs), I will get error:

~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpgen/generator/run.py:242: UserWarning: The batch sizes are not enough. Assume auto for those not spefified.
  warnings.warn("The batch sizes are not enough. Assume auto for those not spefified.")
Traceback (most recent call last):
  File "~/scratch/Anaconda3/envs/deepc/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpgen/main.py", line 182, in main
    args.func(args)
  File "~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpgen/generator/run.py", line 2340, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpgen/generator/run.py", line 2299, in run_iter
    make_train (ii, jdata, mdata)
  File "~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpgen/generator/run.py", line 252, in make_train
    assert (len(init_data_sys_) <= len(init_batch_size_))
AssertionError
____________________________________________________________________________________________________________________
I change the "init_batch_size" to 100, it did not help. how to add all files to train the model?

**Detailed Description**

<!
{
  "type_map": ["Li"],
  "mass_map": [7.0],

  "_comment": "initial data set for Training and the number of frames in each training  batch",
  "init_data_prefix": "~/scratch/deep/deecada/",
  "init_data_sys":   [
    "Li14"   
  ],
  "init_batch_size": [
2
],

  "_comment": "configurations for starting MD in Exploration and batch sizes when traning snapshots derived from these configs (if they were selected)",
  "sys_configs_prefix": "~/scratch/deep/poscars/",
  "sys_configs":    [
    [
      "0000[0-9]/POSCAR"
    ],
    [
      "0001[0-9]/POSCAR"
    ]
  ],
  "sys_batch_size": [
   4,
   4
  ],

  "_comment": " 00.train ",
  "numb_models":            4,

  "default_training_param": {
    "model": {
      "type_map":           ["Li"],
      "descriptor": {
        "type":             "se_a",
        "sel":              [64],
        "rcut_smth":        0.5,
        "rcut":             5.0,
        "neuron":           [10,20,40],
        "resnet_dt":        false,
        "axis_neuron":      12,
        "seed":             0
      },
      "fitting_net": {
        "neuron":           [120,120,120],
        "resnet_dt":        true,
        "coord_norm":       true,
        "type_fitting_net": false,
        "seed": 0
      }
    },
      "loss": {
        "start_pref_e":      0.02,
        "limit_pref_e":      1,
        "start_pref_f":      1000,
        "limit_pref_f":      1,
        "start_pref_v":      0,
        "limit_pref_v":      0
    },
      "learning_rate": {
        "type":              "exp",
        "start_lr":          0.001,
        "decay_steps":       1000,
        "decay_rate":        0.95
    },
      "training": {
        "systems":           [],
        "set_prefix":        "set",
        "stop_batch":        200000,
        "batch_size":        1,
        "seed": 1,
        "_comment":          "frequencies counted in batch",
        "disp_file":         "lcurve.out",
        "disp_freq":         1000,
        "numb_test":         4,
        "save_freq":         1000,
        "save_ckpt":         "model.ckpt",
        "load_ckpt":         "model.ckpt",
        "disp_training":     true,
        "time_training":     true,
        "profiling":         false,
        "profiling_file":    "timeline.json"
    }
  },

  "_comment": " 01.model_devi ",
  "model_devi_dt": 0.002,
  "model_devi_skip": 0,
  "model_devi_f_trust_lo":  0.05,
  "model_devi_f_trust_hi":  0.15,
  "model_devi_clean_traj":  false,
  "model_devi_jobs": [
    {
      "sys_idx": [
        0
      ],
      "temps": [
        50
      ],
      "press": [
        1
      ],
      "trj_freq": 10,
      "nsteps":   10000,
      "ensemble": "nvt",
      "_idx":     "00"
    },
    {
      "sys_idx": [
        1
      ],
      "temps": [
        50
      ],
      "press": [
        1
      ],
      "trj_freq": 10,
      "nsteps":   30000,
      "ensemble": "nvt",
      "_idx":     "01"
    }
  ],

  "_comment": " 02.fp ",
  "fp_style":             "vasp",
  "shuffle_poscar":       false,
  "fp_task_max":          40,
  "fp_task_min":          8,
  "fp_pp_path":           "./",
  "fp_pp_files":          [ "POTCAR_Li"],
  "fp_incar":             "INCAR_Li"

-->
If the  structures atoms are different in :
"sys_configs_prefix": "~/scratch/deep/poscars/",
  "sys_configs":    [
    [
      "0000[0-9]/POSCAR"
    ],
    [
      "0001[0-9]/POSCAR"
    ]
______________________________________________________________
I will get an error ：
INFO:dpgen:-------------------------iter.000001 task 08--------------------------
INFO:dpgen:failed tasks:      0 in     40    0.00 %
Traceback (most recent call last):
  File "~/scratch/Anaconda3/envs/deepc/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpgen/main.py", line 182, in main
    args.func(args)
  File "~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpgen/generator/run.py", line 2340, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpgen/generator/run.py", line 2329, in run_iter
    post_fp (ii, jdata)
  File "~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpgen/generator/run.py", line 2197, in post_fp
    post_fp_vasp(iter_index, jdata)
  File "~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpgen/generator/run.py", line 1928, in post_fp_vasp
    all_sys.append(_sys)
  File "~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpdata/system.py", line 1316, in append
    if not System.append(self, system):
  File "~/scratch/Anaconda3/envs/deepc/lib/python3.6/site-packages/dpdata/system.py", line 336, in append
    raise RuntimeError('systems with inconsistent formula could not be append: %s v.s. %s' % (self.uniq_formula, system.uniq_formula))
RuntimeError: systems with inconsistent formula could not be append: Li10 v.s. Li3
____________________________________________________________________________________________________________________________
Because the atoms in POSCARs in "sys_configs_prefix" is different, how to write that accurate?

**Comment by AnguseZhang** [comment]
These are  two  different problems. 
1.  "The batch sizes are not enough": the length of "init_batch_size" should be exactly the same as "init_data_sys", and it's true for "sys_batch_size".  As for the meanings of each parameters, you should refer to the manual for descriptions. If you're still not clear about how to set "init_batch_size" and "sys_batch_size", then just delete these two keys. DP-GEN will automatically determine a proper value for you.
2."RuntimeError: systems with inconsistent formula could not be append: Li10 v.s. Li3" : In each system,  the formula (both atom types and atom numbers ) should be the same.

**Comment by njzjz** [comment]
@AnguseZhang Do you think it is a good idea to support `MultiSystems` for default? Users may want systems with different formulas in a same system.
