### ISSUE TITLE
Issue with PLUMED in DPGEN procedure

### ISSUE THREAD

**Issue by ZhanPengOu** [deepmodeling/dpgen#369]
Hello

I'm trying to run dpgen with plumed in the structure of Aluminum clusters,but something went wrong in the model_devi part,it seem that the trajectory files did not generated.Error messages are following

DPGEN Version : 0.8.1

`Traceback (most recent call last):
  File "/home/zpou/anaconda3/envs/dpgen/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/home/zpou/anaconda3/envs/dpgen/lib/python3.8/site-packages/dpgen/main.py", line 182, in main
    args.func(args)
  File "/home/zpou/anaconda3/envs/dpgen/lib/python3.8/site-packages/dpgen/generator/run.py", line 2340, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/home/zpou/anaconda3/envs/dpgen/lib/python3.8/site-packages/dpgen/generator/run.py", line 2315, in run_iter
    run_model_devi (ii, jdata, mdata)
  File "/home/zpou/anaconda3/envs/dpgen/lib/python3.8/site-packages/dpgen/generator/run.py", line 999, in run_model_devi
    dispatcher.run_jobs(mdata['model_devi_resources'],
  File "/home/zpou/anaconda3/envs/dpgen/lib/python3.8/site-packages/dpgen/dispatcher/Dispatcher.py", line 91, in run_jobs
    while not self.all_finished(job_handler, mark_failure) :
  File "/home/zpou/anaconda3/envs/dpgen/lib/python3.8/site-packages/dpgen/dispatcher/Dispatcher.py", line 226, in all_finished
    rjob['context'].download(task_chunks[idx], backward_task_files)
  File "/home/zpou/anaconda3/envs/dpgen/lib/python3.8/site-packages/dpgen/dispatcher/LocalContext.py", line 114, in download
    raise RuntimeError('do not find download file ' + rfile)
RuntimeError: do not find download file /home/zpou/dpgen_work/aa51e6f4-efb8-410a-95f4-7162524155ce/task.000.000001/dump.0.xyz

`

[files.zip](https://github.com/deepmodeling/dpgen/files/6308374/files.zip)

**Comment by AnguseZhang** [comment]
1. Enter directory /home/zpou/dpgen_work/aa51e6f4-efb8-410a-95f4-7162524155ce/task.000.000001/, and you will find running script xxx.sub and log file xxx.log. Check whether your jobs have finished successfully.

2. You're suggested use latest version of DP-GEN (currently 0.9.2).

**Comment by ZhanPengOu** [comment]
[dpgen_work file.zip](https://github.com/deepmodeling/dpgen/files/6308496/dpgen_work.file.zip)

**Comment by ZhanPengOu** [comment]
The dpgen_work file is uploaded, no files named xxx.sub or xxx.log in the task.000.000001/. Anyway,there are no "dump.0.xzy" file in the other folder like"task.000.000004" though i found that it should generate file named 'dump.0.xzy' if plumed work.
[dpgen_work file.zip](https://github.com/deepmodeling/dpgen/files/6308498/dpgen_work.file.zip)

**Comment by tuoping** [comment]
You have put this line in input.lammps :"dump            dpgen_dump all custom 10 traj/*.lammpstrj id type x y z"
Because of this setting: "traj/*.lammpstrj", you renamed the dump files and put them all in a subdirectory "traj", and dpgen can't find them. Just delete it will solve your problem.

**Comment by tuoping** [comment]
Issue solved. Ready to close. @amcadmus

**Comment by tuoping** [comment]
File with name "dump.0.xyz" is required explicitly as backward_file in the coding. So to have the code through, you have to add a line: "DUMPATOMS FILE=dump.0.xyz ATOMS=@matoms" in input.plumed, where @matoms means all the physical atoms present in the MD engine.

**Comment by tuoping** [comment]
I suspect this might not be a proper specification at all. And the HILLS and COLVAR files are not stored after model_deviation. I guess this need to be modified as well.

**Comment by tuoping** [comment]
And I suggest not to run with plumed at outset. Go with oldy-goody NPT-MD for a while, until max_f_devi is low enough, then start with plumed. This way it's likely that your training will converge faster.

**Comment by AnguseZhang** [comment]
This issue is solved. I've closed this issue. If there is still any problem, you can reopen this issue or create a new issue.

**Comment by njzjz** [comment]
Note: fixed by #498.
