### ISSUE TITLE
Issue with dpgen run

### ISSUE THREAD

**Issue by hongmoxian** [deepmodeling/dpgen#372]
I have the error "~/.conda/envs/deepmd-1.2.2/bin/dp_train: No such file or directory" in the  train.log file when I use the command "dpgen run *.json" and  I can`t  find the ralated setting in the machine.json file . Only  the command" dp" exist in this path.
 Thanks!

**Comment by tuoping** [comment]
![Uploading 捕获.PNG…]()

**Comment by tuoping** [comment]
![捕获](https://user-images.githubusercontent.com/80671886/116645832-3b09d780-a9a9-11eb-89f5-e431a6778160.PNG)

**Comment by DingChangjie** [comment]
I also encountered this problem when using dpgen with deepmd-kit 1.3.3. However this issue occurs exclusively on HPC machines (Sugon, 中科曙光计算云). With exactly same installation, things work fine on a single local compute node...

**Comment by AnguseZhang** [comment]
You use old version of machine.json, which is incompatible. 
Delete "deepmd_path" in machine.json.
You can refer to https://github.com/AnguseZhang/dpgen/blob/devel/examples/machine/DeePMD-kit-1.x/machine-slurm-qe.json and see the explanations.

**Comment by AnguseZhang** [comment]
You should also use a compatible param.json. Before you see an example, you should check its version. 
For DeePMD-kit >=1.0 , you can refer to https://github.com/AnguseZhang/dpgen/blob/devel/examples/run/dp1.x-lammps-vasp/CH4/param_CH4_deepmd-kit-1.1.0.json
