### ISSUE TITLE
[BUG] SSH session not active

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/dpgen#379]
![image](https://user-images.githubusercontent.com/9496702/115981699-be6b9900-a563-11eb-8291-4cb4d711bd38.png)

Related: https://github.com/paramiko/paramiko/issues?q=SSH+session+not+active

If paramiko cannot fix this issue, we may need to add `try...except` to retry the connection.

**Comment by amcadmus** [comment]
Could you please contribute a solution? @njzjz

**Comment by amcadmus** [comment]
@felix5572 Please notice this bug
