### ISSUE TITLE
[Feature Request] Check compatible version with DeePMD-kit 

### ISSUE THREAD

**Issue by AnguseZhang** [deepmodeling/dpgen#386]
**Summary**
We should figure out which version of DeePMD-kit will be supported in DP-GEN.

**Detailed Description**

Problems occur when users specify a wrong version of "param.json" or "machine.json", such as "dp_train" and "dp train" and "input.json" of DeePMD-kit.  

I propose to deprecate the support for DeePMD-kit < 1.0, and only provide examples for DeePMD-kit >= 1.0.

Meanwhile, we're going to release DeePMD-kit 2.0. I'm wondering if there is a big difference of user interface?

**Comment by AnguseZhang** [comment]
@amcadmus @njzjz  What's your opinion?

**Comment by njzjz** [comment]
>  only provide examples for DeePMD-kit >= 1.0.
I agree. 
> if there is a big difference of user interface?
The training parameters have [breaking changes](https://deepmd.readthedocs.io/en/latest/train-input.html). Also, it is valuable to add `dp compress` into the workflow.

**Comment by njzjz** [comment]
Note: Besides `systems`, `auto_prob_style` is also required to update.

**Comment by njzjz** [comment]
Close as resolved.
