### ISSUE TITLE
error happens when doing task 8

### ISSUE THREAD

**Issue by 343333333** [deepmodeling/dpgen#399]
when i finish the run_fp , running to post_fp the error happens like this :
i check the file ,seems everythiing goes well ,and i check the OUTCAR  in each fp file they are all finished well.
So i choose to run again changing the `group_size=20` in the fp section ,which used to 10. the problem disappear ,weird.
so ,would you tell me what cause that error and how i can avoid it the next time, thx.
btw ,what the meaning of ' unsuccessfully terminated jobs' , becasue it seems each fp calculation has been done in the run _fp
```
INFO:dpgen:-------------------------iter.000000 task 06--------------------------
INFO:dpgen:system 000 candidate :     14 in     62  22.58 %
INFO:dpgen:system 000 failed    :     10 in     62  16.13 %
INFO:dpgen:system 000 accurate  :     38 in     62  61.29 %
INFO:dpgen:system 000 accurate_ratio:   0.6129    thresholds: 1.0000 and 1.0000   eff. task min and max   -1   20   number of fp tasks:     14
INFO:dpgen:-------------------------iter.000000 task 07--------------------------
INFO:dpgen:new submission of d43b40d3-1b70-49e2-b9e9-b99fb9fbb89c for chunk 5776fd87d63bd9cbe3b31a38c5c7f85b8fcbf0b6
INFO:dpgen:new submission of 96a0626f-0f78-468a-a567-2c8faed8f62c for chunk f6b6fada4486171b74f408bb3db7d1c10cbf9f18
INFO:dpgen:job 96a0626f-0f78-468a-a567-2c8faed8f62c finished
INFO:dpgen:job d43b40d3-1b70-49e2-b9e9-b99fb9fbb89c finished
INFO:dpgen:-------------------------iter.000000 task 08--------------------------
INFO:dpgen:failed tasks:      0 in     14    0.00 % 
INFO:dpgen:failed frame:      3 in     14   21.43 % 
Traceback (most recent call last):
  File "/home/ben/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/home/ben/.local/lib/python3.8/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/home/ben/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 2410, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/home/ben/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 2399, in run_iter
    post_fp (ii, jdata)
  File "/home/ben/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 2267, in post_fp
    post_fp_vasp(iter_index, jdata)
  File "/home/ben/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 2033, in post_fp_vasp
    raise RuntimeError("find too many unsuccessfully terminated jobs")
RuntimeError: find too many unsuccessfully terminated jobs
```

**Comment by AnguseZhang** [comment]
By default, DP-GEN will allow up to 5% first-principle (fp) tasks fail to converge.If a fp-job doesn't converge or breaks up due to certain reasons, dpdata won't collect this frame and DP-GEN will consider this job as "failed".  
In your case, there is 21% (3/14) failed tasks. You should figure out the reason. You can use dpdata.System to load this system's results, and locate the failed tasks.  Possible reasons include improper fp settings  (like too small steps for scf , too strict convergence criterion) or unphysical configurations. 
If you've figured out the reason, you can re-calculate this stage, or jump to next iteration, by manipulating "record.dpgen".

**Comment by njzjz** [comment]
We may add more details to the error message.

**Comment by 343333333** [comment]
> By default, DP-GEN will allow up to 5% first-principle (fp) tasks fail to converge.If a fp-job doesn't converge or breaks up due to certain reasons, dpdata won't collect this frame and DP-GEN will consider this job as "failed".
> In your case, there is 21% (3/14) failed tasks. You should figure out the reason. You can use dpdata.System to load this system's results, and locate the failed tasks. Possible reasons include improper fp settings (like too small steps for scf , too strict convergence criterion) or unphysical configurations.
> If you've figured out the reason, you can re-calculate this stage, or jump to next iteration, by manipulating "record.dpgen".

ok i'll try . thanks for you answering
