### ISSUE TITLE
Automatize virtual environment packing with pypi

### ISSUE THREAD

**Issue by tuoping** [deepmodeling/dpgen#415]
**Summary**
Enable automatic virtual environment packing with pypi.

**Details**
Straigten out the entire workflow and automatize.

**Comment by AnguseZhang** [comment]
This has been solved in 0.10.6, so I'll close this issue.

**Comment by njzjz** [comment]
It's not clear to me what this issue means. DeePMD-kit has a similar issue https://github.com/deepmodeling/deepmd-kit/issues/655.
