### ISSUE TITLE
A terrible training accuracy for Al

### ISSUE THREAD

**Issue by ZhonghengFu** [deepmodeling/dpgen#421]
Hello everyone,

I am a beginner using dpgen. I trained a model for fcc-Al. However, when I tested the model, I got a significant deviation for self-interstitial formation energy. Could anyone please provide me a few suggestions? The input files and results are listed below,

param.json in init_bulk
{
    "stages":    [1, 2, 3, 4],
    "cell_type": "fcc",
    "super_cell": [2, 2, 2],
    "elements": ["Al"],
    "from_poscar": true,
    "from_poscar_path": "POSCAR",
    "potcars": ["POTCAR"],
    "relax_incar": "INCAR.rlx",
    "md_incar": "INCAR.md",
    "scale": [1.00],
    "skip_relax": false,
    "pert_numb": 50,
    "md_nstep": 20,
    "pert_box": 0.03,
    "pert_atom": 0.01,
    "coll_ndata": 5000,
    "type_map": ["Al"],
    "_comment": "that's all"
}

param.json in run
{
    "type_map":		["Al"],
    "mass_map":		[27],

    "init_data_prefix":	"../init/",

    "init_data_sys":	[
    "POSCAR.02x02x02/02.md/sys-0032/deepmd"
			],
    "init_batch_size":	[
    1
    ],
    "sys_configs":	[
    ["/home/zhq/WORK/fzh/work/ml/test/Al-2/init/POSCAR.02x02x02/01.scale_pert/sys-0032/scale-1.000/00000[0-4]/POSCAR"],
    ["/home/zhq/WORK/fzh/work/ml/test/Al-2/init/POSCAR.02x02x02/01.scale_pert/sys-0032/scale-1.000/00000[5-9]/POSCAR"],
    ["/home/zhq/WORK/fzh/work/ml/test/Al-2/init/POSCAR.02x02x02/01.scale_pert/sys-0032/scale-1.000/00001*/POSCAR"],
    ["/home/zhq/WORK/fzh/work/ml/test/Al-2/init/POSCAR.02x02x02/01.scale_pert/sys-0032/scale-1.000/00002*/POSCAR"],
    ["/home/zhq/WORK/fzh/work/ml/test/Al-2/init/POSCAR.02x02x02/01.scale_pert/sys-0032/scale-1.000/00003*/POSCAR"],
    ["/home/zhq/WORK/fzh/work/ml/test/Al-2/init/POSCAR.02x02x02/01.scale_pert/sys-0032/scale-1.000/00004*/POSCAR"]
    ],
    "_comment":		" 00.train ",
    "numb_models":	4,
    "default_training_param" : {
	"model":{
	"_comment": " model parameters",
	"type_map":["Al"],
	"descriptor":{
	"type":			"se_a",
	"sel":			[200],
	"rcut_smth":		0.5,
	"rcut":			6.0,
	"neuron":		[25, 50, 100],
	"resnet_dt":		false,
	"axis_neuron":		12,
	"seed":			1
},
	"fitting_net":{
	"neuron":		[240, 240, 240],
	"resnet_dt":		true,
	"sedd":			1
}},
	"learning_rate":{
	"type":			"exp",
	"start_lr":		0.001,
	"decay_steps":		2000,
	"decay_rate":		0.95
},
	"loss":{
	"start_pref_e":		0.02,
	"limit_pref_e":		2,
	"start_pref_f":		1000,
	"limit_pref_f":		1,
	"start_pref_v":		0.0,
	"limit_pref_v":		0.0
},
	"training":{
	"coord_norm":		true,
	"type_fitting_net":	false,
	"_comment":             " traing controls",
	"systems":		[],
	"set_prefix":		"set",
	"stop_batch":		400000,
	"batch_size":		1,
	"seed":			0,
	"_comment":             " display and restart",
	"_comment":             " frequencies counted in batch",
	"disp_file":		"lcurve.out",
	"disp_freq":		2000,
	"numb_test":		4,
	"save_freq":		20000,
	"save_ckpt":		"model.ckpt",
	"load_ckpt":		"model.ckpt",
	"disp_training":	true,
	"time_training":	true,
	"profiling":		false,
	"profiling_file":	"timeline.json",
	"_comment":		"that's all"}
    },

    "_comment":		" 01.model_devi ",
    "_comment": "model_devi_skip: the first x of the recorded frames",
    "model_devi_dt":		0.002,
    "model_devi_skip":		0,
    "model_devi_f_trust_lo":	0.05,
    "model_devi_f_trust_hi":	0.20,
    "model_devi_e_trust_lo":	1e10,
    "model_devi_e_trust_hi":	1e10,
    "model_devi_clean_traj":	true,
    "model_devi_jobs":	
[
  {
    "_idx": 0,
    "ensemble": "npt",
    "nsteps": 300,
    "press": [
      1.0, 10, 100
    ],
    "sys_idx": [
      0
    ],
    "temps": [
      50
    ],
    "trj_freq": 10
  },
  {
    "_idx": 1,
    "ensemble": "npt",
    "nsteps": 1000,
    "press": [
      1.0, 10, 100
    ],
    "sys_idx": [
      0, 1
    ],
    "temps": [
      50
    ],
    "trj_freq": 10
  },
  {
    "_idx": 2,
    "ensemble": "npt",
    "nsteps": 1000,
    "press": [
      1.0, 10, 100
    ],
    "sys_idx": [
      2, 3
    ],
    "temps": [
      50
    ],
    "trj_freq": 10
  },
  {
    "_idx": 3,
    "ensemble": "npt",
    "nsteps": 3000,
    "press": [
      1.0, 10, 100
    ],
    "sys_idx": [
      4, 5
    ],
    "temps": [
      50
    ],
    "trj_freq": 10
  },
  {
    "_idx": 4,
    "ensemble": "npt",
    "nsteps": 3000,
    "press": [
      1.0, 10, 100
    ],
    "sys_idx": [
      4, 5
    ],
    "temps": [
      50
    ],
    "trj_freq": 10
  }
],

    "_comment":		" 02.fp ",
    "fp_style":		"vasp",
    "shuffle_poscar":	false,
    "fp_task_max":	300,
    "fp_task_min":	5,
    "fp_pp_path":	"./",
    "fp_pp_files":	["POTCAR"],
    "fp_incar":         "/home/zhq/WORK/fzh/work/ml/test/Al-2/run/INCAR",
    "_comment":		" that's all "
}

param.json in test
{
    "_comment": "models",
    "potcar_map": {
        "Al": "potential/POTCAR"
    },
    "conf_dir": "confs/Al/std-fcc",
    "key_id": "",
    "task_type": "deepmd",
    "task": "all",
    
    "vasp_params": {
        "ecut": 650,
        "ediff": 1e-6,
        "kspacing": 0.15,
        "kgamma": false,
        "npar": 1,
        "kpar": 1,
        "_comment": " that's all "
    },
    "lammps_params": {
        "model_dir": "Al_model",
        "type_map": [
            "Al"
        ],
        "model_name": false,
        "model_param_type": false
    },
    "_comment": "00.equi",
    "alloy_shift": false,
    "_comment": "01.eos",
    "vol_start": 12,
    "vol_end": 22,
    "vol_step": 0.5,
    "_comment": "02.elastic",
    "norm_deform": 2e-2,
    "shear_deform": 5e-2,
    "_comment": "03.vacancy",
    "supercell": [
        3,
        3,
        3
    ],
    "_comment": "04.interstitial",
    "insert_ele": [
        "Al"
    ],
    "reprod-opt": false,
    "_comment": "05.surface",
    "min_slab_size": 10,
    "min_vacuum_size": 11,
    "_comment": "pert xz to work around vasp bug...",
    "pert_xz": 0.01,
    "max_miller": 2,
    "static-opt": false,
    "relax_box": false,
    "_comment": "06.phonon",
    "supercell_matrix": [
        2,
        2,
        2
    ],
    "band": "0 1 0  0.5 1 0.5  0.375 0.75 0.375  0  0  0  0.5 0.5 0.5",
    "_comment": "that's all"
}

the result log
DeepModeling
------------
Version: 0.8.2.dev0+gf8d70a4.d20210204
Date:    Feb-04-2021
Path:    /home/zhq/.local/lib/python3.7/site-packages/dpgen

Dependency
------------
     numpy     1.20.3   /apps/lib/anaconda/anaconda3/e5/lib/python3.7/site-packages/numpy
    dpdata     0.1.19   /apps/lib/anaconda/anaconda3/e5/lib/python3.7/site-packages/dpdata-0.1.19-py3.7.egg/dpdata
  pymatgen 2020.10.9.01   /apps/lib/anaconda/anaconda3/e5/lib/python3.7/site-packages/pymatgen
     monty      4.0.2   /apps/lib/anaconda/anaconda3/e5/lib/python3.7/site-packages/monty
       ase     3.19.1   /apps/lib/anaconda/anaconda3/e5/lib/python3.7/site-packages/ase
  paramiko      2.7.2   /home/zhq/.local/lib/python3.7/site-packages/paramiko
 custodian   2021.1.8   /home/zhq/.local/lib/python3.7/site-packages/custodian

Reference
------------
Please cite:
Yuzhi Zhang, Haidi Wang, Weijie Chen, Jinzhe Zeng, Linfeng Zhang, Han Wang, and Weinan E,
DP-GEN: A concurrent learning platform for the generation of reliable deep learning
based potential energy models, Computer Physics Communications, 2020, 107206.
------------

Description
------------
/gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/00.equi/Al/std-fcc/deepmd
conf_dir:	 EpA(eV)  VpA(A^3)
confs/Al/std-fcc	  -3.7483   16.503 
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-12.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-12.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-13.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-13.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-14.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-14.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-15.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-15.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-16.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-16.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-17.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-17.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-18.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-18.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-19.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-19.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-20.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-20.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-21.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/01.eos/Al/std-fcc/deepmd/vol-21.50
Vpa(A^3)	EpA(eV)
11.9999981608503 -2.96662795170267
12.4999949243073 -2.97802583445048
12.9999983614591 -3.09448430830428
13.4999983961358 -3.32230518208628
13.9999959870801 -3.5283274458636
14.5000040385406 -3.6320900440121
15.0000041246356 -3.6964484536534
15.5000045857403 -3.7304097714782
16.0 -3.74457075952198
16.4999997474047 -3.74831572706045
16.9999987265498 -3.74521051825265
17.4999961808157 -3.73651305151505
18.0000045936601 -3.7231315655221
18.4999940008706 -3.7045569241317
19.0000055945374 -3.67865231543475
19.5000043580999 -3.64584828796787
19.9999947077013 -3.6097276969094
20.4999931235139 -3.57066598363155
20.9999979876931 -3.52542444079503
21.5000005488178 -3.4737049576875
gen with norm [-0.02, -0.01, 0.01, 0.02]
gen with shear [-0.05, -0.025, 0.025, 0.05]
 111.73   50.42   50.42    0.00    0.00    0.00 
  50.42  111.73   50.42    0.00    0.00    0.00 
  50.42   50.42  111.73    0.00    0.00    0.00 
   0.00    0.00    0.00   35.33    0.00    0.00 
   0.00    0.00    0.00    0.00   35.33    0.00 
   0.00    0.00    0.00    0.00    0.00   35.33 
# Bulk   Modulus BV = 70.86 GPa
# Shear  Modulus GV = 33.46 GPa
# Youngs Modulus EV = 86.74 GPa
# Poission Ratio uV = 0.30 
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/03.vacancy/Al/std-fcc/deepmd/struct-3x3x3-000
#  /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/03.vacancy/Al/std-fcc/deepmd
Structure: 	Vac_E(eV)  E(eV) equi_E(eV)
struct-3x3x3-000:   0.618  -400.452 -401.070 
task poscar:  /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/04.interstitial/Al/std-fcc/deepmd/POSCAR
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/04.interstitial/Al/std-fcc/deepmd/struct-Al-3x3x3-000
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/04.interstitial/Al/std-fcc/deepmd/struct-Al-3x3x3-001
/gpfs01/zhq_work/fzh/work/ml/test/Al-2/test/04.interstitial/Al/std-fcc/deepmd/struct-Al-3x3x3-*
Insert_ele-Struct: Inter_E(eV)  E(eV) equi_E(eV)
struct-Al-3x3x3-000:   0.720  -407.846 -408.566 
struct-Al-3x3x3-001:   0.835  -407.731 -408.566

Best regards,
Zhongheng

**Comment by AnguseZhang** [comment]
Hi, Zhongheng, 

Before thoroughly looking into your problem, I would like to ask whether you tried the potential we've generated and published.  Is it possible to use the model / data directly ? Or what's the necessity to generate another Al model from scratch?

Mg-Al-Cu paper:
https://iopscience.iop.org/article/10.1088/1674-1056/abf134/meta
The data (containing pure Al's first-principles data)   can be downloaded from http://dplibrary.deepmd.net/#/project_details?project_id=202010.002. 

Also you can refer to the protocol and settings in this paper.

**Comment by ZhonghengFu** [comment]
Hi Yuzhi,
Many thanks for your reply and kind suggestion. it is a good idea to use the model in the library as a test directly. I have tried to use it to do a test. Unbelievably, I got similar results... which are listed below. It is really confusing... Well, I use fcc-Al as a benchmark because it has been reported. I would like to understand the effect of the parameters on the accuracy and fitting speed.

DeepModeling
------------
Version: 0.8.2.dev0+gf8d70a4.d20210204
Date:    Feb-04-2021
Path:    /home/zhq/.local/lib/python3.7/site-packages/dpgen

Dependency
------------
     numpy     1.20.3   /apps/lib/anaconda/anaconda3/e5/lib/python3.7/site-packages/numpy
    dpdata     0.1.19   /apps/lib/anaconda/anaconda3/e5/lib/python3.7/site-packages/dpdata-0.1.19-py3.7.egg/dpdata
  pymatgen 2020.10.9.01   /apps/lib/anaconda/anaconda3/e5/lib/python3.7/site-packages/pymatgen
     monty      4.0.2   /apps/lib/anaconda/anaconda3/e5/lib/python3.7/site-packages/monty
       ase     3.19.1   /apps/lib/anaconda/anaconda3/e5/lib/python3.7/site-packages/ase
  paramiko      2.7.2   /home/zhq/.local/lib/python3.7/site-packages/paramiko
 custodian   2021.1.8   /home/zhq/.local/lib/python3.7/site-packages/custodian

Reference
------------
Please cite:
Yuzhi Zhang, Haidi Wang, Weijie Chen, Jinzhe Zeng, Linfeng Zhang, Han Wang, and Weinan E,
DP-GEN: A concurrent learning platform for the generation of reliable deep learning
based potential energy models, Computer Physics Communications, 2020, 107206.
------------

Description
------------
/gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/00.equi/Al/std-fcc/deepmd
conf_dir:	 EpA(eV)  VpA(A^3)
confs/Al/std-fcc	  -3.7483   16.503 
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-12.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-12.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-13.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-13.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-14.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-14.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-15.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-15.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-16.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-16.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-17.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-17.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-18.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-18.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-19.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-19.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-20.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-20.50
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-21.00
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/01.eos/Al/std-fcc/deepmd/vol-21.50
Vpa(A^3)	EpA(eV)
11.9999981608503 -2.96662795170267
12.4999949243073 -2.97802583445048
12.9999983614591 -3.09448430830428
13.4999983961358 -3.32230518208628
13.9999959870801 -3.5283274458636
14.5000040385406 -3.6320900440121
15.0000041246356 -3.6964484536534
15.5000045857403 -3.7304097714782
16.0 -3.74457075952198
16.4999997474047 -3.74831572706045
16.9999987265498 -3.74521051825265
17.4999961808157 -3.73651305151505
18.0000045936601 -3.7231315655221
18.4999940008706 -3.7045569241317
19.0000055945374 -3.67865231543475
19.5000043580999 -3.64584828796787
19.9999947077013 -3.6097276969094
20.4999931235139 -3.57066598363155
20.9999979876931 -3.52542444079503
21.5000005488178 -3.4737049576875
gen with norm [-0.02, -0.01, 0.01, 0.02]
gen with shear [-0.05, -0.025, 0.025, 0.05]
 111.73   50.42   50.42    0.00    0.00    0.00 
  50.42  111.73   50.42    0.00    0.00    0.00 
  50.42   50.42  111.73    0.00    0.00    0.00 
   0.00    0.00    0.00   35.33    0.00    0.00 
   0.00    0.00    0.00    0.00   35.33    0.00 
   0.00    0.00    0.00    0.00    0.00   35.33 
# Bulk   Modulus BV = 70.86 GPa
# Shear  Modulus GV = 33.46 GPa
# Youngs Modulus EV = 86.74 GPa
# Poission Ratio uV = 0.30 
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/03.vacancy/Al/std-fcc/deepmd/struct-3x3x3-000
#  /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/03.vacancy/Al/std-fcc/deepmd
Structure: 	Vac_E(eV)  E(eV) equi_E(eV)
struct-3x3x3-000:   0.618  -400.452 -401.070 
task poscar:  /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/04.interstitial/Al/std-fcc/deepmd/POSCAR
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/04.interstitial/Al/std-fcc/deepmd/struct-Al-3x3x3-000
# generate /gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/04.interstitial/Al/std-fcc/deepmd/struct-Al-3x3x3-001
/gpfs01/zhq_work/fzh/work/ml/test/Al-3/test/04.interstitial/Al/std-fcc/deepmd/struct-Al-3x3x3-*
Insert_ele-Struct: Inter_E(eV)  E(eV) equi_E(eV)
struct-Al-3x3x3-000:   0.720  -407.846 -408.566 
struct-Al-3x3x3-001:   0.835  -407.731 -408.566

Best regards,
Zhongheng

**Comment by AnguseZhang** [comment]
Hi Zhongheng, 

I see. Probably there is difference between first-principles settings. I can figure out this with you, but I'm not available until next Tuesday. Before that, you can also try with Cu's models (http://dplibrary.deepmd.net/#/project_details?project_id=202010.008) and DP-GEN's paper. 

Besides, recently we've refacted DP-GEN's autotest part and the latest version (>=0.9.2) has supported this. The documentation is on https://github.com/deepmodeling/dpgen/wiki/Relaxation:-get-started-and-input-examples . 
You can try this and you're welcomed to give suggestions about user-interface or anything else.

Best wishes!

Yuzhi

**Comment by ZhonghengFu** [comment]
Hi Yuzhi,
Based on our discussion in Wechat, I have checked my modified dpgen version, which is consistent with the current public version. Therefore I will not put it into the attachment.
In addition, the Epa is still -3.75 eV, which might be attributed to be the different parameters in INCAR. I will follow your feedback.

Best regards,
Zhongheng
