### ISSUE TITLE
assert(system.formula == self.formula) AssertionError

### ISSUE THREAD

**Issue by AmbroseWong** [deepmodeling/dpgen#425]
**Summary**

Hi everyone!
I tried to use dpgen to fit a NN potential, and everything works well as I used sys_configs with same atom numbers, which were used to derived unreasonable  configs and were added to next training iteration after first principles calculations. However, when I tried to replace these configs with different cell size and atom numbers, I encounter an issue when dpgen tried to make a new dataset based on these configs after first principles calculations. The error was "assert(system.formula == self.formula) AssertionError". Since I know when using the dpmd-kit, we need to separate different size dataset and train. I wonder if there is any argument   that can help me to fix this issue during the dpgen training process. Thanks a lot!!!

**Comment by AmbroseWong** [comment]
Usually when I trained using dpmd-kit, I separated different size dataset manually and train them in one iteration. My point is I wonder if there is any arguments which could detected the size difference of "sys_configs" in each dpgen iter and separated them automatically and train next iter rather show up this AssertionError

**Comment by AnguseZhang** [comment]
See https://github.com/deepmodeling/dpgen/issues/365 

You should make sure each element in"sys_configs" have the same formula. If you want to train systems with different sizes, just put them into different elements of the list and specify the index via "sys_idx" of "model_devi_jobs".

**Comment by AmbroseWong** [comment]
> See #365
> 
> You should make sure each element in"sys_configs" have the same formula. If you want to train systems with different sizes, just put them into different elements of the list and specify the index via "sys_idx" of "model_devi_jobs".

OK, thanks a lot. Meanwhile, I wonder if dpgen could add a new api for lammps input file? Since as you know, there are a lot of sampling and simulations algorithm. For example, I know a method called MSST, which could help people to simulate what's going on during the dynamic compression experiments. To sample this phase space during MSST, all you need to do is just modified lammps input. However, as far as I can see， there are a little lammps arguments could be modified during the model_devi iteration. And I did not find a api that could help you to write and customize your lammps input. Perhaps I did not find it but I think it could be a good way to take out the lammps input separately as what u did to VASP INCAR, since this process do not influence the overall workflow of dpgen. Is this could be achieved ?

**Comment by njzjz** [comment]
Custom template for LAMMPS is supported but the documentation is lacked.

**Comment by njzjz** [comment]
> Custom template for LAMMPS is supported but the documentation is lacked.

Documentation has been added in #1015, so I can close this issue.
