### ISSUE TITLE
The problem of main process 'dpgen run'

### ISSUE THREAD

**Issue by lyl2017710** [deepmodeling/dpgen#429]
Hello, everyone. I used dpgen for the first time. When I tried to run the main process of RUN, I made this mistake.I don't quite understand where the problem is, please help.Thank you！
![1](https://user-images.githubusercontent.com/85478180/120973612-bc6f3980-c7a1-11eb-9a21-468d8585c314.png)

**Comment by njzjz** [comment]
See #394.
