### ISSUE TITLE
Multi-task submission on the server

### ISSUE THREAD

**Issue by ZhonghengFu** [deepmodeling/dpgen#431]
Hello everyone,

I am a beginner using dpgen. When I tried to perform dpgen in the nodes in the national supercomputing center in Wuxi, I found the dpgen cannot be executed correctly, which was attributed to the special job submission mode in the cluster. Differing from the common mode in a lsf task submission system (usually, type some parameters and "mpirun -np xxx" into a script, and bsub it), we need to type "bsub -q xx -n xx vasp/lammps" into a script, and bash it. Accordingly, when I bash it, i get an output "Job <xxxxx> has been submitted to queue <xxxx>" immediately instead of the complete vasp/lammps calculation process. Therefore I need to modify the dpgen to meet it. However, despite the fact that the modified dpgen was executed, a task submission on the server was performed one by one instead of a multi-task submission. Could anyone please provide me any hints for it? Attached please find the modified LSF.py and the Al example. I am looking forward to your reply.

Best regards,
Zhongheng
[Al.zip](https://github.com/deepmodeling/dpgen/files/6616377/Al.zip)
[LSF.py.zip](https://github.com/deepmodeling/dpgen/files/6616380/LSF.py.zip)

**Comment by AnguseZhang** [comment]
<img width="1391" alt="Screen Shot 2021-06-09 at 11 55 19 AM" src="https://user-images.githubusercontent.com/38939321/121290643-92408780-c919-11eb-9a8f-315da4ae02ee.png">
Why do you use "nohup bash" instead of "bash" directly?

**Comment by ZhonghengFu** [comment]
Hi Yuzhi,
I modified it. However, it still doesn't work... I used "nohup bash script &" to make the script be executed in the background.
![image](https://user-images.githubusercontent.com/47444145/121293044-8d7dd280-c91d-11eb-8f78-90c38e6eac9b.png)

Best regards,
Zhongheng

**Comment by AnguseZhang** [comment]
I mean  "&". Do you still have a "&"  in "stdin, stdout, stderr = self.context.block_checkcall('cd %s && %s %s &\n\n' % (self.context.remote_root, 'nohup bash', self.sub_script_name"?  Make sure that you delete it. 
This will block the next command from execution before it finishes.

Yuzhi

**Comment by ZhonghengFu** [comment]
Hi Yuzhi,
Yes, I had deleted the "&" before I ran the example. However, it still doesn't work.
Attached please find the modified LSF.py file.

Best regards,
Zhongheng
[LSF.py.zip](https://github.com/deepmodeling/dpgen/files/6621459/LSF.py.zip)

**Comment by AnguseZhang** [comment]
![image](https://user-images.githubusercontent.com/38939321/121304438-eace4f80-c92e-11eb-8a63-ff39fca63709.png)
I have a question. Why the jobs fc85f34a-xxxx and dfb1c631-xxx are submitted separately, but they all finished immediately after the latter is submitted. Did you check the results inside the two jobs? Are they normal?

**Comment by ZhonghengFu** [comment]
Yes, it is confusing. I checked the results for the two tasks. They are normal. In addition, I noticed that the whole running process for my jobs is that the info: "new submission of fc85f34a-xxx" was output after the first vasp calculation was completed, and the second vasp calculation was started to be executed (but the info "job fc85f34a-xxx finished" was not output at that moment). Similarly, the second info: "new submission of dfb1c631-xxx" was output after the second vasp calculation was completed. the two infos "job xxx finished" were output at the same time. Therefore, the issue is that the task status cannot be diagnosed correctly in my opinion, and the info cannot be output correctly.

Best regards,
Zhongheng

**Comment by ZhonghengFu** [comment]
Hi Yuzhi,
The issue has been fixed. The context.block_checkcall was dropped and it worked.
![image](https://user-images.githubusercontent.com/47444145/121320404-b6af5a80-c93f-11eb-9f38-7534eabe8bdb.png)

Best regards,
Zhongheng

**Comment by Cloudac7** [comment]
Which LSF version are you now using and if JobID would be supplied when task submitted from just `bash bsub -q xxx -n xxx`, like this: `Job <148222> is submitted to queue <51-small>.`.

**Comment by ZhonghengFu** [comment]
Hi,
I am sorry that I don't know the LSF version I am using now.
Yes, a sentence like Job <148222> is submitted to queue <51-small> could be output after a job was submitted.

Best regards,
Zhongheng

**Comment by Cloudac7** [comment]
> Hi,
> I am sorry that I don't know the LSF version I am using now.
> Yes, a sentence like Job <148222> is submitted to queue <51-small> could be output after a job was submitted.
> 
> Best regards,
> Zhongheng

Well, if Job ID **could** be acquired from the very output of submission command, I think the original way generating `subret` might take effect, with `nohup` not used (as @AnguseZhang just suggestted).

**Comment by ZhonghengFu** [comment]
Thank you very much!
