### ISSUE TITLE
[BUG] dpgen choose the wrong python executable in Conda envrionment

### ISSUE THREAD

**Issue by leoil** [deepmodeling/dpgen#442]
**Summary**

**DPGEN Version and Platform**

DPGEN version: 0.9.3.dev17+gcc816d5
(conda) python version: Python 3.7.10 (default, Jun  4 2021, 14:48:32)  [GCC 7.5.0] :: Anaconda, Inc. on linux

**Actual Behavior**

When I was runing a example using `dpgen run` for the first time in the **dp-cpu**,  this error occurs:
```
# File  "~/.local/lib/python3.7/site-packages/dpgen/generator/lib/gaussian.py"

ModuleNotFoundError: No module named 'openbabel'
```

I intalled both the GPI and CPU version of deepmd-kit in separate conda environment. 

The two envs are runing with` different versions **(different date)** of Python 3.7
```
(dp-cpu) [xxx@node1 ~]$ python
Python 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
```
```
(dp-gpu) [liuquansheng@node1 ~]$ python
Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
[GCC 7.3.0] :: Anaconda, Inc. on linux

```

However, `openbebel` is already installed in **dp-cpu**.

So I dig around a little bit, and find out that the python executable that runs  `gaussian.py` is actually from **dp-gpu** conda env which has its own import path, and  `openbabel` module is not installed in `dp-gpu`.

```
# added  to the gaussian.py
import sys
print(sys.version)
```

```
# output: 
Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
```

I used `pip install --user` in the dpgen dir for installation, the installation path is `~/.local/bin/dpgen` and the installed source file path is ` ~/.local/lib/python3.7/site-packages/dpgen`

I wonder if it's because dpgen itself is not installed locally for a single conda env, so although the `dpgen run` is executed in `dp-cpu`, the python exectable from `dp-gpu` is called.  Maybe because they are both Python3.7.

It's not a big deal though, but I feel like it worth mentioning.

Thanks a lot for your work.

**Comment by AnguseZhang** [comment]
Thanks for reporting the problem. However, this seems not a bug of DP-GEN, but instead of a common issue of conda package. You can try re-install `dpgen` in `dp-cpu` environment: 
```bash
conda activate dp-cpu;
pip uninstall dpgen
pip install dpgen
dpgen -h
```

**Comment by leoil** [comment]
OK i got it! 
Thanks a lot.
