### ISSUE TITLE
dpgen can not install

### ISSUE THREAD

**Issue by walkjoker-c** [deepmodeling/dpgen#447]
When I download from GitHub, I use command “   python3 setup.py install  ” to install the following error, what should I do , how can I solve this problem?

![WQM0BE18VFSWNR%~W(NU4X3](https://user-images.githubusercontent.com/74398479/123389344-5e798900-d5cc-11eb-85e4-5400f1f43ab6.png)

**Comment by AnguseZhang** [comment]
Download a complete source code of DP-GEN by
```bash
https://github.com/deepmodeling/dpgen.git
cd dpgen;
# See current versions of DP-GEN
git tag
# Switch to a certain version
git checkout SOMEVERSION
```

Btw, the version 0.7.0 is too old, and is no longer maintained or supported. You're suggested upgrade DP-GEN to >= 0.9.0

Yuzhi
