### ISSUE TITLE
[Feature Request] Update CP2K example

### ISSUE THREAD

**Issue by AnguseZhang** [deepmodeling/dpgen#450]
**Summary**

We should update example for DP-GEN for CP2K.

**Detailed Description**

Old version example in https://github.com/deepmodeling/dpgen/blob/devel/examples/run/deprecated/dp0.12-lammps-cp2k/CH4/param_CH4.json has been deprecated.

**Comment by njzjz** [comment]
Close as it was fixed by #456.
