### ISSUE TITLE
Job number control 

### ISSUE THREAD

**Issue by tfcao888666** [deepmodeling/dpgen#452]
Hi All, 
I have one question regarding the total number of jobs that is submited. In the cluster the maximum jobs we can sumit is 10. However, in the ini process. A lot of jobs fold are created and they are submitted at the same time. How to control the number of jobs that can be submitted. 
Another questions, in the ini (dpgen init_bulk ). If some jobs do not terminate properly. How to resubmit it.
Thank you for the help!
Best   

**Summary**

**Detailed Description**

**Further Information, Files, and Links**

**Comment by AnguseZhang** [comment]
You can first use "group_size" to control the jobs

@felix5572  Btw, is there support in new dispatcher to control the maximal number of jobs submitted?

**Comment by felix5572** [comment]
Temporarily not， but  when it reaches the limitation of slurm system, It can stop submitting and wait unit the current jobs finish.

**Comment by tfcao888666** [comment]
Thank you for the clarification.

**Comment by njzjz** [comment]
> Btw, is there support in new dispatcher to control the maximal number of jobs submitted?

@AnguseZhang In the new dispatcher, I changed the implementation. It will be still submitted, but when it exceeds the limitation, slurm will throw an error which can be caught by dispatcher. Dispatcher will skip submitting it and try to submit it next time.
