### ISSUE TITLE
Error in the dpgen run step.

### ISSUE THREAD

**Issue by tfcao888666** [deepmodeling/dpgen#454]
Hi All, 
I am training model for the BaTiS3. I have go through the ini step, and
now go in the  dpgen run step. Always encount an error " File "/home/tfcao/miniconda3/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/tfcao/miniconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/tfcao/miniconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/tfcao/miniconda3/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
 "     
Could you kindly tell me the possible resons? 
Thank you  

Before asking questions, you can

search the previous issues or discussions
check [Manual](https://github.com/deepmodeling/dpgen).

Please **do not** post requests for help (e.g. with installing or using dpgen) here. 
Instead go to [discussions](https://github.com/deepmodeling/dpgen/discussions).

This issue tracker is for tracking dpgen development related issues only.

Thanks for your cooperation.

**Comment by AnguseZhang** [comment]
You didn't provide the full information of error log.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 4, 2021 12:16 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [deepmodeling/dpgen] Error in the dpgen run step. (#454)




 
Hi All,
 I am training model for the BaTiS3. I have go through the ini step, and
 now go in the  dpgen run step. Always encount an error " File "/home/tfcao/miniconda3/lib/python3.9/json/init.py", line 293, in load
 return loads(fp.read(),
 File "/home/tfcao/miniconda3/lib/python3.9/json/init.py", line 346, in loads
 return _default_decoder.decode(s)
 File "/home/tfcao/miniconda3/lib/python3.9/json/decoder.py", line 337, in decode
 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 File "/home/tfcao/miniconda3/lib/python3.9/json/decoder.py", line 353, in raw_decode
 obj, end = self.scan_once(s, idx)
 "
 Could you kindly tell me the possible resons?
 Thank you
 
Before asking questions, you can
 
search the previous issues or discussions
 check Manual.
 
Please do not post requests for help (e.g. with installing or using dpgen) here.
 Instead go to discussions.
 
This issue tracker is for tracking dpgen development related issues only.
 
Thanks for your cooperation.

**Comment by tfcao888666** [comment]
Hi Yuzhi
Thank you for the response. Here is the error.log
DeepModeling
------------
Version: 0.1.dev1626+gcc816d5
Date:    Jul-01-2021
Path:    /home/tfcao/miniconda3/lib/python3.9/site-packages/dpgen

Reference
------------
Please cite:
Yuzhi Zhang, Haidi Wang, Weijie Chen, Jinzhe Zeng, Linfeng Zhang, Han Wang,
and Weinan E,
DP-GEN: A concurrent learning platform for the generation of reliable deep
learning
based potential energy models, Computer Physics Communications, 2020,
107206.
------------

Description
------------
Traceback (most recent call last):
  File
"/home/tfcao/miniconda3/lib/python3.9/site-packages/dpgen/generator/run.py",
line 2323, in run_iter
    mdata=loadfn(machine_file)
  File
"/home/tfcao/.local/lib/python3.9/site-packages/monty/serialization.py",
line 85, in loadfn
    return json.load(fp, *args, **kwargs)
  File "/home/tfcao/miniconda3/lib/python3.9/json/__init__.py", line 293,
in load
    return loads(fp.read(),
  File "/home/tfcao/miniconda3/lib/python3.9/json/__init__.py", line 359,
in loads
    return cls(**kw).decode(s)
  File "/home/tfcao/.local/lib/python3.9/site-packages/monty/json.py", line
422, in decode
    d = json.JSONDecoder.decode(self, s)
  File "/home/tfcao/miniconda3/lib/python3.9/json/decoder.py", line 337, in
decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/tfcao/miniconda3/lib/python3.9/json/decoder.py", line 353, in
raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double
quotes: line 16 column 7 (char 390)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tfcao/miniconda3/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/home/tfcao/miniconda3/lib/python3.9/site-packages/dpgen/main.py",
line 175, in main
    args.func(args)
  File
"/home/tfcao/miniconda3/lib/python3.9/site-packages/dpgen/generator/run.py",
line 2410, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File
"/home/tfcao/miniconda3/lib/python3.9/site-packages/dpgen/generator/run.py",
line 2328, in run_iter
    mdata = json.load (fp)
  File "/home/tfcao/miniconda3/lib/python3.9/json/__init__.py", line 293,
in load
    return loads(fp.read(),
  File "/home/tfcao/miniconda3/lib/python3.9/json/__init__.py", line 346,
in loads
    return _default_decoder.decode(s)
  File "/home/tfcao/miniconda3/lib/python3.9/json/decoder.py", line 337, in
decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/tfcao/miniconda3/lib/python3.9/json/decoder.py", line 353, in
raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double
quotes: line 16 column 7 (char 390)
And here is

"type_map": ["Ba","Ti","S"],
"mass_map": [137.33, 47.87, 32.06],
"_comment": "initial data set for Training and the number of frames in each
training batch",
"init_data_prefix": "/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1",
"init_data_sys": [
"ini/POSCAR.01x01x01/02.md/sys-0002-0002-0006/deepmd"],
"init_batch_size": [8],
"sys_configs_prefix": "ini/POSCAR.01x01x01/02.md/sys-0002-0002-0006/deepmd",
"sys_configs": [
["ini/POSCAR.01x01x01/02.md/sys-0002-0002-0006/scale-1.000/00000*/POSCAR"],
["ini/POSCAR.01x01x01/02.md/sys-0002-0002-0006/scale-1.000/00001*/POSCAR"],
["ini/POSCAR.01x01x01/02.md/sys-0002-0002-0006/scale-1.000/00002*/POSCAR"]
],
"sys_batch_size": [8, 8],
"_comment": " 00.train ",
"numb_models": 4,
"default_training_param": {
"model": {
"type_map": ["Ba","Ti","S"],
"descriptor": {
"type": "se_a",
"sel": [16,4],
"rcut_smth": 0.5,
"rcut": 5.0,
"neuron": [10,20,40],
"resnet_dt": false,
"axis_neuron": 12,
"seed": 1
},
"fitting_net": {
"neuron": [120,120,120],
"resnet_dt": true,
"coord_norm": true,
"type_fitting_net": false,
"seed": 1
}
},
"loss": {
"start_pref_e": 0.02,
"limit_pref_e": 2,
"start_pref_f": 1000,
"limit_pref_f": 1,
"start_pref_v": 0,
"limit_pref_v": 0
},
"learning_rate": {
"type": "exp",
"start_lr": 0.001,
"decay_steps": 10,
"decay_rate": 0.95
},
"training": {
"systems": [],
"set_prefix": "set",
"stop_batch": 5000,
"batch_size": 1,
"seed": 1,
"_comment": "frequencies counted in batch",
"disp_file": "lcurve.out",
"disp_freq": 1000,
"numb_test": 4,
"save_freq": 1000,
"save_ckpt": "model.ckpt",
"load_ckpt": "model.ckpt",
"disp_training": true,
"time_training": true,
"profiling": false,
"profiling_file": "timeline.json"
}
},
"_comment": " 01.model_devi ",
"model_devi_dt": 0.002,
"model_devi_skip": 0,
"model_devi_f_trust_lo": 0.01,
"model_devi_f_trust_hi": 0.3,
"model_devi_clean_traj": false,
"model_devi_jobs": [
{
"sys_idx": [
0
],
"temps": [
50
],
"press": [
1
],
"trj_freq": 10,
"nsteps": 1000,
"ensemble": "nvt",
"_idx": "00"
},
{
"sys_idx": [
1
],
"temps": [
50
],
"press": [
1
],
"trj_freq": 10,
"nsteps": 3000,
"ensemble": "nvt",
"_idx": "01"
}
],
"_comment": " 02.fp ",
"fp_style": "vasp",
"shuffle_poscar": false,
"fp_task_max": 25,
"fp_task_min": 8,
"fp_pp_path": "/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/work",
"fp_pp_files":
["/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/POT_Ba",
"/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/POT_Ti",
"/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/POT_S"],
"fp_incar":
"/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/INCAR_methane"

and here is machine

"train": [
    {
      "machine": {
        "machine_type": "slurm",
        "work_path":
"/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/work"
      },
      "resources": {
        "numb_node": 1,
        "task_per_node": 64,
        "partition": "compute",
        "exclude_list": [],
        "source_list": [],
        "module_list": [],
        "time_limit": "12:00:00",
      },
      "python_path": "~/miniconda3/bin/python"
    }
  ],
  "model_devi": [
    {
      "machine": {
        "machine_type": "slurm",
        "work_path":
"/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/work"
      },
      "resources": {
        "numb_node": 1,
        "task_per_node": 64,
        "partition": "compute",
        "exclude_list": [],
        "source_list": [],
        "module_list": [],
        "time_limit": "12:00:00",
      },
      "command": "mpirun -np 64  /home/tfcao/vasp_bin/regular/vasp",
      "group_size": 1
    }
  ],
  "fp": [
    {
      "machine": {
        "machine_type": "slurm",
        "work_path":
"/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/work"
      },
      "resources": {
        "numb_node": 1,
        "task_per_node": 64,
        "exclude_list": [],
        "with_mpi": false,
        "source_list": [],
        "module_list": [],
        "time_limit": "12:00:00",
        "partition": "compute",
        "_comment": "that's All"
      },
      "command": "mpirun -np 64  /home/tfcao/vasp_bin/regular/vasp",
      "group_size": 1
    }
  ]
}
~

**Comment by AnguseZhang** [comment]
You spelt wrong in machine.json 
There is missing { in the first line 
<img width="553" alt="Screen Shot 2021-07-04 at 6 26 42 PM" src="https://user-images.githubusercontent.com/38939321/124381481-6389b700-dcf5-11eb-90eb-cbddcb1559e8.png">
Delete the final extra "," in ["train"]["resources"] and ["model_devi"]["resources"]
<img width="595" alt="Screen Shot 2021-07-04 at 6 27 27 PM" src="https://user-images.githubusercontent.com/38939321/124381498-7d2afe80-dcf5-11eb-9962-e5841e15db0e.png">

You should carefully check your own input file.
After you change it, you can use 
```python
import json
json.load(open("machine.json"))
```
to check it has been correct.

Yuzhi

**Comment by tfcao888666** [comment]
Hi Yuzhi,
I am sorry. I do not miss "{". When I copy and pasts it here.I miss it
here.
{
"type_map": ["Ba","Ti","S"],
"mass_map": [137.33, 47.87, 32.06],
"_comment": "initial data set for Training and the number of frames in each
training batch",
"init_data_prefix": "/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1",
"init_data_sys": [
"ini/POSCAR.01x01x01/02.md/sys-0002-0002-0006/deepmd"],
"init_batch_size": [8],
"sys_configs_prefix": "ini/POSCAR.01x01x01/02.md/sys-0002-0002-0006/deepmd",
"sys_configs": [
["ini/POSCAR.01x01x01/02.md/sys-0002-0002-0006/scale-1.000/00000*/POSCAR"],
["ini/POSCAR.01x01x01/02.md/sys-0002-0002-0006/scale-1.000/00001*/POSCAR"],
["ini/POSCAR.01x01x01/02.md/sys-0002-0002-0006/scale-1.000/00002*/POSCAR"]
],
"sys_batch_size": [8, 8],
"_comment": " 00.train ",
"numb_models": 4,
"default_training_param": {
"model": {
"type_map": ["Ba","Ti","S"],
"descriptor": {
"type": "se_a",
"sel": [16,4],
"rcut_smth": 0.5,
"rcut": 5.0,
"neuron": [10,20,40],
"resnet_dt": false,
"axis_neuron": 12,
"seed": 1
},
"fitting_net": {
"neuron": [120,120,120],
"resnet_dt": true,
"coord_norm": true,
"type_fitting_net": false,
"seed": 1
}
},
"loss": {
"start_pref_e": 0.02,
"limit_pref_e": 2,
"start_pref_f": 1000,
"limit_pref_f": 1,
"start_pref_v": 0,
"limit_pref_v": 0
},
"learning_rate": {
"type": "exp",
"start_lr": 0.001,
"decay_steps": 10,
"decay_rate": 0.95
},
"training": {
"systems": [],
"set_prefix": "set",
"stop_batch": 5000,
"batch_size": 1,
"seed": 1,
"_comment": "frequencies counted in batch",
"disp_file": "lcurve.out",
"disp_freq": 1000,
"numb_test": 4,
"save_freq": 1000,
"save_ckpt": "model.ckpt",
"load_ckpt": "model.ckpt",
"disp_training": true,
"time_training": true,
"profiling": false,
"profiling_file": "timeline.json"
}
},
"_comment": " 01.model_devi ",
"model_devi_dt": 0.002,
"model_devi_skip": 0,
"model_devi_f_trust_lo": 0.01,
"model_devi_f_trust_hi": 0.3,
"model_devi_clean_traj": false,
"model_devi_jobs": [
{
"sys_idx": [
0
],
"temps": [
50
],
"press": [
1
],
"trj_freq": 10,
"nsteps": 1000,
"ensemble": "nvt",
"_idx": "00"
},
{
"sys_idx": [
1
],
"temps": [
50
],
"press": [
1
],
"trj_freq": 10,
"nsteps": 3000,
"ensemble": "nvt",
"_idx": "01"
}
],
"_comment": " 02.fp ",
"fp_style": "vasp",
"shuffle_poscar": false,
"fp_task_max": 25,
"fp_task_min": 8,
"fp_pp_path": "/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/work",
"fp_pp_files":
["/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/POT_Ba",
"/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/POT_Ti",
"/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/POT_S"],
"fp_incar":
"/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/INCAR_methane"
The error is still there,😅
