### ISSUE TITLE
"conf_dir": "confs/Al/std-fcc" in autotest 

### ISSUE THREAD

**Issue by tfcao888666** [deepmodeling/dpgen#457]
Hi All,
I am doing autotest with dpgen. 
This  tag "conf_dir": "confs/Al/std-fcc" is confusing. I think it is directory of the POSCAR. However, when I put the direcotry. I always encount this error:“  File "/home/tfcao/miniconda3/lib/python3.9/site-packages/dpgen/auto_test/run.py", line 16, in run_task
    confs = jdata['structures']
KeyError: 'structures'
 ”  
Here is the parameter:
"{
    "_comment": "models",
    "potcar_map": {
        "BaTiS3": "/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/POTCAR"
    },

    "conf_dir": "/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1",
    "key_id": "",
    "task_type": "vasp",
    "task": "eos",

    "relax_incar": "/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/relax_incar",
    "scf_incar": "/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1/scf_incar",

    "vasp_params":      {
        "ecut":         650,
        "ediff":        1e-6,
        "kspacing":     0.1,
        "kgamma":       false,
        "npar":         1,
        "kpar":         1,
        "_comment":     " that's all "
    },
    "lammps_params":    {
        "model_dir":"/expanse/lustre/scratch/tfcao/temp_project/batis3-dp1",
        "type_map":["Ba", "Ti", "S"],
        "model_name":false,
        "model_param_type":false
    },

    "_comment": "00.equi",
    "alloy_shift": false,
    "_comment": "01.eos",
    "vol_start": 12,
    "vol_end": 22,
    "vol_step": 0.5,
    "_comment": "02.elastic",
    "norm_deform": 2e-2,
    "shear_deform": 5e-2
}
"
Please have a look, thank you!
Best 
Tengfei  

**Summary**

**Summary**

**Detailed Description**

**Further Information, Files, and Links**

**Comment by AnguseZhang** [comment]
Hi Tengfei, thanks for trying DP-GEN's auto-test module. 
Autotest module has been refactored, and the examples you refer to has been deprecated. We'll try to update the examples in`dpgen/examples`as soon as possible. 
For now, you can refer to https://github.com/deepmodeling/dpgen/wiki/Relaxation:-get-started-and-input-examples and  https://github.com/deepmodeling/dpgen/wiki/Property:-get-started-and-input-examples. 
Btw notice that "structures" should be a list. 

Best wishes.

Yuzhi
