### ISSUE TITLE
restart dpgen run process  

### ISSUE THREAD

**Issue by tfcao888666** [deepmodeling/dpgen#460]
Hi All, 
I use dpgen run and traind the models. I want to add more intial data, and more training steps. Are their any ways to restart from the old potential. For example, I have trained my potential for 100000 steps,  and  want to add more data and more training steps. Coud I restart from 100001 step? Thank you!
Best regards!
Tengfei 

**Summary**

**Detailed Description**

**Further Information, Files, and Links**

**Comment by AnguseZhang** [comment]
@Ericwang6  https://github.com/deepmodeling/dpgen/blob/devel/examples/run/dp1.x-gromacs-gaussian/param.json

**Comment by njzjz** [comment]
The documentation has included the related parameters. https://docs.deepmodeling.com/projects/dpgen/en/devel/run/param.html#run-jdata-training-iter0-model-path
