### ISSUE TITLE
[Parameters] Misleading explanation of the type of "fp_aniso_kspacing"

### ISSUE THREAD

**Issue by DingChangjie** [deepmodeling/dpgen#476]
**Summary**

In README.md, the type of "fp_aniso_kspacing" is "List of integers", which seems to be incorrect : 
![Inked文档这里有误_LI](https://user-images.githubusercontent.com/59408640/126659825-4692041a-b969-4c5d-b1f3-6fccbe8e4916.jpg)

**Detailed Description**
Take a typical aniso cell as an example (a1≈6Å，a2≈6Å，a3≈30Å). A suitable KPOINTS file may present as follows : 
```
Some Comments
0
Monkhorst (or Gamma)
6 6 1
```
To handle this, DpGen's expected behaviour should be like writing the same strings as mentioned in example during the make_fp process. However, A problem occurred that in this example, the b1 and b2 are definitely not integers, but fractions [1/6, 1/6]. (See VASP's official wiki of [KPOINTS](https://www.vasp.at/wiki/index.php/KPOINTS) and [KSPACING](https://www.vasp.at/wiki/index.php/KSPACING)). To gain a better understanding, one can refer to the source code in [`dpgen/auto_test/lib/vasp.py, in function make_kspacing_kpoints`](https://github.com/deepmodeling/dpgen/blob/master/dpgen/auto_test/lib/vasp.py)

```
def make_kspacing_kpoints(poscar, kspacing, kgamma) :
    if type(kspacing) is not list:
        kspacing = [kspacing, kspacing, kspacing]
    with open(poscar, 'r') as fp:
        lines = fp.read().split('\n')
    scale = float(lines[1]) 
    box = []
    for ii in range(2,5) :
        box.append([float(jj) for jj in lines[ii].split()[0:3]])
    box = np.array(box)
    box *= scale
    rbox = reciprocal_box(box) 
    # ==== user-specified kspacing is first converted to kpoints ==========
    kpoints = [max(1,(np.ceil(2 * np.pi * np.linalg.norm(ii) / ks).astype(int))) for ii,ks in zip(rbox,kspacing)]
    ret = make_vasp_kpoints(kpoints, kgamma)
    # ===== then kpoints is used to write KPOINTS file ======
    return ret
```
Thus in my case, I have to specify fp_aniso_kspacing as [0.16667, 0.16667, 1] , to get a work-around. (Mind that I can't even write 1/6, which would cause errors in parsing params.json file). Here is a snapshot of a correctly generated KPOINTS file : 
![正确结果](https://user-images.githubusercontent.com/59408640/126662297-b225405e-5405-41b8-98a3-34fd2c720669.png)

PS : I think it might be a easier and more direct way for both users and programmers, to change this parameter into something like `"fp_k_subdivisions" : [6,6,1]`  and let the program directly paste this line into the generated KPOINTS file ...

**Comment by njzjz** [comment]
Close as resolved.
