### ISSUE TITLE
request for the update of the example of test

### ISSUE THREAD

**Issue by Msunshinep** [deepmodeling/dpgen#483]
Dear developer，

Thank you very much for the development of dpgen. I am a newer using it.
I find the example of the json file for "test" cannot work well, for example the parameter " conf_dir  “ in json should be ”structures“?
So, I want to request for the latest version of the json files for ”test“

Looking forward to your reply！
Best regards！
ChengYu

**Comment by AnguseZhang** [comment]
Sorry for late reply. Now auto-test's documentation is on https://github.com/deepmodeling/dpgen/wiki/Auto-test

**Comment by Msunshinep** [comment]
Thank you very much for your responses to my request！
Best regards！
