### ISSUE TITLE
what are the differences between the "failed tasks" and "failed frame" after finishing 02.fp?

### ISSUE THREAD

**Issue by taipinghu** [deepmodeling/dpgen#485]
Dear developers, 

when the 02.fp process is finished, an error occurs in my calculation. 
  5 2021-08-04 10:55:38,144 - INFO : failed tasks:      0 in    200    0.00 %
  6 2021-08-04 10:55:40,876 - INFO : failed frame:     54 in    190   28.42 %
RuntimeError: find too many unsuccessfully terminated jobs

I have carefully check the OUTCAR in 02.fp, but the OUTCAR files in some directories are not return. when the tasks are calculating, I noticed that the SCF iterations were not converged but the OUTCAR still normally terminated. 

Why the failed frame is "54 in 190 28.42"? I have modified the ratio_failure (larger than 28.42%) of the Machine file. However, this error still occurs. What are the differences between the "failed tasks" and "failed frame"? 

Thanks for your reply.

Taiping

**Comment by AnguseZhang** [comment]
@dingzhaohan 
Please see this issue.
I think there is a bug in https://github.com/deepmodeling/dpgen/blob/ddf39f174a1784ab2a41db225ecbc3b867ae5f99/dpgen/dispatcher/DispatcherList.py#L48

**Comment by HuangJiameng** [comment]
`failed tasks` is about the transmission of the files by dpdispatcher, `failed frame` is about the result of the calculation.
