### ISSUE TITLE
[BUG] `dpgen autotest run` doesn't work on ALIYUN-EHPC-beijing

### ISSUE THREAD

**Issue by tuoping** [deepmodeling/dpgen#501]
**Summary**

`dpgen autotest run relax.json machine.json`
`dpgen autotest post relax.json`
`dpgen autotest make interstitial.json`
All succeeded. 
Only `dpgen autotest run interstitial.son machine.json` didn't do anything but finished.
```json
2021-08-20 10:50:04,899 - INFO : start auto-testing
2021-08-20 10:50:05,359 - INFO : finished!
```

**DPGEN Version and Platform**
0.10.0 & 0.10.1.dev27+g6af59ba
Platform: EHPC-beijing

**Job submission and computing cluster configuration**

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by AnguseZhang** [comment]
The interstitial module in `dpgen`  0.10.6 version should work.
