### ISSUE TITLE
[BUG]no detection for the task of SCF not converged in fp cal

### ISSUE THREAD

**Issue by 343333333** [deepmodeling/dpgen#503]
hello ,
when i use cp2k to calculate the fp task .Because of the program itself, some fp may not converged in their fp calculation,  but when finished the fp  processes the data of this SCF failed to converged  will also be included.
so , i would be thankful if you can add a detection in the post-treatment in fp to detect the data is converged or not.
here is the pic:
![P84Y~8_(`)Y%H`}5 A)F8DM](https://user-images.githubusercontent.com/38664390/130310043-e428bbb5-867d-405c-85cf-8f312c1a7716.png)
but when in the post-treatment they all get included
![image](https://user-images.githubusercontent.com/38664390/130310036-b163aa43-4a07-47a4-ab45-4740a23c0b9d.png)

**Comment by njzjz** [comment]
I think it has been fixed by #486

**Comment by robinzyb** [comment]
> I think it has been fixed by #486 - ping @robinzyb to confirm.

Yes, you're right
