### ISSUE TITLE
help help help !!!  something error  for running dpgen init_bulk 

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [deepmodeling/dpgen#540]
When I ran dpgen to do init_bulk, I used the official example to test. The example is in examples/init. My submission script dpgen.sh‘s  content is as follows ：

#!/bin/bash
#SBATCH -N 1
#SBATCH --ntasks-per-node 8
#SBATCH --partition gpu
#SBATCH --gres=gpu:1

module load deepmodeling/dpgen/0.9.2
module load deepmodeling/deepmd-kit/1.3.3
module load deepmodeling/lammps/deepmd1.3.3

dpgen init_bulk ch4.json

and then   sbatch --gpus=1 ./dpgen.sh

content of ch4.json is as follows：
{
    "stages":           [1,2,3,4],
    "cell_type":        "diamond",
    "super_cell":       [1, 1, 1],
    "elements":         ["H","C"],
    "from_poscar":      true,
    "from_poscar_path": "./CH4.POSCAR",
    "potcars":          ["./POTCAR_H", "./POTCAR_C"],
    "relax_incar":      "./INCAR_methane.rlx",
    "md_incar" :        "./INCAR_methane.md",
    "scale":            [1.00],
    "skip_relax":       false,
    "pert_numb":        30,
    "md_nstep" :        10,
    "pert_box":         0.03,
    "pert_atom":        0.01,
    "deepgen_templ":    "../generator/template/",
    "coll_ndata":       5000,
    "_comment":         "that's all"
}

INCAR_methane.rlx and INCAR_methane.md are also in the same directory as ch4.json.

al.json                    ch4.json             cu.surf.hcp.111.json   INCAR_methane.md    POT_H      
al.POSCAR             ch4.yaml            dpgen.log                  INCAR_methane.rlx      POT_C            reaction.json   surf.yaml
al.yaml                   dpgen.sh           machine.json              POTCAR_C                   test2.json
cu.json                   gmx2.py            POSCAR                      POTCAR_H                  slurm-76311.out  

but the output slurm-76311.out has something errors :
DeepModeling
------------
Version: 0.9.2
Date:    Mar-25-2021
Path:    /data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen
Traceback (most recent call last):
  File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/data/gen.py", line 366, in make_scale
    assert(os.path.isfile(pos_src))
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/apps/priv/.conda/envs/deepMD/bin/dpgen", line 10, in <module>
    sys.exit(main())
  File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/data/gen.py", line 716, in gen_init_bulk
    make_scale(jdata)
  File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/data/gen.py", line 368, in make_scale
    raise RuntimeError("not file %s, vasp relaxation should be run before scale poscar")
RuntimeError: not file %s, vasp relaxation should be run before scale poscar

I don't know what the above error means，and how to fix it.

**Comment by AnguseZhang** [comment]
You don't need to `sbatch dpgen.sh`. Instead, you should configure machine information in  `machine.json` and run command `dpgen init_bulk param.json machine.json`. 
See instructions of `machine.json` in the manual.

**Comment by zhoujingyu13687306871** [comment]
> 你不需要`sbatch dpgen.sh`。相反，您应该在中配置机器信息 `machine.json`并运行命令`dpgen init_bulk param.json machine.json`。
> 参见`machine.json`手册中的说明。

hello, I resubmitted the job after modifying the script, but found that the following error occurred：

Description
------------
Traceback (most recent call last):
  File "/data/apps/priv/.conda/envs/deepMD/bin/dpgen", line 10, in <module>
    sys.exit(main())
  File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/data/gen.py", line 716, in gen_init_bulk
    make_scale(jdata)
  File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/data/gen.py", line 373, in make_scale
    poscar_scale(pos_src, 'POSCAR', jj)
  File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/data/gen.py", line 173, in poscar_scale
    if 'D' == lines[7][0] or 'd' == lines[7][0]:
IndexError: list index out of range

**Comment by zhoujingyu13687306871** [comment]
> > 你不需要`sbatch dpgen.sh`。相反，您应该在中配置机器信息 `machine.json`并运行命令`dpgen init_bulk param.json machine.json`。
> > 参见`machine.json`手册中的说明。
> 
> hello, I resubmitted the job after modifying the script, but found that the following error occurred：
> 
> ## Description
> Traceback (most recent call last):
> File "/data/apps/priv/.conda/envs/deepMD/bin/dpgen", line 10, in
> sys.exit(main())
> File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/main.py", line 175, in main
> args.func(args)
> File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/data/gen.py", line 716, in gen_init_bulk
> make_scale(jdata)
> File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/data/gen.py", line 373, in make_scale
> poscar_scale(pos_src, 'POSCAR', jj)
> File "/data/apps/priv/.conda/envs/deepMD/lib/python3.7/site-packages/dpgen/data/gen.py", line 173, in poscar_scale
> if 'D' == lines[7][0] or 'd' == lines[7][0]:
> IndexError: list index out of range

**Comment by zhoujingyu13687306871** [comment]
> You don't need to `sbatch dpgen.sh`. Instead, you should configure machine information in `machine.json` and run command `dpgen init_bulk param.json machine.json`.
> See instructions of `machine.json` in the manual.

**Comment by zhoujingyu13687306871** [comment]
> 你不需要`sbatch dpgen.sh`。相反，您应该在中配置机器信息 `machine.json`并运行命令`dpgen init_bulk param.json machine.json`。
> 参见`machine.json`手册中的说明。

**Comment by AnguseZhang** [comment]
Please provide your POSCAR. Is your POSCAR compatible with VASP 5 ?

**Comment by zhoujingyu13687306871** [comment]
> Please provide your POSCAR. Is your POSCAR compatible with VASP 5 ?

I use vasp6 , here is my CH4.POSCAR

POSCAR file written by OVITO
   1.0000000000000000
    10.0000000000000000    0.0000000000000000    0.0000000000000000
     0.0000000000000000   10.0000000000000000    0.0000000000000000
     0.0000000000000000    0.0000000000000000   10.0000000000000000
   H    C
     4     1
Direct
  0.5381543385532134  0.4068608007477559  0.3605730142093164
  0.3945396557300829  0.4803205689390709  0.4384688400135213
  0.5520924283424902  0.5654502852627673  0.4427087377775140
  0.5281853047372259  0.4164147551778533  0.5391826568442692
  0.5032505926369848  0.4672551598725561  0.4452323411553799

  0.00000000E+00  0.00000000E+00  0.00000000E+00
  0.00000000E+00  0.00000000E+00  0.00000000E+00
  0.00000000E+00  0.00000000E+00  0.00000000E+00
  0.00000000E+00  0.00000000E+00  0.00000000E+00
  0.00000000E+00  0.00000000E+00  0.00000000E+00

**Comment by zhoujingyu13687306871** [comment]
> Please provide your POSCAR. Is your POSCAR compatible with VASP 5 ?

CH4.POSCAR  provided by official

**Comment by zhoujingyu13687306871** [comment]
btw  I found something errors in init/CH4.POSCAR.01x01x01/00.place_ele/sys-0004-0001

CONTCAR    INCAR    OUTCAR    POSCAR    POTCAR

when I open the OUTCAR :

  1  vasp.6.1.2 22Jul20 (build May 31 2021 10:13:24) complex
  2
  3  executed on             LinuxIFC date 2021.09.14  00:50:52
  4  running on    8 total cores
  5  distrk:  each k-point on    8 cores,    1 groups
  6  distr:  one band on NCORE=   2 cores,    4 groups
  7
  8
  9 --------------------------------------------------------------------------------------------------------
 10
 11
 12  INCAR:
 13  -----------------------------------------------------------------------------
 14 |                                                                             |
 15 |     EEEEEEE  RRRRRR   RRRRRR   OOOOOOO  RRRRRR      ###     ###     ###     |
 16 |     E        R     R  R     R  O     O  R     R     ###     ###     ###     |
 17 |     E        R     R  R     R  O     O  R     R     ###     ###     ###     |
 18 |     EEEEE    RRRRRR   RRRRRR   O     O  RRRRRR       #       #       #      |
 19 |     E        R   R    R   R    O     O  R   R                               |
 20 |     E        R    R   R    R   O     O  R    R      ###     ###     ###     |
 21 |     EEEEEEE  R     R  R     R  OOOOOOO  R     R     ###     ###     ###     |
 22 |                                                                             |
 23 |     ERROR: number of potentials on File POTCAR incompatible with number     |
 24 |     of species INCAR : 2POTCAR: 0                                           |
 25 |                                                                             |
 26 |       ---->  I REFUSE TO CONTINUE WITH THIS SICK JOB ... BYE!!! <----       |
 27 |                                                                             |
 28  -----------------------------------------------------------------------------

**Comment by AnguseZhang** [comment]
You should provide a valid POTCAR.

**Comment by zhoujingyu13687306871** [comment]
> You should provide a valid POTCAR.

After running the job, the generated POTCAR is empty

**Comment by AnguseZhang** [comment]
POTCAR is not expeceted to be generated, but provided by users before `dpgen` runs. Due to commercial license of VASP, we cannot provide POTCAR in examples. Please check if your POTCAR is empty.
