### ISSUE TITLE
[Parameters] Why are there two "type_map" items in param.json?

### ISSUE THREAD

**Issue by tuoping** [deepmodeling/dpgen#541]
**Summary**

There are two items of `type_map = ["C", "H"]` in the [param.json of the most recent example](https://github.com/deepmodeling/dpgen/blob/master/examples/run/dp2.x-gromacs-gaussian/param.json).

```json
{
  **"type_map": ["H", "C", "N", "O", "F", "S", "Cl"],** 
  "mass_map": [2, 12, 14, 16, 17, 32, 35],
  "init_data_prefix": "/path/to/init/data",
  "init_data_sys": ["data.init"],
  "init_multi_systems": true,
  "sys_configs_prefix": "/path/to/model/devi/data",
  "sys_configs": [
  ],
  "sys_charges": [
  ],
  "sys_format": "gromacs/gro",
  "numb_models": 4,
  "train_param": "input.json",
  "default_training_param": {
    "model": {
      **"type_map": ["H", "C", "N", "O", "F", "S", "Cl"],** 
      "descriptor": {
      },
      "fitting_net": {
      }
    },
    "learning_rate": {
    },
    "loss": {
    },
    "training": {
    }
  }
...
}
```
Can they be shared ?

**Detailed Description**

**Further Information, Files, and Links**

**Comment by Ericwang6** [comment]
They should be the same and both are required....I'll fix them and make a pr

**Comment by HuangJiameng** [comment]
The first `type_map` is the one that DP-GEN actually uses. The second one is in `default_training_param` according to the template of DeePMD-kit's training parameters. It will be OK if you skip the second `type_map` in `default_training_param`. Whether you set it or not, the second "type_map" will be assigned the value of the first one.
