### ISSUE TITLE
My machine is DCU,how i set the machine.json?

### ISSUE THREAD

**Issue by qinmi-sudo** [deepmodeling/dpgen#542]
![1](https://user-images.githubusercontent.com/70270603/133913869-20919e93-3d83-42b4-8961-3cdc5fead382.jpg)
When i set "numb_gpu": 1,the task script is 
![5ebbbc6efc3cd9c3895e2f8a69eb4cc](https://user-images.githubusercontent.com/70270603/133914070-4d110413-52ed-461a-a24a-7588a1b9a7bc.png)
But the correct script is like this :
![d29c62d1cc219d0eb5ea663c734457b](https://user-images.githubusercontent.com/70270603/133914086-77977cda-7d0c-4944-8327-c3aadcda668a.png)
So,my machine is DCU,how i set the machine.json?

**Comment by AnguseZhang** [comment]
"custom_flags" in new version of interface of `machine.json` can solve this.
You should adopt DP-GEN >= 0.10.0 and use `machine.json` from https://github.com/deepmodeling/dpgen/blob/master/examples/CH4-refact-dpdispatcher/machine-ali-ehpc.json

Please search "dpdispatcher" in the [manual](https://github.com/deepmodeling/dpgen)

**Comment by qinmi-sudo** [comment]
Thank you, I've solved it
