### ISSUE TITLE
Why I set  "numb_models": 4, only "000" generated.

### ISSUE THREAD

**Issue by qinmi-sudo** [deepmodeling/dpgen#543]
![8d5695ec82b01f4169887c2277008d5](https://user-images.githubusercontent.com/70270603/133914279-8be9ddbd-5e9a-4c87-9d13-eb71627c6985.png)
![2170c21ebe014b9747fbf8c5a761272](https://user-images.githubusercontent.com/70270603/133914309-ed322b42-35ec-434f-b361-fdc3c298809a.png)
My training work_path is "work_path": "/public/home/qinmi/mqin/DPgen/test/TEMPORARY/TRAIN"

**Comment by AnguseZhang** [comment]
Is there any error log ?

**Comment by njzjz** [comment]
You found it on the remote machine, where four directories are in separated directories.

**Comment by qinmi-sudo** [comment]
Thank you, I've solved it
