### ISSUE TITLE
[BUG] The softlink of model.*  files are not local path in aliyun  when DPGEN-training is called by tencent slurm V100 

### ISSUE THREAD

**Issue by bjyxffj** [deepmodeling/dpgen#551]
**Summary**
When the DP-GEN calls tencent slurm V100 for GPU calculation, in 00.train progress, the solflink path is the corresponding calculation path in tencent slurm V100. This is wrong path.  
   Example:  the model.ckpt.data-00000-of-00001 -> /root/dpgen_work/e39e2ed2-89cd-4137-b5d1-2e7f70b37455/000/model.ckpt-800000.data-00000-of-00001.  
   The correct path would be the " model.ckpt.data-00000-of-00001 -> ../../../../iter.000001/00.train/000/model.ckpt.data-00000-of-00001 ".

**DPGEN Version and Platform**

**Job submission and computing cluster configuration**

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by njzjz** [comment]
This has been fixed in deepmodeling/dpdispatcher#132. Please follow [this note](https://github.com/deepmodeling/dpgen#new-dpdispatcher-update-note) to migrate to the latest dpdispatcher. Old versions will not be maintained any more.

**Comment by njzjz** [comment]
Fixed in #552.
