### ISSUE TITLE
[BUG] sbatch: error: line must start with #! followed by the path to an interpreter

### ISSUE THREAD

**Issue by xhjj** [deepmodeling/dpgen#599]
There was an error running the SLURM sbatch command.
The command was:
'/usr/bin/sbatch -e 40980293c19f8a203acaf32a4c33e17cfa817371.sub.e%A -o 40980293c19f8a203acaf32a4c33e17cfa817371.sub.o%A 40980293c19f8a203acaf32a4c33e17cfa817371.sub 2>&1'
and the output was:
'sbatch: error: This does not look like a batch script.  The first
 sbatch: error: line must start with #! followed by the path to an interpreter.
 sbatch: error: For instance: #!/bin/sh
'
vim 40980293c19f8a203acaf32a4c33e17cfa817371.sub
and the first line is space

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
![4dcdf849de5899c44811483f24e4af8](https://user-images.githubusercontent.com/15103973/143521534-55d60122-c2e4-479e-b790-61c5394f11e1.png)

**Comment by AnguseZhang** [comment]
“'/usr/bin/sbatch -e 40980293c19f8a203acaf32a4c33e17cfa817371.sub.e%A -o 40980293c19f8a203acaf32a4c33e17cfa817371.sub.o%A 40980293c19f8a203acaf32a4c33e17cfa817371.sub 2>&1'” What's the relationship between this and DP-GEN?

**Comment by xhjj** [comment]
when i type in the command"dpgen init_bulk CH4.json machine.json", 
I get the error as follow:
"RuntimeError: Meet errors will handle unexpected submission state.
Debug information: remote_root==/home/*/work_path_dpdispatcher_test/b96775916a7ffb6e8d129930efe212ba5585bf20.
Debug information: submission_hash==b96775916a7ffb6e8d129930efe212ba5585bf20.
Please check the dirs and scripts in remote_rootThe job information mentioned above may help
"
so i view the 
/home/*/work_path_dpdispatcher_test/b96775916a7ffb6e8d129930efe212ba5585bf20/b96775916a7ffb6e8d129930efe212ba5585bf20.sub, and the commod as "qsub b96775916a7ffb6e8d129930efe212ba5585bf20.sub :,and the error is as followed:

sbatch: error: This does not look like a batch script.  The first
sbatch: error: line must start with #! followed by the path to an interpreter.
sbatch: error: For instance: #!/bin/sh

**Comment by xhjj** [comment]
help help help！！！！！！！

**Comment by AnguseZhang** [comment]
What's your scheduler system? PBS or Slurm? 
What did you set in your `machine.json`?
Please provide your `machine.json`.

**Comment by xhjj** [comment]
{
  "api_version": "1.0",
  "train": [
    {
      "command": "dp",
      "machine": {
        "batch_type": "PBS",
        "context_type": "SSHContext",
        "local_root": "./",
        "remote_root": "/home/jjh/work_path_dpdispatcher_test",
        "remote_profile": {
            "hostname": "172.27.233.27",
            "username": "jjh"
        }
      },
      "resources": {
        "number_node": 1,
        "cpu_per_node": 4,
        "gpu_per_node": 1,
        "queue_name": "T4_4_15",
        "group_size": 1,
        "custom_flags":["#SBATCH --mem=32G"],
        "strategy": {"if_cuda_multi_devices": true},
        "para_deg": 3,
        "source_list": ["/home/user1234/deepmd.1.2.4.env"]
      }
    }
  ],
  "model_devi":[
    {
      "command": "lmp",
      "machine":{
        "batch_type": "PBS",
        "context_type": "SSHContext",
        "local_root": "./",
        "remote_root": "/home/user1234/work_path_dpdispatcher_test",
        "remote_profile": {
          "hostname": "172.27.233.27",
          "username": "jjh"
        }
      },
      "resources": {
        "number_node": 1,
        "cpu_per_node": 4,
        "gpu_per_node": 1,
        "queue_name": "T4_4_15",
        "group_size": 5,
        "source_list": ["/home/user1234/deepmd.1.2.4.env"]
      }
    }
  ],
  "fp":[
    {
      "command": "vasp",
      "machine":{
        "batch_type": "PBS",
        "context_type": "SSHContext",
        "local_root": "./",
        "remote_root": "/home/*/work_path_dpdispatcher_test",
        "remote_profile": {
          "hostname": "172.30.107.150",
          "username": "jjh"
        }
      },
      "resources": {
        "number_node": 1,
        "cpu_per_node": 16,
        "gpu_per_node": 0,
        "queue_name": "cpu",
        "group_size": 1,
        "source_list": ["/home/jjh/vasp.6.1.0/bin/vasp"]

      }
    }
  ]
}

**Comment by xhjj** [comment]
when i set the slurm，it works.  but  another error appears. what is the "source_list"?

**Comment by xhjj** [comment]
/var/spool/slurmd/job00039/slurm_script: line 15: source: /home/jjh/vasp.6.1.0/bin/vasp: cannot execute binary file

**Comment by xhjj** [comment]
/var/spool/slurmd/job00039/slurm_script: line 15: source: /home/jjh/vasp.6.1.0/bin/vasp: cannot execute binary file

**Comment by xhjj** [comment]
when i set the SOURCE_LIST correctly, it wprks.
the next error is " find no valid outcar in sys sys-0004-0001, check if your vasp md simulation is correctly done"

**Comment by xhjj** [comment]
when i set the SOURCE_LIST correctly, it wprks.

**Comment by xhjj** [comment]
when i ues ”dpgen run param.json machine.json", it stop at :

Description
------------
2021-11-30 16:14:27,076 - INFO : info:check_all_finished: False
2021-11-30 16:14:27,076 - INFO : remote path: /home/jjh/work_path_dpdispatcher_test/3b5328c5cb7a63d766aa4102da5a385b85263811
2021-11-30 16:14:27,223 - INFO : job: 5be87d00ce1e43d4db20608f670a5a65a61c58aa submit; job_id is 278
2021-11-30 16:14:27,230 - INFO : job: c77a30252b163545ea07a3696483bdc3c7f46fc8 submit; job_id is 279
2021-11-30 16:14:27,237 - INFO : job: ab9886c22d1e0352c312d55f51e476bfcd712a0e submit; job_id is 280
2021-11-30 16:14:27,244 - INFO : job: 0bbe11c02995c9d572ccb6e6bdedc721b6d78134 submit; job_id is 281

---------------------
what can i do for it?

**Comment by njzjz** [comment]
> what can i do for it?

The program was waiting until the jobs normally finished. It never stopped.

**Comment by xhjj** [comment]
but it stay on the first step，and It hasn't been done all night. How do I need to accelerate?

**Comment by AnguseZhang** [comment]
In the first step, there may be four DeePMD-kit's training process, and this is quite normal for training several hours.

**Comment by AnguseZhang** [comment]
I think this issue can be closed. If you still have problems,  you're welcomed to re-open this issue or create a new discussion.
