### ISSUE TITLE
[BUG] GPU usage keep LOW

### ISSUE THREAD

**Issue by axin1212** [deepmodeling/dpgen#621]
**Summary**

**DPGEN Version and Platform**

**Job submission and computing cluster configuration**

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by AnguseZhang** [comment]
Please create issues in https://github.com/deepmodeling/deepmd-kit
Please provide necessary information, otherwise we cannot know what happens.

**Comment by axin1212** [comment]
1600 frames of configures have been trained in 4 GPU cards，the GPU type is V100, based on shell system. But the usage of GPU's memory keep on 1G/40G during training, which takes more than 10h for 40w steps. The version of dpgen is 0.10.2 and deepmd-kit is 2.0.3.

**Comment by njzjz** [comment]
I don't think the GPU memory is the same concept as the GPU usage. They are unrelated.
