### ISSUE TITLE
[Feature Request] The pypi installed and conda installed version is not the latest!!!

### ISSUE THREAD

**Issue by tuoping** [deepmodeling/dpgen#625]
**Summary**

There was an issue about two weeks ago about `autotest`. The energy value in result.out file is not divided by the sum of atom numbers, but by the number of the first type of atom. This is changed in the master branch, but not in the pypi installed version. Is there an `automatic updating` procedure to the pypi repo and conda repo? 

**Job submission and computing cluster configuration**

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by njzjz** [comment]
Resolved in the latest version.
