### ISSUE TITLE
[BUG] Dpgen Run simplify  name 'convert_mdata' is not defined Error

### ISSUE THREAD

**Issue by wangxx1987** [deepmodeling/dpgen#633]
**Summary**

Dpgen Run simplify  name 'convert_mdata' is not defined Error

**Version: 0.10.1.dev62+g591d26c**

![image](https://user-images.githubusercontent.com/98146358/150479784-2d552750-1749-4d1c-9f5a-cda6cc56ef85.png)

**Comment by AnguseZhang** [comment]
Please try https://github.com/deepmodeling/dpgen/pull/634/files
