### ISSUE TITLE
[BUG]Run dpgen smplify “sys_batch_size” Error

### ISSUE THREAD

**Issue by wangxx1987** [deepmodeling/dpgen#635]
**Summary**

<Run dpgen smplify “sys_batch_size” Erro>

**DPGEN Version 0.10.0**

Run according to the simplify case template:
![image](https://user-images.githubusercontent.com/98146358/150623416-6ab79b47-2eb0-4310-9f09-ec02991f137f.png)
Errors are reported as follows:
![image](https://user-images.githubusercontent.com/98146358/150623432-325f1e93-a18e-4a75-8309-da8d442029f2.png)

Run after removing parameter "sys_batch_size":
![image](https://user-images.githubusercontent.com/98146358/150623466-96aa886a-4006-4e3f-bf02-adc65cf9757a.png)
Errors are reported as follows:
![image](https://user-images.githubusercontent.com/98146358/150623482-d01c8cc7-cf93-41cf-af5c-1d65bb869629.png)

The simplify examlpe param.json has no 'sys_configs'

**Comment by njzjz** [comment]
You should set it to
```json
"sys_batch_size": []
```

**Comment by AnguseZhang** [comment]
Since t
