### ISSUE TITLE
[Parameters] improper training parameters in the input file of dpgen examples

### ISSUE THREAD

**Issue by liupf16** [deepmodeling/dpgen#637]
**Summary**

The latest version of dpgen has integrated deepmd 2.x, however the example input parameters do not change accordingly .

**Summary**

The main issues lies in the trainning section of param_CH4_deepmd-kit-2.0.1.json in the path dpgen/examples/run/dp2.x-lammps-vasp/ 

**Detailed Description**

the latest training parameters  is as follows（abolishing the old key stop_batch ）：
"training_data": {
            "systems": [],
            "set_prefix":"set",
            "batch_size":"auto"
            },
 "numb_steps": 1000000,

**Comment by LiangWenshuo1118** [comment]
Your suggestion has been adopted. See the devel branch.
