### ISSUE TITLE
[Feature Request] Machine example

### ISSUE THREAD

**Issue by dingzhaohan** [deepmodeling/dpgen#639]
**Summary**

**Machine Format**

Hi~I was confused about machine parameters: "train_command", "python_path", dict train["command"]. Could u provide a breif introduction about that or refact parsing code?

**Comment by njzjz** [comment]
I think `python_path` has been already deprecated. Examples should be updated.

**Comment by njzjz** [comment]
#762 has removed `python_path` in examples.
