### ISSUE TITLE
IndexError: list index out of range in dpgen init_bulk

### ISSUE THREAD

**Issue by PKUfjh** [deepmodeling/dpgen#647]
When I run dpgen init_bulk, I found out the following IndexError:

File "/rhome/dhileept/.local/lib/python3.9/site-packages/dpgen/data/gen.py", line 176, in poscar_scale
if 'D' == lines[7][0] or 'd' == lines[7][0]:
IndexError: list index out of range

DPGEN 0.10.3
Platform: Lebesgue DPGEN image

**INCAR_fullerene.rlx**
PREC=A
ENCUT=400
ISYM=0
ALGO=Fast
EDIFF=1.000000e-06
LREAL=False
NPAR=4
KPAR=1
NELM=120
NELMIN=4
ISIF=2
ISMEAR=0
SIGMA=0.20000
IBRION=2
NSW=50
LWAVE=F
LCHARG=F
PSTRESS=0
KSPACING=0.500000
KGAMMA=.FALSE.

**INCAR_fullerene.md**
PREC=A
ENCUT=400
ISYM=0
ALGO=Fast
EDIFF=1.000000e-06
LREAL=False
NPAR=4
KPAR=1
NELM=120
NELMIN=4
ISIF=2
ISMEAR=0
SIGMA=0.20000
IBRION=0
POTIM=0.5
NSW=10
LWAVE=F
LCHARG=F
PSTRESS=0
KSPACING=0.500000
KGAMMA=.FALSE.

**C60.POSCAR**
C240
1.0
14.023496 0.000000 0.000000
0.000000 14.023496 0.000000
0.000000 0.000000 14.023496
C
240
direct
0.551807 0.185443 0.164208 C
0.551807 0.185443 0.835793 C
0.783635 0.416276 0.101528 C
0.164208 0.448193 0.814558 C
0.164208 0.448193 0.185443 C
0.283635 0.083724 0.101528 C
0.814558 0.335792 0.051807 C
0.416276 0.101528 0.216365 C
0.500000 0.050028 0.249030 C
0.398472 0.216365 0.083724 C
0.814558 0.335792 0.948193 C
0.101528 0.283635 0.916276 C
0.250970 0.000000 0.050028 C
0.835793 0.448193 0.814558 C
0.314557 0.164208 0.948193 C
0.685442 0.164208 0.948193 C
0.916276 0.398472 0.783635 C
0.185443 0.335792 0.948193 C
0.314557 0.164208 0.051807 C
0.448193 0.185443 0.164208 C
0.398472 0.216365 0.916276 C
0.664207 0.051807 0.814558 C
0.749031 0.000000 0.949971 C
0.601528 0.216365 0.916276 C
0.216365 0.416276 0.898472 C
0.685442 0.164208 0.051807 C
0.948193 0.314557 0.164208 C
0.000000 0.449972 0.750969 C
0.083724 0.398472 0.783635 C
0.185443 0.335792 0.051807 C
0.416276 0.101528 0.783635 C
0.716365 0.083724 0.101528 C
0.583724 0.101528 0.783635 C
0.500000 0.050028 0.750969 C
0.216365 0.416276 0.101528 C
0.948193 0.314557 0.835793 C
0.449972 0.249030 0.000000 C
0.583724 0.101528 0.216365 C
0.083724 0.398472 0.216365 C
0.601528 0.216365 0.083724 C
0.448193 0.185443 0.835793 C
0.916276 0.398472 0.216365 C
0.000000 0.449972 0.249030 C
0.783635 0.416276 0.898472 C
0.749031 0.000000 0.050028 C
0.898472 0.283635 0.916276 C
0.835793 0.448193 0.185443 C
0.664207 0.051807 0.185443 C
0.101528 0.283635 0.083724 C
0.250970 0.000000 0.949971 C
0.949971 0.250970 0.000000 C
0.051807 0.314557 0.164208 C
0.335792 0.051807 0.185443 C
0.283635 0.083724 0.898472 C
0.898472 0.283635 0.083724 C
0.335792 0.051807 0.814558 C
0.716365 0.083724 0.898472 C
0.050028 0.250970 0.000000 C
0.051807 0.314557 0.835793 C
0.550029 0.249030 0.000000 C
0.551807 0.685442 0.664207 C
0.551807 0.685442 0.335792 C
0.783635 0.916276 0.601528 C
0.164208 0.948193 0.314557 C
0.164208 0.948193 0.685442 C
0.283635 0.583724 0.601528 C
0.814558 0.835793 0.551807 C
0.416276 0.601528 0.716365 C
0.500000 0.550029 0.749031 C
0.398472 0.716365 0.583724 C
0.814558 0.835793 0.448193 C
0.101528 0.783635 0.416276 C
0.250970 0.500000 0.550029 C
0.835793 0.948193 0.314557 C
0.314557 0.664207 0.448193 C
0.685442 0.664207 0.448193 C
0.916276 0.898472 0.283635 C
0.185443 0.835793 0.448193 C
0.314557 0.664207 0.551807 C
0.448193 0.685442 0.664207 C
0.398472 0.716365 0.416276 C
0.664207 0.551807 0.314557 C
0.749031 0.500000 0.449972 C
0.601528 0.716365 0.416276 C
0.216365 0.916276 0.398472 C
0.685442 0.664207 0.551807 C
0.948193 0.814558 0.664207 C
0.000000 0.949971 0.250970 C
0.083724 0.898472 0.283635 C
0.185443 0.835793 0.551807 C
0.416276 0.601528 0.283635 C
0.716365 0.583724 0.601528 C
0.583724 0.601528 0.283635 C
0.500000 0.550029 0.250970 C
0.216365 0.916276 0.601528 C
0.948193 0.814558 0.335792 C
0.449972 0.749031 0.500000 C
0.583724 0.601528 0.716365 C
0.083724 0.898472 0.716365 C
0.601528 0.716365 0.583724 C
0.448193 0.685442 0.335792 C
0.916276 0.898472 0.716365 C
0.000000 0.949971 0.749031 C
0.783635 0.916276 0.398472 C
0.749031 0.500000 0.550029 C
0.898472 0.783635 0.416276 C
0.835793 0.948193 0.685442 C
0.664207 0.551807 0.685442 C
0.101528 0.783635 0.583724 C
0.250970 0.500000 0.449972 C
0.949971 0.750969 0.500000 C
0.051807 0.814558 0.664207 C
0.335792 0.551807 0.685442 C
0.283635 0.583724 0.398472 C
0.898472 0.783635 0.583724 C
0.335792 0.551807 0.314557 C
0.716365 0.583724 0.398472 C
0.050028 0.750969 0.500000 C
0.051807 0.814558 0.335792 C
0.550029 0.749031 0.500000 C
0.051807 0.185443 0.664207 C
0.051807 0.185443 0.335792 C
0.283635 0.416276 0.601528 C
0.664207 0.448193 0.314557 C
0.664207 0.448193 0.685442 C
0.783635 0.083724 0.601528 C
0.314557 0.335792 0.551807 C
0.916276 0.101528 0.716365 C
0.000000 0.050028 0.749031 C
0.898472 0.216365 0.583724 C
0.314557 0.335792 0.448193 C
0.601528 0.283635 0.416276 C
0.750969 0.000000 0.550029 C
0.335792 0.448193 0.314557 C
0.814558 0.164208 0.448193 C
0.185443 0.164208 0.448193 C
0.416276 0.398472 0.283635 C
0.685442 0.335792 0.448193 C
0.814558 0.164208 0.551807 C
0.948193 0.185443 0.664207 C
0.898472 0.216365 0.416276 C
0.164208 0.051807 0.314557 C
0.249030 0.000000 0.449972 C
0.101528 0.216365 0.416276 C
0.716365 0.416276 0.398472 C
0.185443 0.164208 0.551807 C
0.448193 0.314557 0.664207 C
0.500000 0.449972 0.250970 C
0.583724 0.398472 0.283635 C
0.685442 0.335792 0.551807 C
0.916276 0.101528 0.283635 C
0.216365 0.083724 0.601528 C
0.083724 0.101528 0.283635 C
0.000000 0.050028 0.250970 C
0.716365 0.416276 0.601528 C
0.448193 0.314557 0.335792 C
0.949971 0.249030 0.500000 C
0.083724 0.101528 0.716365 C
0.583724 0.398472 0.716365 C
0.101528 0.216365 0.583724 C
0.948193 0.185443 0.335792 C
0.416276 0.398472 0.716365 C
0.500000 0.449972 0.749031 C
0.283635 0.416276 0.398472 C
0.249030 0.000000 0.550029 C
0.398472 0.283635 0.416276 C
0.335792 0.448193 0.685442 C
0.164208 0.051807 0.685442 C
0.601528 0.283635 0.583724 C
0.750969 0.000000 0.449972 C
0.449972 0.250970 0.500000 C
0.551807 0.314557 0.664207 C
0.835793 0.051807 0.685442 C
0.783635 0.083724 0.398472 C
0.398472 0.283635 0.583724 C
0.835793 0.051807 0.314557 C
0.216365 0.083724 0.398472 C
0.550029 0.250970 0.500000 C
0.551807 0.314557 0.335792 C
0.050028 0.249030 0.500000 C
0.051807 0.685442 0.164208 C
0.051807 0.685442 0.835793 C
0.283635 0.916276 0.101528 C
0.664207 0.948193 0.814558 C
0.664207 0.948193 0.185443 C
0.783635 0.583724 0.101528 C
0.314557 0.835793 0.051807 C
0.916276 0.601528 0.216365 C
0.000000 0.550029 0.249030 C
0.898472 0.716365 0.083724 C
0.314557 0.835793 0.948193 C
0.601528 0.783635 0.916276 C
0.750969 0.500000 0.050028 C
0.335792 0.948193 0.814558 C
0.814558 0.664207 0.948193 C
0.185443 0.664207 0.948193 C
0.416276 0.898472 0.783635 C
0.685442 0.835793 0.948193 C
0.814558 0.664207 0.051807 C
0.948193 0.685442 0.164208 C
0.898472 0.716365 0.916276 C
0.164208 0.551807 0.814558 C
0.249030 0.500000 0.949971 C
0.101528 0.716365 0.916276 C
0.716365 0.916276 0.898472 C
0.185443 0.664207 0.051807 C
0.448193 0.814558 0.164208 C
0.500000 0.949971 0.750969 C
0.583724 0.898472 0.783635 C
0.685442 0.835793 0.051807 C
0.916276 0.601528 0.783635 C
0.216365 0.583724 0.101528 C
0.083724 0.601528 0.783635 C
0.000000 0.550029 0.750969 C
0.716365 0.916276 0.101528 C
0.448193 0.814558 0.835793 C
0.949971 0.749031 0.000000 C
0.083724 0.601528 0.216365 C
0.583724 0.898472 0.216365 C
0.101528 0.716365 0.083724 C
0.948193 0.685442 0.835793 C
0.416276 0.898472 0.216365 C
0.500000 0.949971 0.249030 C
0.283635 0.916276 0.898472 C
0.249030 0.500000 0.050028 C
0.398472 0.783635 0.916276 C
0.335792 0.948193 0.185443 C
0.164208 0.551807 0.185443 C
0.601528 0.783635 0.083724 C
0.750969 0.500000 0.949971 C
0.449972 0.750969 0.000000 C
0.551807 0.814558 0.164208 C
0.835793 0.551807 0.185443 C
0.783635 0.583724 0.898472 C
0.398472 0.783635 0.083724 C
0.835793 0.551807 0.814558 C
0.216365 0.583724 0.898472 C
0.550029 0.750969 0.000000 C
0.551807 0.814558 0.835793 C
0.050028 0.749031 0.000000 C

**POTCAR_C**
download from official website

**init.json file**
{
    "stages":           [1,2,3,4],
    "cell_type":	"fcc",
    "super_cell":	[1, 1, 1],
    "elements":		["C"],
    "from_poscar":	true,
    "from_poscar_path":	"./C60.POSCAR",
    "potcars":		["./POTCAR_C"],
    "relax_incar": 	"./INCAR_fullerene.rlx",
    "md_incar" : 	"./INCAR_fullerene.md",
    "scale":		[1.00],
    "skip_relax":	false,
    "pert_numb":	30,
    "md_nstep" : 	10,
    "pert_box":		0.03,
    "pert_atom":	0.01,
    "deepgen_templ":	"../generator/template/",
    "coll_ndata":	5000,
    "_comment":		"that's all"
}

**machine.json file** (neglect the train and model_devi section)
{
  "api_version": "1.0",
  "deepmd_version": "2.0.1",
  "fp":
    [{
      "command": "mpirun -n 16 vasp_std",
      "machine": {
        "batch_type": "Lebesgue",
        "context_type": "LebesgueContext",
        "local_root" : "./",
        "remote_profile":{
          "email": "*******",
          "password": "********",
          "program_id": 717,
            "keep_backup":true,
            "input_data":{
              "job_type": "indicate",
              "log_file": "task*/fp.log",
              "grouped":true,
              "job_name": "dpgen_fp_job",
              "disk_size": 300,
              "checkpoint_files": "sync_files",
              "checkpoint_time":15,
              "scass_type":"c32_m128_cpu",
              "platform": "ali",
              "image_name":"LBG_vasp-vtst-5-4-4_v1",
              "on_demand":1
            }
        }
      },
      "resources": {
        "group_size": 50,
        "local_root":"./",
        "source_list": ["/opt/intel/oneapi/setvars.sh"]
      }
    }
  ]
}

**Expected Behavior**

**Actual Behavior**
In 00.place_ele directory, POSCAR is generated the same with the original C60.POSCAR.
But **CONTCAR is empty**. The submitted job is terminated and generate this IndexError.

**Steps to Reproduce**
dpgen init_bulk init.json machine.json

**Additional information**
the system to use running dpgen has 240 atoms, it has this error.
When I use the same INCAR and POTCAR, but change the number of atoms to less than 120, it does not has this error.

**Comment by AnguseZhang** [comment]
Can you post your original `POSCAR`, and `CONTCAR` generated in `00.place_ele`?

**Comment by PKUfjh** [comment]
Found the problem, it is the memory issue. One should set unlimit -s unlimited in the source lists.
