### ISSUE TITLE
[BUG] PWSCF input file does not specify "occupations"

### ISSUE THREAD

**Issue by mkphuthi** [deepmodeling/dpgen#672]
**Summary**

To use smearing in pw.x you need to specify the input parameter `occupations='smearing'` in the input file otherwise smearing will not be used even if you specify "degauss" and "smearing". This can fail silently producing converged but wrong results for metals.

**DPGEN Version and Platform**

DPGEN version: 0.9.2
OS: CentOS 7.9

**Expected Behavior**

Create pw.x input file with smearing turned on

**Actual Behavior**

Does not add the `occupations='smearing'` parameter when smearing is necessary

**Steps to Reproduce**

Use dpgen run with following input for fp section in the dpgen run config using PWSCF:

  ```
  "fp_style": "pwscf",
  "shuffle_poscar": true,
  "fp_task_max": 10,
  "fp_task_min": 1,
  "fp_pp_path": "./",
  "fp_pp_files": ["my_pseudopotential"],
  "fp_params": {
    "ecut": 100,
    "ediff": 1e-6,
    "kspacing": 0.2,
    "sigma": 0.02,
    "smearing": "mp"
```
**Further Information, Files, and Links**

I can submit a PR for this if you'd like. The fix would be adding "occupations=smearing" if sigma is specified in the run config json

**Comment by AnguseZhang** [comment]
Thanks for your report !  Also thanks for the wish to contribute. We definitely welcome you to submit the PR if you would.

On the other hand,  DP-GEN also allows users to designate the parameters for QE inputs according to their needs.

To achieve this, you can replace the key "fp_params"  with "user_fp_params", and specify the parameters you need. 

Could you please have a try and see whether it works? 

Yuzhi

**Comment by mkphuthi** [comment]
I was not familiar with the user_fp_params and it works fine. This is definitely easier to use and with more control. Thanks.

**Comment by AnguseZhang** [comment]
Since this problem has been solved, I'll close this issue. We'll try to furnish the documents with @HuangJiameng
