### ISSUE TITLE
[BUG] boto3 raise an exception if not configure aws region.

### ISSUE THREAD

**Issue by KZHIWEI** [deepmodeling/dpgen#674]
**Summary**

/dpgen/dispatcher/AWS.py: line:8

try:
    import boto3
except ModuleNotFoundError:
    pass
else:
    batch_client = boto3.client('batch')

**DPGEN Version and Platform**

all version

**Job submission and computing cluster configuration**

**Expected Behavior**

ignore the error if user not config boto3 region and not using AWS.

**Actual Behavior**

If user install boto3 but not config region, boto3 will  throw an exception. 

![middle_img_v2_a6733bf7-f6d2-4c7d-a702-26e2281745eg](https://user-images.githubusercontent.com/43613336/158776912-bba80c2b-735f-4f4a-8489-07f298263638.png)

**Steps to Reproduce**

use a plain instance install boto3 (pip install boto3) and run dpgen

**Further Information, Files, and Links**

**Comment by cherushui** [comment]
Hello zhiwei @KZHIWEI ,
I have met this error info.
A temporary solution is design a region by environment variable before excute dpgen.
e.g.:

`export AWS_DEFAULT_REGION=us-west-2
`
