### ISSUE TITLE
After installed the dpgen, an error with 'pip install --user .'

### ISSUE THREAD

**Issue by Jeremy1189** [deepmodeling/dpgen#676]
After installed the dpgen, an error with 'pip install --user .' as follows, 

(deepmd) [biaoxu4@hpclogin02 dpgen]$ pip install --user .
Processing /gpfs1/home/biaoxu4/dpgen
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
ERROR: Could not install packages due to an OSError: [('/gpfs1/home/biaoxu4/dpgen/tests/database/data.tar.gz', '/tmp/pip-req-build-vjko_gd7/tests/database/data.tar.gz', "[Errno 11] Resource temporarily unavailable: '/gpfs1/home/biaoxu4/dpgen/tests/database/data.tar.gz' -> '/tmp/pip-req-build-vjko_gd7/tests/database/data.tar.gz'")]

**Comment by Jeremy1189** [comment]
you can use the following command :
pip install --user biaoxu4(your username)

and then run 

pip install -- user .
it  works.
![image](https://user-images.githubusercontent.com/85468234/159145662-fc8277e4-8702-4105-85df-ddefd9671d50.png)

**Comment by njzjz** [comment]
I close this issue as the latest pip no longer copies the source code to `/tmp`.
