### ISSUE TITLE
Confused by keyword "task_per_node" in fp, suggest change to "CPU_per_jobs"

### ISSUE THREAD

**Issue by lalaheihaihei** [deepmodeling/dpgen#681]
In 02.fp step, the "task_per_node" means "Number of CPU cores required per jobs". It is very confusing, because I think it is the number of jobs per node at the beginning.

Actually, when I set it to 8, it becomes "mpiexec.hydra -n 8 vasp". So, I think it's better to change it to avoid comfusing.

**Comment by wanghan-iapcm** [comment]
This key word should be provided by deepmodeling/dpdispatcher.  We borrowed the name from the slurm batching system.
