### ISSUE TITLE
[BUG] an error occured when running dp-gen about gromacs/gaussian:RuntimeError: cannot find upload file em.tpr

### ISSUE THREAD

**Issue by Cynthia0807-learn** [deepmodeling/dpgen#692]
**Summary**

When I run DP-GEN about gromacs/gaussian,an error occured:
```
Traceback (most recent call last):
  File "/home/wyq/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/home/wyq/.local/lib/python3.8/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/home/wyq/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 3083, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/home/wyq/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 3059, in run_iter
    run_model_devi (ii, jdata, mdata)
  File "/home/wyq/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 1305, in run_model_devi
    dispatcher.run_jobs(mdata['model_devi_resources'],
  File "/home/wyq/.local/lib/python3.8/site-packages/dpgen/dispatcher/Dispatcher.py", line 84, in run_jobs
    job_handler = self.submit_jobs(resources,
  File "/home/wyq/.local/lib/python3.8/site-packages/dpgen/dispatcher/Dispatcher.py", line 146, in submit_jobs
    rjob['context'].upload(cur_chunk,
  File "/home/wyq/.local/lib/python3.8/site-packages/dpgen/dispatcher/LocalContext.py", line 80, in upload
    raise RuntimeError('cannot find upload file ' + os.path.join(local_job, jj))
RuntimeError: cannot find upload file /home/wyq/Desktop/gmx-dp/dpgen_test/iter.000000/01.model_devi/task.000.000000/em.tpr
```
em.tpr is outfile,why cannot find upload file?
**DPGEN Version and Platform**

dpgen:0.13.0
**Job submission and computing cluster configuration**

**Expected Behavior**

I want to test the system h2o with DP-GEN about gromacs/gaussian
**Actual Behavior**

**Steps to Reproduce**

[test.zip](https://github.com/deepmodeling/dpgen/files/8376679/test.zip)
My command: nohup dpgen param.json machine.json &
**Further Information, Files, and Links**

**Comment by Ericwang6** [comment]
Hi, the problem is due to in your directories specified by `sys_configs_prefix` and `sys_configs` does not have file named `em.tpr`. You should run `gmx -f md.mdp -c h2o.gro -p h2o.top -o em.tpr` first. And in `param.json`, **I notice some settings are not configured  properly**. The correct should be as flows:
```json
"gromacs_settings": {
    "mdp_filename": "md.mdp",
    "topol_filename": "h2o.top",
    "conf_filename": "h2o.gro",
    "index_filename": "index.raw",
    "ref_filename": "em.tpr",
    "type_filename": "type.raw",
    "deffnm":"h2o",
    "maxwarn": 4,
    "model_devi_script": "model_devi.py",
    "traj_filename": "deepmd_traj.gro",
    "group_name": "Water"
  },
```
`ref_filename` and `type_filename` should be set explicitly. `group_name` should be set to `"Water"` instead of `"Other"` since you are doing simulation on water (in this system, gromacs cannot find a group named "Other").

Besides, I notice that in your `h2o.top` and `h2o.gro`. Oxygen and hydrogen are named to `OW` and `HW` respectively, but in your deepmd training, they are set to `O` and `H` (in `type_map` argument). This will lead to an error. So you should make them consistent.

If you have further problems, feel free to contact me.

**Comment by Ericwang6** [comment]
P.S. If you chose to change `type_map` argument, please set them to `Ow` and `Hw`. This is because `dpdata` will translate `["OW", "HW"]` to `["Ow", "Hw"]`

**Comment by Cynthia0807-learn** [comment]
> Hi, the problem is due to in your directories specified by `sys_configs_prefix` and `sys_configs` does not have file named `em.tpr`. You should run `gmx -f md.mdp -c h2o.gro -p h2o.top -o em.tpr` first. And in `param.json`, **I notice some settings are not configured properly**. The correct should be as flows:
> 
> ```json
> "gromacs_settings": {
>     "mdp_filename": "md.mdp",
>     "topol_filename": "h2o.top",
>     "conf_filename": "h2o.gro",
>     "index_filename": "index.raw",
>     "ref_filename": "em.tpr",
>     "type_filename": "type.raw",
>     "deffnm":"h2o",
>     "maxwarn": 4,
>     "model_devi_script": "model_devi.py",
>     "traj_filename": "deepmd_traj.gro",
>     "group_name": "Water"
>   },
> ```
> 
> `ref_filename` and `type_filename` should be set explicitly. `group_name` should be set to `"Water"` instead of `"Other"` since you are doing simulation on water (in this system, gromacs cannot find a group named "Other").
> 
> Besides, I notice that in your `h2o.top` and `h2o.gro`. Oxygen and hydrogen are named to `OW` and `HW` respectively, but in your deepmd training, they are set to `O` and `H` (in `type_map` argument). This will lead to an error. So you should make them consistent.
> 
> If you have further problems, feel free to contact me.

@Ericwang6 Thanks for your help.Now it works normally.I run gromacs/dp without dpgen before，and it worked fine.
Besides, What  is the argument `group_name`  based on? This is not explained in the manual of `DP-GEN`.Finally,I hope something about gromacs will be added in the manual or tutorial of the DP-GEN.

**Comment by HuangJiameng** [comment]
@Ericwang6
