### ISSUE TITLE
[BUG] _"dpgen autotest make relaxation.json" for deepmd

### ISSUE THREAD

**Issue by xuekuiwin** [deepmodeling/dpgen#697]
**Summary**

When dpgen is run (dpgen autotest make relaxation.json), it forces a change to the in.lammps  parameter "pair_coeff   * *", and delete "**"
**DPGEN Version and Platform**
DPGEN :0.10.3; platform: pbs

**Job submission and computing cluster configuration**

**Expected Behavior**
add  "**"

**Actual Behavior**

you can see dir: "confs/std-hcp/relaxation/in.lammps" and "lammps_input/in.lammps"
**Steps to Reproduce**

relaxation.json:
{
    "structures":         ["confs/std-*"],
    "interaction": {
            "type":        "deepmd",
            "model":       "frozen_model.pb",
            "in_lammps":   "lammps_input/in.lammps",
            "type_map":   {"Ti": 0}
        },
    "relaxation": {
            "cal_type":    "relaxation",
            "cal_setting":{"relax_pos":       true,
                           "relax_shape":     true,
                           "relax_vol":       true,
                           "etol": 1e-12,
                           "ftol": 1e-6,
                           "maxiter": 5000,
                           "maximal": 500000}
        }
}

in.lammps:
clear
units             metal
dimension         3
boundary          p p p
atom_style        atomic
box               tilt large
read_data         conf.lmp
mass              1 47.88
neigh_modify      every 1 delay 0 check no
pair_style        deepmd frozen_model.pb
pair_coeff        * *
compute           mype all pe
thermo            100
thermo_style      custom step pe pxx pyy pzz pxy pxz pyz lx ly lz vol c_mype
dump              1 all custom 100 dump.relax id type xs ys zs fx fy fz
min_style         cg
fix               1 all box/relax iso 0.0
minimize          1.000000e-12 1.000000e-06 5000 500000
fix               1 all box/relax aniso 0.0
minimize          1.000000e-12 1.000000e-06 5000 500000
variable          N equal count(all)
variable          V equal vol
variable          E equal "c_mype"
variable          tmplx equal lx
variable          tmply equal ly
variable          Pxx equal pxx
variable          Pyy equal pyy
variable          Pzz equal pzz
variable          Pxy equal pxy
variable          Pxz equal pxz
variable          Pyz equal pyz
variable          Epa equal ${E}/${N}
variable          Vpa equal ${V}/${N}
variable          AA equal (${tmplx}*${tmply})
print "All done"
print "Total number of atoms = ${N}"
print "Final energy per atoms = ${Epa}"
print "Final volume per atoms = ${Vpa}"
print "Final Base area = ${AA}"
print "Final Stress (xx yy zz xy xz yz) = ${Pxx} ${Pyy} ${Pzz} ${Pxy} ${Pxz} ${Pyz}"
**Further Information, Files, and Links**

**Comment by AnguseZhang** [comment]
Thanks for report. You can test https://github.com/deepmodeling/dpgen/pull/698/files @xuekuiwin and see whether it works.

**Comment by wanghan-iapcm** [comment]
Will be fixed by #696 #698

**Comment by xuekuiwin** [comment]
ok, thanks!
