### ISSUE TITLE
autotest proprites

### ISSUE THREAD

**Issue by 13yong** [deepmodeling/dpgen#702]
Hello developer, recently I meet an error about dpgen autotest. When I use script "dpgen autotest run param.json machine.json", the screeen tell me that "Submit job via 1 processes". And then there no more information. Before I met the error, I had used my machine.json finished relaxation processses. In my machine.json, I used api_version=1.0. So can you help me to solve the question? Thank you very much.
param.json:
{
"structures":["./"]
"interaction":{
  "type": "deepmd",
  "model": "frozen_model.pb",
   "deepmd_version": "2.0.1",
   "type_map": {"C": 0, "H":1}
 },
"properties": [
    {
     "type": "elastic",
     "norm_deform": 2e-2,
     "shear_deform": 3e-2
     }
 ]
}

**Comment by 13yong** [comment]
[](url)

**Comment by AnguseZhang** [comment]
Hi, is there update for this problem?  If not, you can provide all files related (including the model, jsons for relaxation and properties )

**Comment by 13yong** [comment]
> Hi, is there update for this problem? If not, you can provide all files related (including the model, jsons for relaxation and properties, POSCARs, etc) to let this problem be reproduced.

Thank you for your attention. The test.zip contains **1**. all log files, **2**. all json files, **3**. the DP model for CH4. **4**, POSCAR for CH4. The DP potential got with dpgen run.But I don't know how to updata my output files, if you need I can try it again.  In my opinion, it can not make job file.
[test.zip](https://github.com/deepmodeling/dpgen/files/8633064/test.zip)

**Comment by 13yong** [comment]
> Hi, is there update for this problem? If not, you can provide all files related (including the model, jsons for relaxation and properties, POSCARs, etc) to let this problem be reproduced.

I'm sorry to tell you  When I use machine.json of new version(api > 1.0) to submit eos task, it also can't work. So I guess new machine.json has conflict with autotest properties.

**Comment by 13yong** [comment]
> 



> Hi, I have completed the process of autotest on my server with the data you provided. In my machine.json, I also used api_version=1.0. So maybe you should check your machine.json carefully?

Firstly, thank you for your attention. When we set api_version=1.0 that means the old dpdescriptor was used. However, it is said that the old dpdescriptor is no longer maintained, so we are trying to use api_version>1.0. Note that the old dpdesciptor still can be used now. If you have good idea you can connect with me. The best wishes to you.

**Comment by HuangJiameng** [comment]
> Note that the old dpdesciptor still can be used now.
I think you mean dpdispatcher. I am confused about whether you want to use the old dpdispatcher, or you are trying the new one? Maybe this doc can help you. [https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/getting-started.html](url)

**Comment by HuangJiameng** [comment]
> When we set api_version=1.0 that means the old dpdescriptor was used.

In fact, when we set api_version=1.0 that means dpdescriptor(the new one) was used. I can't get your point.

**Comment by njzjz** [comment]
Since it's unclear what's wrong here, I'm going to close the issue.
