### ISSUE TITLE
[BUG] dpgen0.10.2 ERROR: Incorrect args for pair coefficients (src/input.cpp:1713)  Last command: pair_coeff

### ISSUE THREAD

**Issue by baihuyu12** [deepmodeling/dpgen#707]
My machine is offline, so I use dpgen-0.10.2.sh to install, I found the reason of error is "pair_coeff " should be corrected by "pair_coeff **".
![image](https://user-images.githubusercontent.com/57975158/164478685-bc2b814a-b1b9-4cc5-a190-2c24a91367cd.png)

https://github.com/deepmodeling/dpgen/discussions/588
![image](https://user-images.githubusercontent.com/57975158/164478262-1cdeb76a-e5e1-4c4f-8f20-3fcfd63569bb.png)

But I can't find the dpgen/generator/lib/lammps.py in my directory.

How can I do?

![image](https://user-images.githubusercontent.com/57975158/164478460-62b889ac-59fe-4a60-998f-792f07c9e58d.png)

**Comment by njzjz** [comment]
```sh
find . -name lammps.py
```
