### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by Gauyer** [deepmodeling/dpgen#708]
Description
------------
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/deepgen/bin/dpgen", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/envs/deepgen/lib/python3.9/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/home/ubuntu/miniconda3/envs/deepgen/lib/python3.9/site-packages/dpgen/generator/run.py", line 2410, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/home/ubuntu/miniconda3/envs/deepgen/lib/python3.9/site-packages/dpgen/generator/run.py", line 2384, in run_iter
    mdata = decide_model_devi_machine(mdata)
  File "/home/ubuntu/miniconda3/envs/deepgen/lib/python3.9/site-packages/dpgen/remote/decide_machine.py", line 148, in decide_model_devi_machine
    mdata["model_devi_group_size"] = mdata["model_devi"][0]["group_size"]
KeyError: 'group_size'

Can anyone help me?
the machine.json is below
{
  "api_version": "1.0",
  "deepmd_version": "2.1.0",
  "train" :[
    {
      "command": "dp",
      "machine": {
        "batch": "slurm",
        "context_type": "local",
        "local_root" : "./",
        "work_path": "/home/ubuntu/PdSe2DPGEN"
      },
      "resources": {
        "number_node": 1,
        "local_root":"./",
        "cpu_per_node": 4,
        "gpu_per_node": 1,
        "queue_name": "compute",
        "group_size": 1,
        "custom_flags":[],
        "source_list": [" /home/ubuntu/PdSe2DPGEN/deepmd.sh"]
      }
    }],
  "model_devi": 
    [{
      "command": "/home/ubuntu/miniconda3/envs/deepmd/bin/lmp",
      "machine": {
        "batch": "slurm",
        "context_type": "local",
        "local_root" : "./",
        "work_path": "/home/ubuntu/PdSe2DPGEN"
      },
      "resources": {
        "number_node": 1,
        "local_root":"./",
        "cpu_per_node": 0,
        "gpu_per_node": 1,
        "queue_name": "compute",
        "group_size": 10,
        "custom_flags":[],
        "source_list": ["/home/ubuntu/PdSe2DPGEN/deepmd.sh"]
      }
    }],
  "fp":
    [{
      "command": "srun -n 52 vasp_std",
      "machine": {
        "batch": "slurm",
        "context_type": "local",
        "local_root" : "./",
        "work_path": "/home/ubuntu/PdSe2DPGEN"
      },
      "resources": {
        "number_node": 1,
        "cpu_per_node": 52,
        "queue_name": "compute",
        "group_size": 6,
        "custom_flags":["#SBATCH -n 52"],
        "local_root":"./",

        "module_list": []
      }
    }
  ]
}

**Comment by AnguseZhang** [comment]
What's your DP-GEN version?  It seems that it's not the latest version. You're suggested update DP-GEN to `0.10.4`

**Comment by Gauyer** [comment]
> What's your DP-GEN version? It seems that it's not the latest version. You're suggested update DP-GEN to `0.10.4`

0.9.2 from conda install , it seems that the latest version in conda can't be update

**Comment by AnguseZhang** [comment]
> > What's your DP-GEN version? It seems that it's not the latest version. You're suggested update DP-GEN to `0.10.4`
> 
> 0.9.2 from conda install , it seems that the latest version in conda can't be update

You can install DP-GEN from source code, which is not difficult. Updating DP-GEN in `conda` and `pip` source will be another issue.

**Comment by Gauyer** [comment]
> > > What's your DP-GEN version? It seems that it's not the latest version. You're suggested update DP-GEN to `0.10.4`
> > 
> > 
> > 0.9.2 from conda install , it seems that the latest version in conda can't be update
> 
> You can install DP-GEN from source code, which is not difficult. Updating DP-GEN in `conda` and `pip` source will be fixed in another issue.

I use the git clone install , while another error encountered during the use in dpgen
![5094fcb85e8c7317466f342a9b622ff](https://user-images.githubusercontent.com/55430525/164976682-4bb335cc-b840-4ac0-a54c-67943a820e0e.png)

**Comment by Gauyer** [comment]
> > > > What's your DP-GEN version? It seems that it's not the latest version. You're suggested update DP-GEN to `0.10.4`
> > > 
> > > 
> > > 0.9.2 from conda install , it seems that the latest version in conda can't be update
> > 
> > 
> > You can install DP-GEN from source code, which is not difficult. Updating DP-GEN in `conda` and `pip` source will be fixed in another issue.
> 
> I use the git clone install , while another error encountered during the use in dpgen ![5094fcb85e8c7317466f342a9b622ff](https://user-images.githubusercontent.com/55430525/164976682-4bb335cc-b840-4ac0-a54c-67943a820e0e.png)

which make the mistakes of runing the dpgen run pa. ma.
