### ISSUE TITLE
Job scheduling system

### ISSUE THREAD

**Issue by 13yong** [deepmodeling/dpgen#715]
Hello developer, I have a question about job scheduling system. I submit a job with 16 cpu cores, but in fact it runs with only 1 core. My dpgen version is 0.10.3.
![0285c10e19be94db63a8bff1d0485e0](https://user-images.githubusercontent.com/90954282/165032679-a39af920-6872-4e93-9fa3-35e4c3243886.png)
![a12ce32d49a1883c5c7ad8787d6be60](https://user-images.githubusercontent.com/90954282/165032705-5e2b6d50-154b-4574-880a-b9c02416f4fb.png)

**Comment by AnguseZhang** [comment]
1. "#SBATCH -l select=2:ncpus:16:ngpus=0",  Why do you specify "select=2"? Do you want to require two nodes ?
2. How did you find "There runs with only 1 core."? 
3. What's the correct script which can launch 16 cores on your computing cluster? Did you contact the cluster admin for help ?

**Comment by 13yong** [comment]
> 

1.Specify "select = 2" in order to use 2 nodes.
2. When I use command "qnodes node03", as we can see the last picture. So I think a core is called to run the task.
3. The correct script launch 16 cores on my computing cluster like follow picture. 
![image](https://user-images.githubusercontent.com/90954282/165046292-2710cc71-49d9-4e67-80c6-d9130c6f5ac9.png)

**Comment by wanghan-iapcm** [comment]
> Hello developer, I have a question about job scheduling system. I submit a job with 16 cpu cores, but in fact it runs with only 1 core. My dpgen version is 0.10.3. ![0285c10e19be94db63a8bff1d0485e0](https://user-images.githubusercontent.com/90954282/165032679-a39af920-6872-4e93-9fa3-35e4c3243886.png) ![a12ce32d49a1883c5c7ad8787d6be60](https://user-images.githubusercontent.com/90954282/165032705-5e2b6d50-154b-4574-880a-b9c02416f4fb.png)

Please report issues in plan text. Search engines like goole and bing cannot search within figures. Thanks!

**Comment by 13yong** [comment]
> 
Sorry. Some of the task scripts generated by dpgen are as follows:
***
#PBS -l select=2: ncpus=16 : ngpus=0
#PBS -j  oe
#PBS -q dell
RENOTE_ROOT=/home/m-zc3/work/dpgen_tmp_dir/8054c225943b4d3e87f4f0flaf0828b0065ed2b9
echo 0 > $RENOTE_RO0T/04d1910e9df273335480c7a8c45a98deeade9cOe_flag_if_job_task_fail
test $? -ne 0 &&exit i
{ source /opt/intel/compilers_and_libraries_2019.3.199/linux/bin/compilervars. sh intel64; }
{source /opt/intel/compilers_and_libraries_2019.3.199/1inux/bin/iccvars.sh intel64;}
{source /opt/intel/compilers_and_libraries_2019.3.199/linux/bin/ifortvars.sh intel64; }
{source /opt/intel/compilers_and_libraries_2019.3.199/linux/mkl/bin/mklvars.sh intel64; }
{source /opt/intel/impi/2019.3.199/intel64/bin/mpivars.sh; }
cd $REMOTE_ROOT
cd task.000.000046
test $? -ne 0 && exit 1
if [ ! -f e4de306df0bb792f2b55a74ac7a277e158c580ad_task_tag_finished ] ;then( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log
if test $? -eq 0; then touch e4de3906dfebb792f2b55a74ac7a277e158c589ad_task_tag_finished; else echo 1 > $RENOTE_RO0T/4d1910e9df273335480c7a8c45a98deeade9coe_flag_if_job_task_fail;fi
fi &
wait
***
Checking the use of nodes results in the following:
***
node03
                state = free
                power_state = Running
                np = 32
                properties = dell
                ntype = cluster
                jobs = 0/514423.mgr
                status = opsys=linux , uname=2456 11422 16684,nsessions=6 , nu9, gres=,netload=154811395920, sta4423.mgr
***

**Comment by 13yong** [comment]
> 1. "#SBATCH -l select=2:ncpus:16:ngpus=0",  Why do you specify "select=2"? Do you want to require two nodes ?
> 2. How did you find "There runs with only 1 core."?
> 3. What's the correct script which can launch 16 cores on your computing cluster? Did you contact the cluster admin for help ?
Today I have a try.
change
**
#PBS -l select=2: ncpus=16 : ngpus=0
**
into
**
#PBS -l nodes=1:ppn=16
**
It can run with 16 cores. So I want to know how to auto change in machine.json.
