### ISSUE TITLE
The combination of Two POTCAR meet an error

### ISSUE THREAD

**Issue by Gauyer** [deepmodeling/dpgen#716]
Hi developer , 
when i processing into the fp stage , I meet an error showing below
![1650868970(1)](https://user-images.githubusercontent.com/55430525/165034292-6086f039-c5ae-4ee0-9939-8fdbd3182711.png)

then i check the catalogue of runing of fp 

the fp.log shows below
 running on   52 total cores
 distrk:  each k-point on   52 cores,    1 groups
 distr:  one band on   26 cores,    2 groups
 using from now: INCAR     
 vasp.5.4.4.18Apr17-6-g9f103f2a35 (build Dec 22 2021 14:51:05) complex          
  
 POSCAR found type information on POSCAR  Pd Se
 POSCAR found :  2 types and      72 ions
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       00001494AD5F40B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       0000149C7CC7F0B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       0000150E49A100B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       000014745928D0B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       000014816F1F60B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       0000152ECE2080B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       0000150E0F6580B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       000014EA3CA9F0B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       00001474187870B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       000015358A3E60B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       0000148D80A210B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       00001500DC1810B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       00001488E8A2F0B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       000014ECA4DAC0B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       000014FDD13E30B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       000014CFD98740B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       0000150F47D540B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR
Image              PC                Routine            Line        Source             
vasp_std           00000000015B4F68  Unknown               Unknown  Unknown
vasp_std           00000000015EFE72  Unknown               Unknown  Unknown
vasp_std           00000000015EE8D7  Unknown               Unknown  Unknown
vasp_std           0000000000532B77  Unknown               Unknown  Unknown
vasp_std           00000000013ED5FD  Unknown               Unknown  Unknown
vasp_std           000000000040BA22  Unknown               Unknown  Unknown
libc-2.31.so       0000145B7E8630B3  __libc_start_main     Unknown  Unknown
vasp_std           000000000040B92E  Unknown               Unknown  Unknown
forrtl: severe (59): list-directed I/O syntax error, unit 10, file /home/ubuntu/PdSe2DPGEN/932a80322a887157e480f48cdcd30ac79ecd1fca/task.001.000009/POTCAR

it seems that the dpgen combine two potcar file in a wrong way
part of the combined potcar shows below

0.117833995195E+01  0.112549878728E+01  0.105776389819E+01  0.974970085213E+00  0.877159007428E+00
  0.764615842314E+00  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00
  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00
  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00
  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00
  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00  0.000000000000E+00
  0.000000000000E+00  0.000000000000E+00
 End of Dataset  PAW_PBE Se 06Sep2000                   
   6.00000000000000     
 parameters from PSCTR are:
   VRHFIN =Se: s2p4
   LEXCH  = PE
   EATOM  =   257.1286 eV,   18.8984 Ry
 
there should be another line between first and second potcar file, but the above is not consistent with the cat potcar1 potcar2 > potcar

**Comment by AnguseZhang** [comment]
Can you provide your two POTCARs, INCAR, and a POSCAR ?

**Comment by Gauyer** [comment]
Thanks for your reply , i can't upload the origin incar potcar and poscar so i make them into txt file
The potcar
[Pd_POTCAR.txt](https://github.com/deepmodeling/dpgen/files/8552740/Pd_POTCAR.txt)
[Se_POTCAR.txt](https://github.com/deepmodeling/dpgen/files/8552743/Se_POTCAR.txt)
INCAR:
[INCAR.txt](https://github.com/deepmodeling/dpgen/files/8552745/INCAR.txt)
POSCAR:


[POSCAR1.txt](https://github.com/deepmodeling/dpgen/files/8552762/POSCAR1.txt)
[POSCAR3.txt](https://github.com/deepmodeling/dpgen/files/8552766/POSCAR3.txt)

[POSCAR2.txt](https://github.com/deepmodeling/dpgen/files/8552765/POSCAR2.txt)

**Comment by Gauyer** [comment]
@AnguseZhang Is there any solution , looking for your help~~

**Comment by LiangWenshuo1118** [comment]
I have combined  the two POTCARs via the following command 
cat Pd_POTCAR.txt Se_POTCAR.txt > POTCAR 
and executed the vasp_std command. However, threre is no errors reported.
[files.zip](https://github.com/deepmodeling/dpgen/files/8579993/files.zip)
You can use the combined POTCAR if it still reports an error.

**Comment by LiangWenshuo1118** [comment]
Hi, I have performed the init_bulk task with the POTCAR files you provided and the generated POTCAR works normally.
Is this problem being solved?

**Comment by njzjz** [comment]
I am going to close the issue as it looks like a bug in VASP.
