### ISSUE TITLE
[BUG] dpgen run error:  paramiko.ssh_exception.SSHException: Server connection dropped: 

### ISSUE THREAD

**Issue by baihuyu12** [deepmodeling/dpgen#722]
when I use “dpgen run",  the program run a iteration, and then it is interrupted. An error is reported"paramiko.ssh_exception.SSHException: Server connection dropped: ". 

So I can only manually submit the task again after completing a iteration.

I don't know why ? how can I resolve the error ？

![image](https://user-images.githubusercontent.com/57975158/166853051-e3cf0d0e-7895-4a8f-8985-d882eec7012f.png)

**Comment by AnguseZhang** [comment]
Do you have to use `SSHContext`? Maybe you can use `LocalContext` to transfer files.

**Comment by baihuyu12** [comment]
what is SSHContext and LocalContext?
 I use local machine and pbs to submit  the task.
![image](https://user-images.githubusercontent.com/57975158/166913463-3f9d46ea-8fb7-4c96-b198-c65405c03b51.png)
![image](https://user-images.githubusercontent.com/57975158/166913508-9792f05a-4282-4573-acca-7910ab122e3c.png)![image](https://user-images.githubusercontent.com/57975158/166913594-39c162e1-5e9e-4e7b-92ab-0ce77a7c13ae.png)

**Comment by AnguseZhang** [comment]
Are the login node where DP-GEN runs and computing nodes in the same cluster (such that they share the same storage disk)? If yes, delete `hostname`, `port`, `username`, `password` in each `machine` json and try again.

**Comment by AnguseZhang** [comment]
About the concept of `Context`, you can refer to https://mp.weixin.qq.com/s/iyO29AzB9s0KJBsGDSjdkA (in Chinese).

**Comment by baihuyu12** [comment]
thank u very much, it is fine when I delete hostname, port, username, password in each machine json.
