### ISSUE TITLE
undefined key `hostname` in strict mode?

### ISSUE THREAD

**Issue by kluophysics** [deepmodeling/dpgen#727]
Installed dpgen directly from downloaded github repo, `pip install --user .` and this does not recognized hostname, which is strange.

Also tried to install dpgen from conda (default version v0.10.2), however, the dpgen generate `pair style\n` without two asterisks and the input.lammps generated thus does not run. It seems the version combination is messed up?

***See below.***

`/public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
NOTE: Some configuration directories are not set up yet: 
	/public/home/kluo/.gromacswrapper
	/public/home/kluo/.gromacswrapper/qscripts
	/public/home/kluo/.gromacswrapper/templates
NOTE: You can create the configuration file and directories with:
	>>> import gromacs
	>>> gromacs.config.setup()
/public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/gromacs/__init__.py:286: GromacsImportWarning: Some Gromacs commands were NOT found; maybe source GMXRC first? The following are missing:
['release']

  warnings.warn("Some Gromacs commands were NOT found; "
DeepModeling
------------
Version: 0.10.5
Date:    May-12-2022
Path:    /public/home/kluo/.local/lib/python3.9/site-packages/dpgen

Dependency
------------
     numpy     1.22.3   /public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/numpy
    dpdata      0.2.6   /public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/dpdata
  pymatgen            unknown version or path
     monty  2022.4.26   /public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/monty
       ase     3.22.1   /public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/ase
  paramiko     2.10.4   /public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/paramiko
 custodian  2022.2.13   /public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/custodian

Reference
------------
Please cite:
Yuzhi Zhang, Haidi Wang, Weijie Chen, Jinzhe Zeng, Linfeng Zhang, Han Wang, and Weinan E,
DP-GEN: A concurrent learning platform for the generation of reliable deep learning
based potential energy models, Computer Physics Communications, 2020, 107206.
------------

Description
------------
Traceback (most recent call last):
  File "/public/home/kluo/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/public/home/kluo/.local/lib/python3.9/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/public/home/kluo/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 3236, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/public/home/kluo/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 3212, in run_iter
    run_model_devi (ii, jdata, mdata)
  File "/public/home/kluo/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 1398, in run_model_devi
    run_md_model_devi(iter_index,jdata,mdata)
  File "/public/home/kluo/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 1380, in run_md_model_devi
    submission = make_submission(
  File "/public/home/kluo/.local/lib/python3.9/site-packages/dpgen/dispatcher/Dispatcher.py", line 358, in make_submission
    machine = Machine.load_from_dict(abs_mdata_machine)
  File "/public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/dpdispatcher/machine.py", line 126, in load_from_dict
    base.check_value(machine_dict, strict=True)
  File "/public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/dargs/dargs.py", line 278, in check_value
    self.traverse_value(argdict, 
  File "/public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/dargs/dargs.py", line 241, in traverse_value
    self._traverse_sub(value,
  File "/public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/dargs/dargs.py", line 256, in _traverse_sub
    sub_hook(self, value, path)
  File "/public/home/kluo/.conda/envs/dpgen/lib/python3.9/site-packages/dargs/dargs.py", line 310, in _check_strict
    raise ArgumentKeyError(path,
dargs.dargs.ArgumentKeyError: [at root location] undefined key `hostname` is not allowed in strict mode
`

**Comment by AnguseZhang** [comment]
"Installed dpgen directly from downloaded github repo, pip install --user . and this does not recognized hostname, which is strange." Please provide your `machine.json`.

**Comment by AnguseZhang** [comment]
Probably the keyword `hostname` is set to wrong place. You can refer to https://github.com/deepmodeling/dpgen/blob/master/examples/CH4-refact-dpdispatcher/machine-ali-ehpc.json .

**Comment by njzjz** [comment]
It seems that it's not a bug. The correct location should be `remote_profile/hostname`. See https://docs.deepmodeling.com/projects/dpgen/en/latest/run-mdata.html.

**Comment by kluophysics** [comment]
> 
[run.zip](https://github.com/deepmodeling/dpgen/files/8674153/run.zip)

The `machine.json` file is adapted from the example. It is set in the right place, I believe.

**Comment by AnguseZhang** [comment]
![Screen Shot 2022-05-12 at 5 50 08 PM](https://user-images.githubusercontent.com/38939321/168043439-69fa43b5-0adb-4c9f-8356-b3cd5aaf57f8.jpg)

You set `hostname` for twice in `model_devi` part. Delete the former.

**Comment by kluophysics** [comment]
> ![Screen Shot 2022-05-12 at 5 50 08 PM](https://user-images.githubusercontent.com/38939321/168043439-69fa43b5-0adb-4c9f-8356-b3cd5aaf57f8.jpg)
> 
> You set `hostname` for twice in `model_devi` part. Delete the former.

Thanks, I removed it and other duplicated ones. Now the problem is the `pair_coeff`. 

I checked the `lammps.py` from the path of dpgen.__path__, which in my case is
/public/home/kluo/.local/lib/python3.9/site-packages/dpgen/generator/lib/lammps.py

It includes the right pair_coeff 
`
        ret+= "pair_style      deepmd %s out_freq ${THERMO_FREQ} out_file model_devi.out %s\n" % (graph_list, keywords)
    ret+= "pair_coeff      * *\n"
` 
However,  still though, the error happens with the log file  `task.000.00000*/model_devi.log`

`ERROR: Incorrect args for pair coefficients (src/input.cpp:1717)
Last command: pair_coeff
`
and the generated `input.lammps` contains no asterisks
`
pair_style      deepmd ../graph.000.pb ../graph.001.pb ../graph.002.pb ../graph.003.pb  out_freq ${THERMO_FREQ} out_file model_devi.out 
pair_coeff    
`
Any clue why it is so?

Thanks, again!

**Comment by njzjz** [comment]
Did you rerun the make_model_devi step to regenerate files?

**Comment by kluophysics** [comment]
> Did you rerun the make_model_devi step to regenerate files?

I’m not sure about your question. I cleaned the scratch dir and run dpgen run param machine.

**Comment by AnguseZhang** [comment]
> 
Change `record.dpgen` to let the last line be "N 2", where N is the iteration index.
