### ISSUE TITLE
[BUG] Cannot recognize the failed DFT calculation job at stage 7

### ISSUE THREAD

**Issue by yaomz16** [deepmodeling/dpgen#732]
**Summary**

Dogen is not able to recognize those failed DFT jobs due to "convergence not achieved". I'm running DFT jobs with Quantum Espresso.

**DPGEN Version and Platform**

DPGEN v0.9.2
Linux 3.10.0-1160.59.1.el7.x86_64 #1 SMP  x86_64 x86_64 x86_64 GNU/Linux
Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz

**Job submission and computing cluster configuration**

None

**Expected Behavior**

Dpgen shall recognize DFT jobs that do not converge as failed job, and keep running

**Actual Behavior**

DPGEN recognized the failed DFT jobs (failed to converge after maximum steps) at stage 7 as succeeded jobs and keep running, and in stage 8 it fails because it cannot read the output files of those failed DFT jobs, like this:

 File "...../miniconda3/envs/dp-lammps/lib/python3.7/site-packages/dpdata/qe/scf.py", line 137, in get_frame
    np.array(energy)[np.newaxis], force[np.newaxis, :, :], stress[np.newaxis, :, :]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

PS: I'm running DFT jobs with Quantum Espresso.

**Steps to Reproduce**

Any DFT jobs with QE that is not converged after 100 steps can reproduce the problem. I guess the reason that DPGEN recognizes these jobs as succeeded is that there are "JOB DONE." lines at the end of the output file, which is exactly the same as those converged jobs.

**Further Information, Files, and Links**

/

**Comment by AnguseZhang** [comment]
So has this problem been solved? @yaomz16

**Comment by yaomz16** [comment]
my fault, it’s not a bug
