### ISSUE TITLE
Modify the keywords in param.json

### ISSUE THREAD

**Issue by LiangWenshuo1118** [deepmodeling/dpgen#743]
**Details**
The keywords "model_devi_e_trust_lo" and "model_devi_e_trust_hi" in dpgen/examples seem to be inconsistent with the source code, where they are "model_devi_v_trust_lo" and "model_devi_v_trust_hi".

**Comment by wanghan-iapcm** [comment]
`model_devi_e_trust_lo` and `model_devi_e_trust_hi` are deprecated keys.

**Comment by njzjz** [comment]
Fixed by #807.
