### ISSUE TITLE
[Feature Request] Massive traj dump files in model devi step

### ISSUE THREAD

**Issue by LavendaRaphael** [deepmodeling/dpgen#766]
## Problem

During the model devi step, dpgen generates separate dump files for each snapshot in the `traj` directory.
If the step is long and the number of tasks is large, the number of files will be large, resulting in slow pack compression after the model devi step is completed.
I don't quite understand why dpgen doesn't consider outputting a single dump file, but a large number of single dump files.
Or is there any way to increase the tar speed in this step?

## Possible solutions

- Changed `tar -zc` to `tar -c`, `.tar` is more efficient than `.tar.gz` in my opinion.
- Add `tar -c traj -f traj.tar` commands after each `lmp` command, like `dp compress` in the dp step.
- Execute tar and untar in parallel in dpdispatcher.

**Comment by HuangJiameng** [comment]
> Changed tar -zc to tar -c, .tar is more efficient than .tar.gz in my opinion.
> Add tar -c traj -f traj.tar commands after each lmp command, like dp compress in the dp step.
> Execute tar and untar in parallel in dpdispatcher.
@njzjz how do you think about it

**Comment by njzjz** [comment]
`tar -zc` does compression after packing (not before), so I don't see the meaning not to compress or to pack twice.

**Comment by LavendaRaphael** [comment]
> `tar -zc` does compression after packing (not before), so I don't see the meaning not to compress or to pack twice.

That is, the compression time is small head? I know.
In my case, since file transfers between clusters and individuals are always on the local area network, network speed is not the bottleneck and large files without compression can be transferred quickly.
The main problem here is that packing so many small dump files is very slow, packing and unpacking takes a lot of time, even longer than the computation time in my cluster. So I think if the dump files are packed in real time after each lmp is done on each compute node, then it's just like a parallel execution of packing, then it will save a lot of packing time.

**Comment by njzjz** [comment]
Packing is strongly IO-bound. Parallelism does not make sense.

**Comment by LavendaRaphael** [comment]
> `tar -zc` does compression after packing (not before), so I don't see the meaning not to compress or to pack twice.

I have tested to pack and/or compress 23M `traj.tar` * 700 into a single file.
- Using `tar -cv */traj.tar -f tmp.tar` costs 3 minutes, the final file is 15G
- Using `tar -zcv */traj.tar -f tmp.tgz` costs 40 minutes, the final file is 6.3 G

Also I added `tar` after the `lmp` command to pack `traj/` into `traj.tar` on the fly, and the efficiency has also improved a lot, although I did not carefully calculate the extra time cost in computing nodes.

**Comment by njzjz** [comment]
Your result shows packing is not slow.

How much time does it cost to `gzip tmp.tar`? 40 minutes are quite slow to compress only a 15 GB file. (only 6 MB/s?)

**Comment by LavendaRaphael** [comment]
> Your result shows packing is not slow.
> 
> How much time does it take to `gzip tmp.tar`? 40 minutes are quite slow to compress only a 15 GB file. (only 6 MB/s?)

Also 40 mins

**Comment by njzjz** [comment]
So only gzip is expensive in your machine. We may add an option to skip compression.

**Comment by LavendaRaphael** [comment]
> So only gzip is expensive in your machine. We may add an option to skip compression.

Thank you. You are right, the case is dependent on the machine. I have tested on different machines.

Test files:
- 120 `traj` dirs, each contains 1000 lmp dump files, total is 120000.
- 120 `traj.tar` files, which is the packed file of `traj`, each 23M.
- The final file `.tar` is 2.6 G, `.tgz` is 1.1G

|Time (s)|Remote cluster|Personal Computer|
|---|---|---|
|`tar -c */traj.tar`|25 s|107 s|
|`tar -zc */traj.tar`|411 s|155 s|
|`tar -c */traj`|1479 s|959 s|
|`tar -zc */traj`|1050 s|189 s|

It's strange that if packing dump files directly, sometimes `tar -zc` is faster than `tar -c`.
