### ISSUE TITLE
[BUG] Inconsistent of symlink design

### ISSUE THREAD

**Issue by KZHIWEI** [deepmodeling/dpgen#797]
**Summary**

With the symlink generated by dpgen, the behavior of each symlink are different.
![image](https://user-images.githubusercontent.com/43613336/178457417-8397fb5e-a298-47a9-ac51-cc16c973f6f3.png)

This figure shows data.init point to /data/dpgen_lebesgue which is absolute path.
but graph.00*.pb point to relative path 00*/frozen_model.pb.

**DPGEN Version and Platform**

DeepModeling
------------
Version: 0.10.4
Date:    Mar-30-2022
Path:    /opt/anaconda3/lib/python3.9/site-packages/dpgen

**Expected Behavior**

Should use relative path, since if user copy dpgen files to another location absolute path won't work.

**Comment by HuangJiameng** [comment]
could you provide PARAM file?

**Comment by KZHIWEI** [comment]
> could you provide PARAM file?
[run_param.zip](https://github.com/deepmodeling/dpgen/files/9091659/run_param.zip)

**Comment by HuangJiameng** [comment]
`graph.00[0-3].pb` is generate by dpgen, while `data.init` is set according to PARAM. They are not generated in the same way. If  dpgen files are copied to another location, it's supposed to be restart from the latest make_train step, where data.init is generated.

**Comment by KZHIWEI** [comment]
> `graph.00[0-3].pb` is generate by dpgen, while `data.init` is set according to PARAM. They are not generated in the same way. If dpgen files are copied to another location, it's supposed to be restart from the latest make_train step, where data.init is generated.

Thank you !
