### ISSUE TITLE
[BUG] the incorrect using of assertTrue() in tests/auto_test/test_vasp.py

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/dpgen#826]
**Summary**

In tests/auto_test/test_vasp.py(https://github.com/deepmodeling/dpgen/blob/master/tests/auto_test/test_vasp.py), there has many statements try to compare two values by using assertTrue() function, like `self.assertTrue(incar['ISIF'],4)` in line 73, but this is wrong. This function is used to "Check that the expression is true.", which is comment in the definition:

    def assertTrue(self, expr, msg=None):
        """Check that the expression is true."""
        if not expr:
            msg = self._formatMessage(msg, "%s is not true" % safe_repr(expr))
            raise self.failureException(msg)

**Comment by wanghan-iapcm** [comment]
Thanks for reporting. Could you please PR to fix it ? Thank you!

**Comment by pxlxingliang** [comment]
ok, I will submit a PR later
