### ISSUE TITLE
[BUG] inconsistent type of  the value of 'stress' in outcar_dict['data']['stress']

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/dpgen#827]
**Summary**

The function `compute` in https://github.com/deepmodeling/dpgen/blob/master/dpgen/auto_test/VASP.py is used to collect the data information (e.g. cells, coords, forces, stress, and so on) from OUTCAR, Most of the information are got by function `LabeledSystem(outcar)`, except for the information of 'stress', which is added in current function. 
At the end of this function, key 'stress' is added in the dictionary `outcar_dict['data']`, and the value is a dictionary, which is ` {"@module": "numpy", "@class": "array", "dtype": "float64", "data": stress}`. It was supposed to be a type of `numpy.ndarray`, is it? The other values like 'forces'/'coords'/'virials' has the type of numpy.ndarray. May be we should change the type of outcar_dict['data']['stress'] to be numpy.ndarray?

    def compute(self,
                output_dir):
        outcar = os.path.join(output_dir, 'OUTCAR')
        if not os.path.isfile(outcar):
            dlog.warning("cannot find OUTCAR in " + output_dir + " skip")
            return None
        else:
            ls = LabeledSystem(outcar)
            stress = []
            with open(outcar, 'r') as fin:
                lines = fin.read().split('\n')
            for line in lines:
                if 'in kB' in line:
                    stress_xx = float(line.split()[2])
                    stress_yy = float(line.split()[3])
                    stress_zz = float(line.split()[4])
                    stress_xy = float(line.split()[5])
                    stress_yz = float(line.split()[6])
                    stress_zx = float(line.split()[7])
                    stress.append([])
                    stress[-1].append([stress_xx, stress_xy, stress_zx])
                    stress[-1].append([stress_xy, stress_yy, stress_yz])
                    stress[-1].append([stress_zx, stress_yz, stress_zz])

            outcar_dict = ls.as_dict()
            outcar_dict['data']['stress'] = {"@module": "numpy", "@class": "array", "dtype": "float64", "data": stress}

            return outcar_dict

**Comment by wanghan-iapcm** [comment]
@kevinwenminion Could you please explain why it is designed in this way?

**Comment by kevinwenminion** [comment]
I just make sure that the "stress" in result.json agrees with "virials". The code may be redundant, but it's not a bug. Please see the following example of result.json for "virials" and "stress":

"virials": {
            "@module": "numpy",
            "@class": "array",
            "dtype": "float64",
            "data": [
                [
                    [
                        -0.011566137863845699,
                        0.0,
                        0.0
                    ],
                    [
                        0.0,
                        -0.011566137863845699,
                        0.0
                    ],
                    [
                        0.0,
                        0.0,
                        -0.011566137863845699
                    ]
                ]
            ]
        },
        "stress": {
            "@module": "numpy",
            "@class": "array",
            "dtype": "float64",
            "data": [
                [
                    [
                        -0.68802,
                        0.0,
                        0.0
                    ],
                    [
                        0.0,
                        -0.68802,
                        0.0
                    ],
                    [
                        0.0,
                        0.0,
                        -0.68802
                    ]
                ]
            ]
        }

**Comment by pxlxingliang** [comment]
@kevinwenminion Thanks for your reply, that original codes indeed can realize the requirement.

**Comment by wanghan-iapcm** [comment]
resolved
