### ISSUE TITLE
Is able the "dpgen init_surf" to process two elements system?

### ISSUE THREAD

**Issue by ysu-007** [deepmodeling/dpgen#859]
I want to generate the initial structures for the surface dp potential train.  Here I use a two elements system InSe. The POSCAR is shown in Fig1. 
![image](https://user-images.githubusercontent.com/54423463/183855578-ee4b09fe-2588-418c-8906-27f4cfa7426f.png)
![image](https://user-images.githubusercontent.com/54423463/183855616-fc6b7c5b-65ba-4b19-8ba9-5c579ecd4b22.png)
![image](https://user-images.githubusercontent.com/54423463/183855651-dd061914-8dd2-4f37-96ce-d04ef6ba3303.png)
Fig1
If I select 0 0 1 miller plane, the layer_numb is set to 1,  I got the right surface structure， see Fig 2, the  c axis is much larger than c axis in Fig1 due to extra vacuum.
![image](https://user-images.githubusercontent.com/54423463/183856308-c14e4e60-4d47-4b30-8077-fdfff011bc93.png)
![image](https://user-images.githubusercontent.com/54423463/183856355-b5f4a9f0-e523-4c76-b4bf-e2519832476c.png)
![image](https://user-images.githubusercontent.com/54423463/183856391-0148900e-4119-4408-bae3-5d3831eb5c1c.png)
Fig 2
However, when I select 110  miller plane, the surface structure seems totally wrong, see Fig 3. There are three same-type atoms are in a line which is not the case in InSe POSCAR. So may be there are some problems for the code to process the two elements systems.
![image](https://user-images.githubusercontent.com/54423463/183856824-3d49fad4-b4ef-4628-a156-a9e3e3f76962.png)
![image](https://user-images.githubusercontent.com/54423463/183856838-1404b8e5-aae1-4d79-91f2-3f0c4190b966.png)
![image](https://user-images.githubusercontent.com/54423463/183856864-4078aee1-6d6b-46fa-989b-6ad8f927b547.png)
![image](https://user-images.githubusercontent.com/54423463/183857400-02d413df-5011-450f-a8a6-9da7e169f1ed.png)
Fig 3

**Comment by ysu-007** [comment]
All the structures are shown in the following files.
[structures.zip](https://github.com/deepmodeling/dpgen/files/9298463/structures.zip)

**Comment by HuangJiameng** [comment]
Could you provide your INCAR and PARAM?

**Comment by ysu-007** [comment]
I found where I am wrong. The sruface structure in 00.place_ele/surf-***/POSCAR is right. The surface structures in 00.place_ele/surf-***/sys-000*-000*/POSCAR are specific surfaces with exchange order of atoms. I do not know which kind of specific surfaces they are.
