### ISSUE TITLE
install dpgen

### ISSUE THREAD

**Issue by 13yong** [deepmodeling/dpgen#860]
I meet a error during install dpgen. I get the code dpgen-0.10.6-Linux-x86_64.sh from our web. But when I finished install, It dosen't work. The error information as below:
![WHLVL@N9PXD6WQ`MWX7C)ND](https://user-images.githubusercontent.com/90954282/184078749-3052fb07-d801-4924-afdc-643134f48165.png)

**Comment by HuangJiameng** [comment]
see #833

**Comment by AnguseZhang** [comment]
The solution in #833 should work, so I closed this issue.
