### ISSUE TITLE
update DP-GEN Docs

### ISSUE THREAD

**Issue by HuangJiameng** [deepmodeling/dpgen#883]
1. add docs
    - [x] user guide 
    - [x] common-errors
2. add tutorials
    - [x] Handson autotest
    - [x] Case Study : Mg-Y for `dpgen run`
    - [x] Case Study : Transfer Learning for `dpgen simplify`
3. update tutorials to the lastest version (v0.10.6)
    - [x] Handson tutorial (CH4)
4. Move the docs from README and wiki to [Docs/DPGEN](https://docs.deepmodeling.com/projects/dpgen/en/latest/)
     - [x] run
     - [x] init_bulk
     - [x] init_surf
     - [x] simplify
     - [x] autotest
     - [x] troubleshooting

**Comment by njzjz** [comment]
Here is the current TOC:
![image](https://user-images.githubusercontent.com/9496702/186020009-9b08d162-925d-433f-af97-411bdccb0ffc.png)

I suggest merging `run`, `init`, and `simplify` into a section called `workflow`, and making each of them a chapter (the same level as "Command line interface").

**Comment by HuangJiameng** [comment]
All docs are updated to the website. TOC will be managed.

**Comment by njzjz** [comment]
Since the website is ready, we may remove out-of-date contents in `README.md`, as we don't want to maintain two identical things. Just a confirmation, have all contents in `README.md` been transferred to the website?

**Comment by HuangJiameng** [comment]
The part of old dispatcher is not transferred. I'm wondering if we should keep it. This is the current introduction to `machine` https://docs.deepmodeling.com/projects/dpgen/en/devel/run/example-of-machine.html

**Comment by njzjz** [comment]
We do not need to keep it. But I found #777 and #778 are not resolved yet.

**Comment by HuangJiameng** [comment]
OK, I will add examples for them and update arginfo.
