### ISSUE TITLE
The "user_forward_files" command for dpgen Init_surf is not working？ Please check, thanks.

### ISSUE THREAD

**Issue by ysu-007** [deepmodeling/dpgen#889]
I do not see any "user_forward_files" code in dpgen source code and the command is also not working.

**Comment by HuangJiameng** [comment]
https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/task.html#argument:task/forward_files I think you need parameter `forward_files`. Its name has been changed in new dpdispatcher.

**Comment by HuangJiameng** [comment]
The content in README will be updated and move to [DPGEN's Document](https://docs.deepmodeling.com/projects/dpgen/en/latest/) soon. The introduction to Machine parameters see [DP-Dispatcher's Document](https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/).

**Comment by HuangJiameng** [comment]
I see. `init_surf` doesn't support `forward_files` yet. I will fix it.

**Comment by ysu-007** [comment]
The function will be added in future version.
