### ISSUE TITLE
How can I know the exact meaning of the parameter "head_ratio" in the surf_init input file?

### ISSUE THREAD

**Issue by ysu-007** [deepmodeling/dpgen#924]
**Summary**

**DPGEN Version and Platform**

**Job submission and computing cluster configuration**

**Details**

DeepModeling
------------
Version: 0.10.6
Date:    Aug-19-2022
Path:    /root/.local/lib/python3.9/site-packages/dpgen

Platform 
Bohrium

I met a piece of error information when I used dpgen init_surf command. However, I can't find the exact meaning of the parameter "head_ratio" in the manual. 

Error information
![image](https://user-images.githubusercontent.com/54423463/187106288-0a475795-e0ea-410e-afa3-91fe37c4d3cf.png)

**Comment by HuangJiameng** [comment]
According to https://github.com/deepmodeling/dpgen/blob/8dea29ef125f66be9641afe5ac4970433a9c9ce1/dpgen/data/surf.py#L484
init_surf will generate a series of surface structures with specified separations between the sample layer and its periodic image. There are two ways to specify the intervel in generating the vacuum layers: 1) to set the interval value and 2) to set the number of intervals. The whole interval range is divided into the nearby region with denser intervals (head region) and the far-away region with sparser intervals (tail region), which are divided by mid_point. The number of intervals in the head region = vacuum_num * head_ratio. `vacuum_num` and `head_ratio` are both keys in `param.json`.
(Thanks to the answer from @Vibsteamer. `init_surf_jdata_arginfo` need to be added.)

**Comment by HuangJiameng** [comment]
please follow #778
