### ISSUE TITLE
[Feature Request] improvements of model_devi process on remote server

### ISSUE THREAD

**Issue by wankiwi** [deepmodeling/dpgen#938]
During the model deviation step, I found that downloading and unzipping files from the remote is very time-consuming in the case of a large number of trajectories.
At present, the process of dpgen is to download the trajectory to the local and then obtain the candidate structures through analysis. If it can be changed to analyze the trajectory on the remote server, get the candidate structure and then download it locally, it can avoid downloading large trajectory files, greatly speeds up the process.
I hope the developers can consider my suggestion, thank you very much.

**Comment by HuangJiameng** [comment]
Picking candidates is in `make_fp` step. Since we only need the remote server to run MD with LAMMPS, which is `run_model_devi` step, it's a breaking change to do what you said. Maybe you can try `merge_traj` to print all trajectories in one file. See #838. It may speed up the process.

**Comment by wankiwi** [comment]
I tried the merge_traj function, and got the following error.
`  File "/home/kwwan/software/Anaconda3/lib/python3.8/site-packages/dpdispatcher/ssh_context.py", line 409, in _walk_directory raise RuntimeError(f'cannot find upload file {work_path} {jj}')  
RuntimeError: cannot find upload file task.005.000000 all.lammpstrj
`
How to solve it?

**Comment by HuangJiameng** [comment]
Could you provide your input files to help locate and reproduce the problem?

**Comment by wankiwi** [comment]
> I tried the merge_traj function, and got the following error. ` File "/home/kwwan/software/Anaconda3/lib/python3.8/site-packages/dpdispatcher/ssh_context.py", line 409, in _walk_directory raise RuntimeError(f'cannot find upload file {work_path} {jj}') RuntimeError: cannot find upload file task.005.000000 all.lammpstrj` How to solve it?

[param.zip](https://github.com/deepmodeling/dpgen/files/9541879/param.zip)
param.json is attached. Thanks.

**Comment by HuangJiameng** [comment]
Could you show your directory tree under `01.model_devi/task.005.000000`? Have you re-run the process before `make_model_devi` step? And `model_devi_merge_traj` is false in the `param.json` you provide. I think `merge_traj` won't be applied unless it is true.

**Comment by wankiwi** [comment]
> Could you show your directory tree under `01.model_devi/task.005.000000`? Have you re-run the process from `make_model_devi` step? And `model_devi_merge_traj` is false in the `param.json` you provide. I think `merge_traj` won't be applied unless it is true.

Sorry, I attached the wrong param.json file. As after it run with error,  I turn off the merge_traj. The only difference between the param.json corresponding to the "RuntimeError" and the attached param.json is that the model_devi_merge_traj is true. 
The directory tree under 01.model_devi/task.005.000000 is like this:
`task.005.000000`
`├── conf.lmp -> ../confs/005.0000.lmp`  
`├── input.lammps`
`├── job.json`

And I did not rerun the process from make_model_devi.
Thanks.

**Comment by HuangJiameng** [comment]
In `make_model_devi` step, `"dump            1 all custom ${DUMP_FREQ} all.lammpstrj id type x y z fx fy fz\n"` is written in `input.lammps`. This means if traj is needed to be printed into one file, the process should be rerun from `make_model_devi` step.

**Comment by wankiwi** [comment]
Same error as: https://github.com/deepmodeling/dpgen/pull/944#issuecomment-1244751009. Lammps throwed this error:
`ERROR on proc 0: Cannot open dump file (src/dump.cpp:604)` 
This error is because there is no traj folder under the current file, which contradicts the setting of input.lammps:
`dump            1 all custom ${DUMP_FREQ} traj/*.lammpstrj id type x y z fx fy fz`

**Comment by HuangJiameng** [comment]
@wankiwi  It is fixed, please take a look.

**Comment by wankiwi** [comment]
> @wankiwi It is fixed, please take a look.

Sorry, I forgot to reply. I have greatly reduced the trajectory file size after using the merge_traj option, which has solved my problem to a large extent. Thank you!
