### ISSUE TITLE
error when use "pip install --user ." to install the dpgen 

### ISSUE THREAD

**Issue by wanghaopku** [deepmodeling/dpgen#98]
I have successflully installed the dpgen package on one supercomputer before. But this time when i use "pip install --user ." on another computer, there was an error: 

ERROR: Could not install packages due to an EnvironmentError: [('/lustre3/jmxue_pkuhpc/software/lammps_software/dpgen/.git/objects/pack/pack-add722551b0cd46bae0c45e5a3f94d4a4578e1ca.pack', '/ram/tmp/pip-req-build-_ks46gq9/.git/objects/pack/pack-add722551b0cd46bae0c45e5a3f94d4a4578e1ca.pack', "[Errno 13] Permission denied: '/ram/tmp/pip-req-build-_ks46gq9/.git/objects/pack/pack-add722551b0cd46bae0c45e5a3f94d4a4578e1ca.pack'"), ('/lustre3/jmxue_pkuhpc/software/lammps_software/dpgen/.git/objects/pack/pack-add722551b0cd46bae0c45e5a3f94d4a4578e1ca.idx', '/ram/tmp/pip-req-build-_ks46gq9/.git/objects/pack/pack-add722551b0cd46bae0c45e5a3f94d4a4578e1ca.idx', "[Errno 13] Permission denied: '/ram/tmp/pip-req-build-_ks46gq9/.git/objects/pack/pack-add722551b0cd46bae0c45e5a3f94d4a4578e1ca.idx'")]

it seems i don't have the permission, but i can make document using "mkdir -p ram/tmp/pip-req-build-_ks46gq9/.git/objects/pack/". I don't know why this error occured. So i simply  use "python setup.py install" as well as installing the dpdata. And it works, and the installed PATH is  
“/home/jmxue_pkuhpc/lustre3/anaconda3/envs/deepMD/bin/dpgen” .

**Comment by njzjz** [comment]
pypa/pip#4525
