### ISSUE TITLE
An error occurred during structure copy in 01.model_devi

### ISSUE THREAD

**Issue by caojiachun** [deepmodeling/dpgen#997]
**An error occurred during the structure transformation after restarting dpgen. It worked fine until now.**

**dpgen 2.1.1**

****

**iter.000000/01.model_devi/confs**
![image](https://user-images.githubusercontent.com/71744229/195976144-c5015f0d-fb45-4d87-b6fe-75b134724a5b.png)

![image](https://user-images.githubusercontent.com/71744229/195976164-bc842602-5772-4b3d-b498-467b4bedce5b.png)
000.000.poscar
![image](https://user-images.githubusercontent.com/71744229/195976187-9afbe5e1-536d-4709-aaa0-e21654b906ec.png)

**Comment by HuangJiameng** [comment]
It seems like that you have set `shuffle_poscar` as True? If it can't work after turning `shuffle_poscar` to false, please provide your `param.json`. https://docs.deepmodeling.com/projects/dpgen/en/devel/run/param.html#argument:run_jdata[model_devi_engine=lammps]/shuffle_poscar

**Comment by caojiachun** [comment]
Thank you, I misunderstood the meanning of shuffle_poscar and set it of "true". The error no longer occurs when I set it to "false".
